// This file was auto-generated by the card stub generator.
// Card effects were implemented by an agent.
// If you have any questions or feedback, reach out to @C4 in the discord.

import { PokemonCard } from '../../../game/store/card/pokemon-card';
import { Stage, CardType } from '../../../game/store/card/card-types';
import { StoreLike, State, StateUtils } from '../../../game';
import { Effect } from '../../../game/store/effects/effect';
import {WAS_ATTACK_USED, DISCARD_TOP_X_CARDS_FROM_YOUR_DECK, MOVE_CARDS } from '../../../game/store/prefabs/prefabs';

export class Tyranitar extends PokemonCard {
  public stage: Stage = Stage.STAGE_2;
  public evolvesFrom: string = 'Pupitar';
  public cardType: CardType[] = [F];
  public hp: number = 180;
  public weakness = [{ type: G }];
  public retreat = [C, C, C, C];

  public attacks = [
    {
      name: 'Bedrock Breaker',
      cost: [F, C, C],
      damage: 120,
      text: 'Discard a Stadium in play.'
    },
    {
      name: 'Mountain Swing',
      cost: [F, F, C, C],
      damage: 250,
      text: 'Discard the top 5 cards of your deck.'
    }
  ];

  public regulationMark: string = 'D';
  public set: string = 'DAA';
  public setNumber: string = '88';
  public cardImage: string = 'assets/cardback.png';
  public name: string = 'Tyranitar';
  public fullName: string = 'Tyranitar DAA';

  public reduceEffect(store: StoreLike, state: State, effect: Effect): State {
    // Attack 1: Bedrock Breaker
    // Ref: set-chilling-reign/castform-sunny-form.ts (discard stadium in play)
    if (WAS_ATTACK_USED(effect, 0, this)) {
      const stadiumCard = StateUtils.getStadiumCard(state);
      if (stadiumCard !== undefined) {
        const cardList = StateUtils.findCardList(state, stadiumCard);
        const owner = StateUtils.findOwner(state, cardList);
        MOVE_CARDS(store, state, cardList, owner.discard, { sourceCard: this });
      }
    }

    // Attack 2: Mountain Swing
    // Ref: set-rebel-clash/spiritomb.ts (DISCARD_TOP_X_CARDS_FROM_YOUR_DECK)
    if (WAS_ATTACK_USED(effect, 1, this)) {
      const player = effect.player;
      DISCARD_TOP_X_CARDS_FROM_YOUR_DECK(store, state, player, 5, this, effect);
    }

    return state;
  }
}
