// This file was auto-generated by the card stub generator.
// Card effects were implemented by an agent.
// If you have any questions or feedback, reach out to @C4 in the discord.

import { PokemonCard } from '../../../game/store/card/pokemon-card';
import { Stage, CardType, SuperType } from '../../../game/store/card/card-types';
import { StoreLike, State, GameMessage, Card, PokemonCardList } from '../../../game';
import { Effect } from '../../../game/store/effects/effect';
import { AttackEffect } from '../../../game/store/effects/game-effects';
import {WAS_ATTACK_USED, SHUFFLE_DECK, MOVE_CARDS } from '../../../game/store/prefabs/prefabs';
import { ChooseCardsPrompt } from '../../../game/store/prompts/choose-cards-prompt';
import { StateUtils } from '../../../game/store/state-utils';

function* useAscension(next: Function, store: StoreLike, state: State,
  self: Cosmog, effect: AttackEffect): IterableIterator<State> {
  const player = effect.player;

  if (player.deck.cards.length === 0) {
    return state;
  }

  let cards: Card[] = [];
  yield store.prompt(state, new ChooseCardsPrompt(
    player,
    GameMessage.CHOOSE_CARD_TO_EVOLVE,
    player.deck,
    { superType: SuperType.POKEMON, evolvesFrom: 'Cosmog' },
    { min: 1, max: 1, allowCancel: true }
  ), selected => {
    cards = selected || [];
    next();
  });

  if (cards.length > 0) {
    const pokemonCardList = StateUtils.findCardList(state, self) as PokemonCardList;
    MOVE_CARDS(store, state, player.deck, pokemonCardList, { cards: cards, sourceCard: self });
    pokemonCardList.clearEffects();
    pokemonCardList.pokemonPlayedTurn = state.turn;
  }

  return SHUFFLE_DECK(store, state, player);
}

export class Cosmog extends PokemonCard {
  public stage: Stage = Stage.BASIC;
  public cardType: CardType[] = [P];
  public hp: number = 50;
  public weakness = [{ type: P }];
  public retreat = [C];

  public attacks = [
    {
      name: 'Ascension',
      cost: [P],
      damage: 0,
      text: 'Search your deck for a card that evolves from this Pokémon and put it onto this Pokémon to evolve it. Then, shuffle your deck.'
    }
  ];

  public set: string = 'CEC';
  public setNumber: string = '99';
  public cardImage: string = 'assets/cardback.png';
  public name: string = 'Cosmog';
  public fullName: string = 'Cosmog CEC';

  public reduceEffect(store: StoreLike, state: State, effect: Effect): State {
    // Attack 1: Ascension
    // Ref: set-forbidden-light/gabite.ts (Ascension)
    if (WAS_ATTACK_USED(effect, 0, this)) {
      const generator = useAscension(() => generator.next(), store, state, this, effect);
      return generator.next().value;
    }

    return state;
  }
}
