// This file was auto-generated by the card stub generator.
// Card effects were implemented by an agent.
// If you have any questions or feedback, reach out to @C4 in the discord.

import { PokemonCard } from '../../../game/store/card/pokemon-card';
import { Stage, CardType, SpecialCondition } from '../../../game/store/card/card-types';
import { PowerType, StoreLike, State, StateUtils, ConfirmPrompt, GameMessage, ShowCardsPrompt } from '../../../game';
import { Effect } from '../../../game/store/effects/effect';
import {WAS_ATTACK_USED, JUST_EVOLVED, IS_ABILITY_BLOCKED, MULTIPLE_COIN_FLIPS_PROMPT, SHUFFLE_DECK, MOVE_CARDS } from '../../../game/store/prefabs/prefabs';
import { AddSpecialConditionsEffect } from '../../../game/store/effects/attack-effects';

export class Florges extends PokemonCard {
  public stage: Stage = Stage.STAGE_2;
  public evolvesFrom: string = 'Floette';
  public cardType: CardType[] = [Y];
  public hp: number = 130;
  public weakness = [{ type: M }];
  public resistance = [{ type: D, value: -20 }];
  public retreat = [C, C];

  public powers = [{
    name: 'Flower Picking',
    powerType: PowerType.ABILITY,
    text: 'When you play this Pokémon from your hand to evolve 1 of your Pokémon during your turn, you may choose 2 random cards from your opponent\'s hand. Your opponent reveals those cards and shuffles them into their deck.'
  }];

  public attacks = [{
    name: 'Petal Dance',
    cost: [Y, C],
    damage: 60,
    damageCalculation: 'x',
    text: 'Flip 3 coins. This attack does 60 damage for each heads. This Pokémon is now Confused.'
  }];

  public set: string = 'CEC';
  public setNumber: string = '152';
  public cardImage: string = 'assets/cardback.png';
  public name: string = 'Florges';
  public fullName: string = 'Florges CEC';

  public reduceEffect(store: StoreLike, state: State, effect: Effect): State {
    // Ability: Flower Picking (on-evolve)
    // Ref: set-hidden-fates/charmeleon.ts (Burning Fighter - on-evolve)
    if (JUST_EVOLVED(effect, this)) {
      const player = effect.player;

      if (IS_ABILITY_BLOCKED(store, state, player, this)) {
        return state;
      }

      const opponent = StateUtils.getOpponent(state, player);

      if (opponent.hand.cards.length === 0) {
        return state;
      }

      state = store.prompt(state, new ConfirmPrompt(
        player.id,
        GameMessage.WANT_TO_USE_ABILITY
      ), wantToUse => {
        if (wantToUse) {
          const handSize = opponent.hand.cards.length;
          const numToShuffle = Math.min(2, handSize);

          // Choose random cards
          const indices: number[] = [];
          while (indices.length < numToShuffle) {
            const idx = Math.floor(Math.random() * handSize);
            if (!indices.includes(idx)) {
              indices.push(idx);
            }
          }

          const randomCards = indices.map(i => opponent.hand.cards[i]);

          // Show the cards
          store.prompt(state, new ShowCardsPrompt(
            player.id,
            GameMessage.CARDS_SHOWED_BY_THE_OPPONENT,
            randomCards
          ), () => {
            // Shuffle those cards into the opponent's deck
            randomCards.forEach(c => {
              MOVE_CARDS(store, state, opponent.hand, opponent.deck, { cards: [c], sourceCard: this });
            });
            SHUFFLE_DECK(store, state, opponent);
          });
        }
      });
    }

    // Attack 1: Petal Dance
    // Ref: set-hidden-fates/zapdos.ts (MULTIPLE_COIN_FLIPS_PROMPT)
    if (WAS_ATTACK_USED(effect, 0, this)) {
      const player = effect.player;

      MULTIPLE_COIN_FLIPS_PROMPT(store, state, player, 3, results => {
        const heads = results.filter(r => r).length;
        effect.damage = 60 * heads;
      });

      // This Pokemon is now Confused
      const addConfusion = new AddSpecialConditionsEffect(effect, [SpecialCondition.CONFUSED]);
      addConfusion.target = player.active;
      store.reduceEffect(state, addConfusion);
    }

    return state;
  }
}
