// This file was auto-generated by the card stub generator.
// Card effects were implemented by an agent.
// If you have any questions or feedback, reach out to @C4 in the discord.

import { PokemonCard } from '../../../game/store/card/pokemon-card';
import { Stage, CardType, SuperType } from '../../../game/store/card/card-types';
import { PowerType, StoreLike, State, StateUtils, GameMessage, PlayerType, SlotType } from '../../../game';
import { AttachEnergyPrompt } from '../../../game/store/prompts/attach-energy-prompt';
import { CheckPokemonTypeEffect } from '../../../game/store/effects/check-effects';
import { Effect } from '../../../game/store/effects/effect';
import {WAS_ATTACK_USED, IS_ABILITY_BLOCKED, MOVE_CARDS } from '../../../game/store/prefabs/prefabs';

export class Gallade extends PokemonCard {
  public stage: Stage = Stage.STAGE_2;
  public evolvesFrom: string = 'Kirlia';
  public cardType: CardType[] = [P];
  public hp: number = 160;
  public weakness = [{ type: P }];
  public retreat = [C, C];

  public powers = [{
    name: 'Double Type',
    powerType: PowerType.ABILITY,
    text: 'As long as this Pokémon is in play, it is Psychic and Fighting type.'
  }];

  public attacks = [
    {
      name: 'Power Cyclone',
      cost: [C, C],
      damage: 120,
      text: 'Move an Energy from this Pokémon to 1 of your Benched Pokémon.'
    }
  ];

  public set: string = 'CEC';
  public setNumber: string = '82';
  public cardImage: string = 'assets/cardback.png';
  public name: string = 'Gallade';
  public fullName: string = 'Gallade CEC';

  public reduceEffect(store: StoreLike, state: State, effect: Effect): State {
    // Ability: Double Type (passive - adds Fighting type)
    // Ref: set-cosmic-eclipse/heliolisk.ts (CheckPokemonTypeEffect pattern)
    if (effect instanceof CheckPokemonTypeEffect && effect.target.getPokemonCard() === this) {
      const player = StateUtils.findOwner(state, effect.target);

      if (IS_ABILITY_BLOCKED(store, state, player, this)) {
        return state;
      }

      if (!effect.cardTypes.includes(CardType.FIGHTING)) {
        effect.cardTypes.push(CardType.FIGHTING);
      }
    }

    // Attack 1: Power Cyclone
    // Ref: set-burning-shadows/simipour.ts (Aqua Reflect - move energy to bench)
    if (WAS_ATTACK_USED(effect, 0, this)) {
      const player = effect.player;
      const hasBench = player.bench.some(b => b.cards.length > 0);

      if (!hasBench) {
        return state;
      }

      const attachedEnergies = player.active.cards.filter(card =>
        card.superType === SuperType.ENERGY
      );

      if (attachedEnergies.length === 0) {
        return state;
      }

      return store.prompt(state, new AttachEnergyPrompt(
        player.id,
        GameMessage.ATTACH_ENERGY_TO_BENCH,
        player.active,
        PlayerType.BOTTOM_PLAYER,
        [SlotType.BENCH],
        { superType: SuperType.ENERGY },
        { allowCancel: false, min: 1, max: 1 }
      ), transfers => {
        transfers = transfers || [];
        for (const transfer of transfers) {
          const target = StateUtils.getTarget(state, player, transfer.to);
          MOVE_CARDS(store, state, player.active, target, { cards: [transfer.card], sourceCard: this });
        }
      });
    }

    return state;
  }
}
