// This file was auto-generated by the card stub generator.
// Card effects were implemented by an agent.
// If you have any questions or feedback, reach out to @C4 in the discord.

import { PokemonCard } from '../../../game/store/card/pokemon-card';
import { Stage, CardType, EnergyType, SuperType } from '../../../game/store/card/card-types';
import { StoreLike, State, GameMessage, ChooseCardsPrompt, Card } from '../../../game';
import { EnergyCard } from '../../../game/store/card/energy-card';
import { Effect } from '../../../game/store/effects/effect';
import {WAS_ATTACK_USED, MOVE_CARDS } from '../../../game/store/prefabs/prefabs';
import { DISCARD_X_ENERGY_FROM_THIS_POKEMON } from '../../../game/store/prefabs/costs';
import { DISCARD_AN_ENERGY_FROM_OPPONENTS_ACTIVE_POKEMON } from '../../../game/store/prefabs/attack-effects';

export class Torkoal extends PokemonCard {
  public stage: Stage = Stage.BASIC;
  public cardType: CardType[] = [R];
  public hp: number = 110;
  public weakness = [{ type: W }];
  public retreat = [C, C];

  public attacks = [
    {
      name: 'Fire Fling',
      cost: [R],
      damage: 0,
      text: 'Put 4 [R] Energy cards from your discard pile into your hand.'
    },
    {
      name: 'Kindle',
      cost: [R, R, R],
      damage: 100,
      text: 'Discard an Energy from this Pokémon. If you do, discard an Energy from your opponent\'s Active Pokémon.'
    }
  ];

  public set: string = 'CEC';
  public setNumber: string = '29';
  public cardImage: string = 'assets/cardback.png';
  public name: string = 'Torkoal';
  public fullName: string = 'Torkoal CEC';

  public reduceEffect(store: StoreLike, state: State, effect: Effect): State {
    // Attack 1: Fire Fling
    // Ref: set-unbroken-bonds/fire-crystal.ts (recover fire energy from discard)
    if (WAS_ATTACK_USED(effect, 0, this)) {
      const player = effect.player;

      let energyInDiscard = 0;
      player.discard.cards.forEach(c => {
        if (c instanceof EnergyCard
          && c.energyType === EnergyType.BASIC
          && c.provides.includes(CardType.FIRE)) {
          energyInDiscard++;
        }
      });

      if (energyInDiscard === 0) {
        return state;
      }

      const count = Math.min(4, energyInDiscard);

      return store.prompt(state, new ChooseCardsPrompt(
        player,
        GameMessage.CHOOSE_CARD_TO_HAND,
        player.discard,
        { superType: SuperType.ENERGY, energyType: EnergyType.BASIC, name: 'Fire Energy' },
        { min: count, max: count, allowCancel: false }
      ), selected => {
        const cards: Card[] = selected || [];
        cards.forEach(c => { MOVE_CARDS(store, state, player.discard, player.hand, { cards: [c], sourceCard: this }); });
      });
    }

    // Attack 2: Kindle
    // Refs: set-hidden-fates/charmeleon.ts (Flamethrower), AGENTS-patterns.md (discard opponent energy)
    if (WAS_ATTACK_USED(effect, 1, this)) {
      DISCARD_X_ENERGY_FROM_THIS_POKEMON(store, state, effect, 1);
      DISCARD_AN_ENERGY_FROM_OPPONENTS_ACTIVE_POKEMON(store, state, effect);
    }

    return state;
  }
}
