// This file was auto-generated by the card stub generator.
// Card effects were implemented by an agent.
// If you have any questions or feedback, reach out to @C4 in the discord.

import { PokemonCard } from '../../../game/store/card/pokemon-card';
import {
  Stage,
  CardType,
  CardTag,
  SuperType,
  EnergyType,
} from '../../../game/store/card/card-types';
import {
  PowerType,
  StoreLike,
  State,
  GameError,
  GameMessage,
  PlayerType,
  SlotType,
  Card,
  StateUtils,
  PokemonCardList,
} from '../../../game';
import { EnergyCard } from '../../../game/store/card/energy-card';
import { Effect } from '../../../game/store/effects/effect';
import { ChooseCardsPrompt } from '../../../game/store/prompts/choose-cards-prompt';
import { ChoosePokemonPrompt } from '../../../game/store/prompts/choose-pokemon-prompt';
import {WAS_ATTACK_USED,
  WAS_POWER_USED,
  IS_ABILITY_BLOCKED,
  USE_ABILITY_ONCE_PER_TURN,
  ABILITY_USED,
  REMOVE_MARKER_AT_END_OF_TURN,
  BLOCK_IF_GX_ATTACK_USED, MOVE_CARDS } from '../../../game/store/prefabs/prefabs';

export class VolcaronaGx extends PokemonCard {
  protected _tags = [CardTag.POKEMON_GX];
  public stage: Stage = Stage.STAGE_1;
  public evolvesFrom: string = 'Larvesta';
  public cardType: CardType[] = [R];
  public hp: number = 210;
  public weakness = [{ type: W }];
  public retreat = [C, C, C];

  public readonly FLAMING_SHOT_MARKER = 'VOLCARONA_GX_CEC_FLAMING_SHOT_MARKER';

  public powers = [
    {
      name: 'Flaming Shot',
      useWhenInPlay: true,
      powerType: PowerType.ABILITY,
      text: "Once during your turn (before your attack), you may discard a [R] Energy card from your hand. If you do, put 2 damage counters on 1 of your opponent's Pokémon.",
    },
  ];

  public attacks = [
    {
      name: 'Backfire',
      cost: [R, R, C],
      damage: 160,
      text: 'Put 2 [R] Energy attached to this Pokémon into your hand.',
    },
    {
      name: 'Massive Heat Wave-GX',
      cost: [R],
      damage: 0,
      text: "Discard an Energy from each of your opponent's Pokémon. (You can't use more than 1 GX attack in a game.)",
    },
  ];

  public set: string = 'CEC';
  public setNumber: string = '35';
  public cardImage: string = 'assets/cardback.png';
  public name: string = 'Volcarona-GX';
  public fullName: string = 'Volcarona-GX CEC';

  public reduceEffect(store: StoreLike, state: State, effect: Effect): State {
    // Ability: Flaming Shot
    // Ref: set-x-and-y/greninja.ts (Water Shuriken - discard energy from hand, put damage counters on opponent's Pokemon)
    if (WAS_POWER_USED(effect, 0, this)) {
      const player = effect.player;

      if (IS_ABILITY_BLOCKED(store, state, player, this)) {
        throw new GameError(GameMessage.BLOCKED_BY_EFFECT);
      }

      // Check for [R] Energy in hand
      const hasFireEnergy = player.hand.cards.some(
        (c) =>
          c instanceof EnergyCard &&
          c.energyType === EnergyType.BASIC &&
          c.provides.includes(CardType.FIRE),
      );

      if (!hasFireEnergy) {
        throw new GameError(GameMessage.CANNOT_USE_POWER);
      }

      USE_ABILITY_ONCE_PER_TURN(player, this.FLAMING_SHOT_MARKER, this);
      ABILITY_USED(player, this);

      // Discard a [R] Energy from hand
      store.prompt(
        state,
        new ChooseCardsPrompt(
          player,
          GameMessage.CHOOSE_CARD_TO_DISCARD,
          player.hand,
          { superType: SuperType.ENERGY, energyType: EnergyType.BASIC, name: 'Fire Energy' },
          { allowCancel: false, min: 1, max: 1 },
        ),
        (cards) => {
          cards = cards || [];
          if (cards.length > 0) {
            MOVE_CARDS(store, state, player.hand, player.discard, { cards: cards, sourceCard: this });

            // Put 2 damage counters on 1 of opponent's Pokemon
            store.prompt(
              state,
              new ChoosePokemonPrompt(
                player.id,
                GameMessage.CHOOSE_POKEMON_TO_DAMAGE,
                PlayerType.TOP_PLAYER,
                [SlotType.ACTIVE, SlotType.BENCH],
                { allowCancel: false },
              ),
              (targets) => {
                if (targets && targets.length > 0) {
                  targets[0].damage += 20;
                }
              },
            );
          }
        },
      );
    }

    REMOVE_MARKER_AT_END_OF_TURN(effect, this.FLAMING_SHOT_MARKER, this);

    // Attack 1: Backfire
    // Ref: set-guardians-rising/talonflame.ts (energy to hand pattern)
    if (WAS_ATTACK_USED(effect, 0, this)) {
      const player = effect.player;
      const cardList = StateUtils.findCardList(state, this) as PokemonCardList;

      // Find Fire Energy attached to this Pokemon
      const fireEnergy = cardList.cards.filter(
        (c) =>
          c instanceof EnergyCard &&
          c.energyType === EnergyType.BASIC &&
          c.provides.includes(CardType.FIRE),
      );

      if (fireEnergy.length > 0) {
        const toMove = fireEnergy.slice(0, 2);
        toMove.forEach((card) => {
          MOVE_CARDS(store, state, cardList, player.hand, { cards: [card], sourceCard: this });
        });
      }
    }

    // Attack 2: Massive Heat Wave-GX
    // Ref: set-crimson-invasion/gyarados-gx.ts (Dread Storm-GX - discard energy from each opponent's Pokemon)
    if (WAS_ATTACK_USED(effect, 1, this)) {
      const player = effect.player;
      const opponent = StateUtils.getOpponent(state, player);

      BLOCK_IF_GX_ATTACK_USED(player);
      player.usedGX = true;

      // For each opponent Pokemon with energy, discard 1 energy
      const pokemonWithEnergy: { cardList: PokemonCardList; energyCards: Card[] }[] = [];
      opponent.forEachPokemon(PlayerType.TOP_PLAYER, (cardList) => {
        const energyCards = cardList.cards.filter((c: Card) => c instanceof EnergyCard);
        if (energyCards.length > 0) {
          pokemonWithEnergy.push({ cardList, energyCards });
        }
      });

      pokemonWithEnergy.forEach(({ cardList, energyCards }) => {
        if (energyCards.length === 1) {
          MOVE_CARDS(store, state, cardList, opponent.discard, { cards: [energyCards[0]], sourceCard: this });
        } else {
          store.prompt(
            state,
            new ChooseCardsPrompt(
              player,
              GameMessage.CHOOSE_CARD_TO_DISCARD,
              cardList,
              { superType: SuperType.ENERGY },
              { min: 1, max: 1, allowCancel: false },
            ),
            (selected: Card[]) => {
              const cards = selected || [];
              cards.forEach((card: Card) => {
                MOVE_CARDS(store, state, cardList, opponent.discard, { cards: [card], sourceCard: this });
              });
            },
          );
        }
      });
    }

    return state;
  }
}
