// This file was auto-generated by the card stub generator.
// Card effects were implemented by an agent.
// If you have any questions or feedback, reach out to @C4 in the discord.

import { PokemonCard } from '../../../game/store/card/pokemon-card';
import {
  Stage,
  CardType,
  CardTag,
  SuperType,
  EnergyType,
} from '../../../game/store/card/card-types';
import {
  StoreLike,
  State,
  PlayerType,
  SlotType,
  GameMessage,
  StateUtils,
  AttachEnergyPrompt,
} from '../../../game';
import { EnergyCard } from '../../../game/store/card/energy-card';
import { Effect } from '../../../game/store/effects/effect';
import {WAS_ATTACK_USED, MOVE_CARDS } from '../../../game/store/prefabs/prefabs';
import { PutDamageEffect } from '../../../game/store/effects/attack-effects';
import { CardList } from '../../../game/store/state/card-list';

export class ExcadrillEx extends PokemonCard {
  protected _tags = [CardTag.POKEMON_EX];
  public stage: Stage = Stage.BASIC;
  public cardType: CardType[] = [F];
  public hp: number = 180;
  public weakness = [{ type: W }];
  public resistance = [{ type: L, value: -20 }];
  public retreat = [C, C, C];

  public attacks = [
    {
      name: 'Dig Out',
      cost: [C, C],
      damage: 40,
      text: 'Discard the top card of your deck. If that card is a basic Energy card, attach it to 1 of your Pokémon.',
    },
    {
      name: 'Break Ground',
      cost: [F, F, C, C],
      damage: 120,
      text: "Does 10 damage to each of your Benched Pokémon. (Don't apply Weakness and Resistance for Benched Pokémon.)",
    },
  ];

  public set: string = 'LTR';
  public setNumber: string = '82';
  public cardImage: string = 'assets/cardback.png';
  public name: string = 'Excadrill-EX';
  public fullName: string = 'Excadrill-EX LTR';

  public reduceEffect(store: StoreLike, state: State, effect: Effect): State {
    // Attack 1: Dig Out
    // Ref: set-lost-thunder/magcargo-gx.ts (Crushing Charge)
    if (WAS_ATTACK_USED(effect, 0, this)) {
      const player = effect.player;

      if (player.deck.cards.length === 0) {
        return state;
      }

      const topOfDeck = new CardList();
      MOVE_CARDS(store, state, player.deck, topOfDeck, { count: 1, sourceCard: this });

      const discardedEnergy = topOfDeck.cards.filter((card) => {
        return (
          card.superType === SuperType.ENERGY &&
          (card as EnergyCard).energyType === EnergyType.BASIC
        );
      });

      if (discardedEnergy.length === 0) {
        MOVE_CARDS(store, state, topOfDeck, player.discard, { sourceCard: this });
      } else {
        store.prompt(
          state,
          new AttachEnergyPrompt(
            player.id,
            GameMessage.ATTACH_ENERGY_TO_BENCH,
            topOfDeck,
            PlayerType.BOTTOM_PLAYER,
            [SlotType.ACTIVE, SlotType.BENCH],
            { superType: SuperType.ENERGY, energyType: EnergyType.BASIC },
            { allowCancel: false, min: 1, max: 1 },
          ),
          (transfers) => {
            transfers = transfers || [];
            for (const transfer of transfers) {
              const target = StateUtils.getTarget(state, player, transfer.to);
              MOVE_CARDS(store, state, topOfDeck, target, { cards: [transfer.card], sourceCard: this });
            }
            MOVE_CARDS(store, state, topOfDeck, player.discard, { sourceCard: this });
          },
        );
      }
    }

    // Attack 2: Break Ground
    // Ref: set-boundaries-crossed/sandslash.ts (Earthquake)
    if (WAS_ATTACK_USED(effect, 1, this)) {
      const player = effect.player;

      player.forEachPokemon(PlayerType.BOTTOM_PLAYER, (cardList) => {
        if (cardList === player.active) {
          return;
        }
        const damage = new PutDamageEffect(effect, 10);
        damage.target = cardList;
        store.reduceEffect(state, damage);
      });
    }

    return state;
  }
}
