// This file was auto-generated by the card stub generator.
// Card effects were implemented by an agent.
// If you have any questions or feedback, reach out to @C4 in the discord.

import { PokemonCard } from '../../../game/store/card/pokemon-card';
import { Stage, CardType } from '../../../game/store/card/card-types';
import { StoreLike, State, StateUtils } from '../../../game';
import { Effect } from '../../../game/store/effects/effect';
import {WAS_ATTACK_USED, MOVE_CARDS } from '../../../game/store/prefabs/prefabs';

export class Crawdaunt extends PokemonCard {
  public stage: Stage = Stage.STAGE_1;
  public evolvesFrom: string = 'Corphish';
  public cardType: CardType[] = [W];
  public hp: number = 130;
  public weakness = [{ type: L }];
  public retreat = [C, C, C];

  public attacks = [
    {
      name: 'Knock Off',
      cost: [W, C, C],
      damage: 60,
      text: 'Discard a random card from your opponent\'s hand.'
    },
    {
      name: 'Crabhammer',
      cost: [W, W, C, C],
      damage: 140,
      text: ''
    }
  ];

  public regulationMark: string = 'E';
  public set: string = 'BST';
  public setNumber: string = '39';
  public cardImage: string = 'assets/cardback.png';
  public name: string = 'Crawdaunt';
  public fullName: string = 'Crawdaunt BST';

  public reduceEffect(store: StoreLike, state: State, effect: Effect): State {
    // Attack 1: Knock Off
    // Ref: AGENTS-patterns.md (Discard a random card from opponent's hand - Math.random() allowed)
    if (WAS_ATTACK_USED(effect, 0, this)) {
      const player = effect.player;
      const opponent = StateUtils.getOpponent(state, player);

      if (opponent.hand.cards.length > 0) {
        const randomIndex = Math.floor(Math.random() * opponent.hand.cards.length);
        const randomCard = opponent.hand.cards[randomIndex];
        MOVE_CARDS(store, state, opponent.hand, opponent.discard, { cards: [randomCard], sourceCard: this });
      }
    }

    return state;
  }
}
