// This file was auto-generated by the card stub generator.
// Card effects were implemented by an agent.
// If you have any questions or feedback, reach out to @C4 in the discord.

import { PokemonCard } from '../../../game/store/card/pokemon-card';
import { Stage, CardType, SuperType, TrainerType } from '../../../game/store/card/card-types';
import { StoreLike, State, GameMessage } from '../../../game';
import { Effect } from '../../../game/store/effects/effect';
import {WAS_ATTACK_USED, SHUFFLE_DECK, MOVE_CARDS } from '../../../game/store/prefabs/prefabs';
import { ChooseCardsPrompt } from '../../../game/store/prompts/choose-cards-prompt';

export class GalarianMrMime extends PokemonCard {
  public stage: Stage = Stage.BASIC;
  public cardType: CardType[] = [W];
  public hp: number = 80;
  public weakness = [{ type: M }];
  public retreat = [C];

  public attacks = [
    {
      name: 'Pound',
      cost: [W],
      damage: 10,
      text: ''
    },
    {
      name: 'Find It',
      cost: [C, C],
      damage: 0,
      text: 'Search your deck for an Item card, reveal it, and put it into your hand. Then, shuffle your deck.'
    }
  ];

  public regulationMark: string = 'E';
  public set: string = 'BST';
  public setNumber: string = '34';
  public cardImage: string = 'assets/cardback.png';
  public name: string = 'Galarian Mr. Mime';
  public fullName: string = 'Galarian Mr. Mime BST';

  public reduceEffect(store: StoreLike, state: State, effect: Effect): State {
    // Attack 2: Find It
    // Ref: set-shining-fates/ball-guy.ts (search deck for Item card with name filter)
    if (WAS_ATTACK_USED(effect, 1, this)) {
      const player = effect.player;

      return store.prompt(state, new ChooseCardsPrompt(
        player,
        GameMessage.CHOOSE_CARD_TO_HAND,
        player.deck,
        { superType: SuperType.TRAINER, trainerType: TrainerType.ITEM },
        { min: 0, max: 1, allowCancel: false }
      ), selected => {
        const cards = selected || [];
        if (cards.length > 0) {
          MOVE_CARDS(store, state, player.deck, player.hand, { cards: cards, sourceCard: this });
        }
        return SHUFFLE_DECK(store, state, player);
      });
    }

    return state;
  }
}
