// This file was auto-generated by the card stub generator.
// Card effects were implemented by an agent.
// If you have any questions or feedback, reach out to @C4 in the discord.

import { PokemonCard } from '../../../game/store/card/pokemon-card';
import { Stage, CardType } from '../../../game/store/card/card-types';
import { StoreLike, State, StateUtils } from '../../../game';
import { Effect } from '../../../game/store/effects/effect';
import {WAS_ATTACK_USED, MOVE_CARDS } from '../../../game/store/prefabs/prefabs';

export class Bunnelby extends PokemonCard {
  public stage: Stage = Stage.BASIC;
  public cardType: CardType[] = [C];
  public hp: number = 70;
  public weakness = [{ type: F }];
  public retreat = [C];

  public attacks = [
    {
      name: 'Burrow',
      cost: [C],
      damage: 0,
      text: 'Discard the top card of your opponent\'s deck.'
    },
    {
      name: 'Headbutt Bounce',
      cost: [C, C, C],
      damage: 50,
      text: ''
    }
  ];

  public regulationMark: string = 'D';
  public set: string = 'RCL';
  public setNumber: string = '146';
  public cardImage: string = 'assets/cardback.png';
  public name: string = 'Bunnelby';
  public fullName: string = 'Bunnelby RCL';

  public reduceEffect(store: StoreLike, state: State, effect: Effect): State {
    // Attack 1: Burrow
    // Ref: set-steam-siege/ambipom.ts (Furry Chance - discard top card of opponent's deck)
    if (WAS_ATTACK_USED(effect, 0, this)) {
      const player = effect.player;
      const opponent = StateUtils.getOpponent(state, player);

      if (opponent.deck.cards.length > 0) {
        const topCard = opponent.deck.cards[0];
        MOVE_CARDS(store, state, opponent.deck, opponent.discard, { cards: [topCard], sourceCard: this });
      }
    }

    return state;
  }
}
