// This file was auto-generated by the card stub generator.
// Card effects were implemented by an agent.
// If you have any questions or feedback, reach out to @C4 in the discord.

import { PokemonCard } from '../../../game/store/card/pokemon-card';
import { Stage, CardType, EnergyType, SuperType } from '../../../game/store/card/card-types';
import { GameMessage, PlayerType, SlotType, StoreLike, State, StateUtils } from '../../../game';
import { EnergyCard } from '../../../game/store/card/energy-card';
import { Effect } from '../../../game/store/effects/effect';
import {WAS_ATTACK_USED, MOVE_CARDS } from '../../../game/store/prefabs/prefabs';
import { AttachEnergyPrompt } from '../../../game/store/prompts/attach-energy-prompt';

export class Charjabug extends PokemonCard {
  public stage: Stage = Stage.STAGE_1;
  public evolvesFrom: string = 'Grubbin';
  public cardType: CardType[] = [L];
  public hp: number = 90;
  public weakness = [{ type: F }];
  public retreat = [C, C];

  public attacks = [
    {
      name: 'Charge',
      cost: [C],
      damage: 0,
      text: 'Search your deck for up to 2 [L] Energy cards and attach them to this Pokémon. Then, shuffle your deck.'
    },
    {
      name: 'Lightning Ball',
      cost: [L, L, C],
      damage: 70,
      text: ''
    }
  ];

  public regulationMark: string = 'D';
  public set: string = 'RCL';
  public setNumber: string = '65';
  public cardImage: string = 'assets/cardback.png';
  public name: string = 'Charjabug';
  public fullName: string = 'Charjabug RCL';

  public reduceEffect(store: StoreLike, state: State, effect: Effect): State {
    // Attack 1: Charge
    // Ref: set-roaring-skies/dragonite-2.ts (Wrapped in Wind - attach energy from deck to self)
    if (WAS_ATTACK_USED(effect, 0, this)) {
      const player = effect.player;

      const hasLightningEnergyInDeck = player.deck.cards.some(c =>
        c instanceof EnergyCard && c.energyType === EnergyType.BASIC && c.provides.includes(CardType.LIGHTNING)
      );

      if (!hasLightningEnergyInDeck) {
        return state;
      }

      return store.prompt(state, new AttachEnergyPrompt(
        player.id,
        GameMessage.ATTACH_ENERGY_CARDS,
        player.deck,
        PlayerType.BOTTOM_PLAYER,
        [SlotType.ACTIVE],
        { superType: SuperType.ENERGY, energyType: EnergyType.BASIC, name: 'Lightning Energy' },
        { min: 0, max: 2, allowCancel: false }
      ), transfers => {
        transfers = transfers || [];
        for (const transfer of transfers) {
          const target = StateUtils.getTarget(state, player, transfer.to);
          MOVE_CARDS(store, state, player.deck, target, { cards: [transfer.card], sourceCard: this });
        }
      });
    }

    return state;
  }
}
