// This file was auto-generated by the card stub generator.
// Card effects were implemented by an agent.
// If you have any questions or feedback, reach out to @C4 in the discord.

import { PokemonCard } from '../../../game/store/card/pokemon-card';
import { Stage, CardType, CardTag } from '../../../game/store/card/card-types';
import {
  Card,
  ChooseCardsPrompt,
  GameMessage,
  ShowCardsPrompt,
  StoreLike,
  State,
  StateUtils,
} from '../../../game';
import { Effect } from '../../../game/store/effects/effect';
import {WAS_ATTACK_USED, MOVE_CARDS } from '../../../game/store/prefabs/prefabs';

export class MalamarVmax extends PokemonCard {
  protected _tags = [CardTag.POKEMON_VMAX];
  public stage: Stage = Stage.VMAX;
  public evolvesFrom: string = 'Malamar V';
  public cardType: CardType[] = [D];
  public hp: number = 310;
  public weakness = [{ type: G }];
  public retreat = [C, C];

  public attacks = [
    {
      name: 'Max Jammer',
      cost: [D, D, C],
      damage: 180,
      text: 'Your opponent reveals their hand. Choose a card you find there and put it on the bottom of their deck.',
    },
  ];

  public regulationMark: string = 'D';
  public set: string = 'RCL';
  public setNumber: string = '122';
  public cardImage: string = 'assets/cardback.png';
  public name: string = 'Malamar VMAX';
  public fullName: string = 'Malamar VMAX RCL';

  public reduceEffect(store: StoreLike, state: State, effect: Effect): State {
    // Attack 1: Max Jammer
    // Ref: set-next-destinies/beheeyem.ts (Brain Control - reveal hand, choose card, put on bottom of deck)
    if (WAS_ATTACK_USED(effect, 0, this)) {
      const player = effect.player;
      const opponent = StateUtils.getOpponent(state, player);

      if (opponent.hand.cards.length === 0) {
        return state;
      }

      return store.prompt(
        state,
        new ShowCardsPrompt(
          player.id,
          GameMessage.CARDS_SHOWED_BY_THE_OPPONENT,
          opponent.hand.cards,
        ),
        () => {
          return store.prompt(
            state,
            new ChooseCardsPrompt(
              player,
              GameMessage.CHOOSE_CARD_TO_DECK,
              opponent.hand,
              {},
              { min: 1, max: 1, allowCancel: false },
            ),
            (selected: Card[]) => {
              if (selected && selected.length > 0) {
                // Move to deck first, then reposition to bottom
                MOVE_CARDS(store, state, opponent.hand, opponent.deck, { cards: selected, sourceCard: this });
                const card = selected[0];
                const index = opponent.deck.cards.indexOf(card);
                if (index > -1) {
                  opponent.deck.cards.splice(index, 1);
                  opponent.deck.cards.push(card); // bottom of deck
                }
              }
            },
          );
        },
      );
    }

    return state;
  }
}
