// This file was auto-generated by the card stub generator.
// Card effects were implemented by an agent.
// If you have any questions or feedback, reach out to @C4 in the discord.

import { TrainerCard } from '../../../game/store/card/trainer-card';
import { CardTag, CardType, TrainerType } from '../../../game/store/card/card-types';
import { PowerType } from '../../../game/store/card/pokemon-types';
import { StoreLike, State, StateUtils } from '../../../game';
import { Effect } from '../../../game/store/effects/effect';
import { DealDamageEffect } from '../../../game/store/effects/attack-effects';
import { CheckPokemonTypeEffect } from '../../../game/store/effects/check-effects';
import { IS_TOOL_BLOCKED } from '../../../game/store/prefabs/prefabs';
import { PokemonCard } from '../../../game/store/card/pokemon-card';

export class FairyCharmAbility extends TrainerCard {
  protected _trainerType: TrainerType = TrainerType.TOOL;
  public set: string = 'UNB';
  public setNumber: string = '171';
  public cardImage: string = 'assets/cardback.png';
  public name: string = 'Fairy Charm Ability';
  public fullName: string = 'Fairy Charm Ability UNB';
  public text: string =
    "Prevent all damage done to the Fairy Pokémon this card is attached to by attacks from your opponent's Pokémon-GX and Pokémon-EX that have Abilities.";

  // Ref: set-lost-thunder/fairy-charm-psychic.ts (Fairy Charm tool damage prevention pattern)
  public reduceEffect(store: StoreLike, state: State, effect: Effect): State {
    if (effect instanceof DealDamageEffect && effect.target.tools.includes(this)) {
      const player = StateUtils.findOwner(state, effect.target);

      if (IS_TOOL_BLOCKED(store, state, player, this)) {
        return state;
      }

      // Check if attached Pokemon is Fairy type
      const checkTargetType = new CheckPokemonTypeEffect(effect.target);
      store.reduceEffect(state, checkTargetType);
      if (!checkTargetType.cardTypes.includes(CardType.FAIRY)) {
        return state;
      }

      // Check if attacking Pokemon is GX or EX with an Ability
      const sourceCard = effect.source.getPokemonCard();
      if (
        sourceCard &&
        (sourceCard.hasTag(CardTag.POKEMON_GX) || sourceCard.hasTag(CardTag.POKEMON_EX))
      ) {
        // Check if the attacking Pokemon has an Ability
        if (
          sourceCard instanceof PokemonCard &&
          sourceCard.powers.some((p) => p.powerType === PowerType.ABILITY)
        ) {
          effect.damage = 0;
        }
      }
    }

    return state;
  }
}
