// This file was auto-generated by the card stub generator.
// Card effects were implemented by an agent.
// If you have any questions or feedback, reach out to @C4 in the discord.

import { PokemonCard } from '../../../game/store/card/pokemon-card';
import { Stage, CardType } from '../../../game/store/card/card-types';
import { StoreLike, State } from '../../../game';
import { Effect } from '../../../game/store/effects/effect';
import { WAS_ATTACK_USED, DRAW_CARDS, ADD_SLEEP_TO_PLAYER_ACTIVE } from '../../../game/store/prefabs/prefabs';
import { DEFENDING_POKEMON_WEAKNESS_IS_NOW } from '../../../game/store/prefabs/effect-of-attack-prefabs';

export class Meowstic extends PokemonCard {
  public stage: Stage = Stage.STAGE_1;
  public evolvesFrom: string = 'Espurr';
  public cardType: CardType[] = [P];
  public hp: number = 90;
  public weakness = [{ type: P }];
  public retreat = [C];

  public attacks = [
    {
      name: 'Caturday',
      cost: [C],
      damage: 0,
      text: 'Draw 3 cards. If you do, this Pokémon is now Asleep.'
    },
    {
      name: 'Perplexing Eyes',
      cost: [P, C, C],
      damage: 70,
      text: 'The Defending Pokémon\'s Weakness is now Psychic until the end of your next turn. (The amount of Weakness doesn\'t change.)'
    }
  ];

  public set: string = 'UNB';
  public setNumber: string = '80';
  public cardImage: string = 'assets/cardback.png';
  public name: string = 'Meowstic';
  public fullName: string = 'Meowstic UNB';

  public reduceEffect(store: StoreLike, state: State, effect: Effect): State {
    // Attack 1: Caturday
    // Ref: set-lost-thunder/virizion-gx.ts (Double Draw) + AGENTS-patterns.md (self-sleep)
    if (WAS_ATTACK_USED(effect, 0, this)) {
      const player = effect.player;
      DRAW_CARDS(store, state, player, 3);
      ADD_SLEEP_TO_PLAYER_ACTIVE(store, state, player, this);
    }

    if (WAS_ATTACK_USED(effect, 1, this)) {
      return DEFENDING_POKEMON_WEAKNESS_IS_NOW(store, state, effect, this, CardType.PSYCHIC);
    }

    return state;
  }
}
