// This file was auto-generated by the card stub generator.
// Card effects were implemented by an agent.
// If you have any questions or feedback, reach out to @C4 in the discord.

import { PokemonCard } from '../../../game/store/card/pokemon-card';
import { Stage, CardType } from '../../../game/store/card/card-types';
import { StoreLike, State, StateUtils } from '../../../game';
import { Effect } from '../../../game/store/effects/effect';
import {WAS_ATTACK_USED, MOVE_CARDS } from '../../../game/store/prefabs/prefabs';

export class Purugly extends PokemonCard {
  public stage: Stage = Stage.STAGE_1;
  public evolvesFrom: string = 'Glameow';
  public cardType: CardType[] = [C];
  public hp: number = 120;
  public weakness = [{ type: F }];
  public retreat = [C, C, C];

  public attacks = [
    {
      name: 'Stray Cat Dash',
      cost: [C, C],
      damage: 30,
      text: 'Discard a random card from your opponent\'s hand. If this Pokémon evolved from Glameow during this turn, discard 2 cards instead of 1.'
    },
    {
      name: 'Lunge Out',
      cost: [C, C, C],
      damage: 80,
      text: ''
    }
  ];

  public set: string = 'UNB';
  public setNumber: string = '160';
  public cardImage: string = 'assets/cardback.png';
  public name: string = 'Purugly';
  public fullName: string = 'Purugly UNB';

  public reduceEffect(store: StoreLike, state: State, effect: Effect): State {
    // Attack 1: Stray Cat Dash
    // Ref: set-ultra-prism/mars.ts (Mars - discard random card from opponent's hand)
    if (WAS_ATTACK_USED(effect, 0, this)) {
      const player = effect.player;
      const opponent = StateUtils.getOpponent(state, player);

      if (opponent.hand.cards.length === 0) {
        return state;
      }

      // Check if evolved from Glameow this turn
      const evolvedThisTurn = player.active.pokemonPlayedTurn === state.turn;
      const discardCount = evolvedThisTurn ? 2 : 1;
      const actualDiscard = Math.min(discardCount, opponent.hand.cards.length);

      for (let i = 0; i < actualDiscard; i++) {
        if (opponent.hand.cards.length > 0) {
          const randomIndex = Math.floor(Math.random() * opponent.hand.cards.length);
          const randomCard = opponent.hand.cards[randomIndex];
          MOVE_CARDS(store, state, opponent.hand, opponent.discard, { cards: [randomCard], sourceCard: this });
        }
      }
    }

    return state;
  }
}
