// This file was auto-generated by the card stub generator.
// Card effects were implemented by an agent.
// If you have any questions or feedback, reach out to @C4 in the discord.

import { PokemonCard } from '../../../game/store/card/pokemon-card';
import { Stage, CardType, EnergyType } from '../../../game/store/card/card-types';
import { PowerType, StoreLike, State, StateUtils, PokemonCardList, GameMessage, ConfirmPrompt, CardList } from '../../../game';
import { EnergyCard } from '../../../game/store/card/energy-card';
import { Effect } from '../../../game/store/effects/effect';
import { CheckProvidedEnergyEffect } from '../../../game/store/effects/check-effects';
import {WAS_ATTACK_USED, IS_ABILITY_BLOCKED, JUST_EVOLVED, SHUFFLE_DECK, MOVE_CARDS } from '../../../game/store/prefabs/prefabs';

export class Sharpedo extends PokemonCard {
  public stage: Stage = Stage.STAGE_1;
  public evolvesFrom: string = 'Carvanha';
  public cardType: CardType[] = [D];
  public hp: number = 110;
  public weakness = [{ type: F }];
  public resistance = [{ type: P, value: -20 }];
  public retreat = [C];

  public powers = [{
    name: 'Greedy Evolution',
    powerType: PowerType.ABILITY,
    text: 'When you play this Pokémon from your hand to evolve 1 of your Pokémon during your turn, you may look at the top 6 cards of your deck and attach any number of [D] Energy cards you find there to this Pokémon. Shuffle the other cards back into your deck.'
  }];

  public attacks = [
    {
      name: 'Bad Fangs',
      cost: [C, C, C],
      damage: 60,
      damageCalculation: '+',
      text: 'This attack does 20 more damage times the amount of [D] Energy attached to this Pokémon.'
    }
  ];

  public set: string = 'UNB';
  public setNumber: string = '111';
  public cardImage: string = 'assets/cardback.png';
  public name: string = 'Sharpedo';
  public fullName: string = 'Sharpedo UNB';

  public reduceEffect(store: StoreLike, state: State, effect: Effect): State {
    // Ability: Greedy Evolution (on-evolve - attach D energy from top 6 cards)
    // Ref: set-team-up/lycanroc-gx.ts (Twilight Eyes - JUST_EVOLVED + ConfirmPrompt pattern)
    if (JUST_EVOLVED(effect, this)) {
      const player = effect.player;

      if (IS_ABILITY_BLOCKED(store, state, player, this)) {
        return state;
      }

      if (player.deck.cards.length === 0) {
        return state;
      }

      store.prompt(state, new ConfirmPrompt(
        player.id,
        GameMessage.WANT_TO_USE_ABILITY,
      ), wantToUse => {
        if (wantToUse) {
          const topCards = new CardList();
          const count = Math.min(6, player.deck.cards.length);
          MOVE_CARDS(store, state, player.deck, topCards, { count: count, sourceCard: this });

          // Find D energy cards
          const darkEnergy = topCards.cards.filter(c =>
            c instanceof EnergyCard && c.energyType === EnergyType.BASIC && c.provides.includes(CardType.DARK)
          );

          // Attach all D energy to this Pokemon
          const cardList = StateUtils.findCardList(state, this) as PokemonCardList;
          darkEnergy.forEach(card => {
            MOVE_CARDS(store, state, topCards, cardList, { cards: [card], sourceCard: this });
          });

          // Shuffle remaining cards back
          MOVE_CARDS(store, state, topCards, player.deck, { sourceCard: this });
          SHUFFLE_DECK(store, state, player);
        }
      });

      return state;
    }

    // Attack 1: Bad Fangs
    // Ref: set-x-and-y/yveltal-ex.ts (Evil Ball - energy counting for damage)
    if (WAS_ATTACK_USED(effect, 0, this)) {
      const player = effect.player;

      const checkEnergy = new CheckProvidedEnergyEffect(player, player.active);
      store.reduceEffect(state, checkEnergy);

      let darkEnergyCount = 0;
      checkEnergy.energyMap.forEach(em => {
        darkEnergyCount += em.provides.filter(t => t === CardType.DARK || t === CardType.ANY).length;
      });

      effect.damage += 20 * darkEnergyCount;
    }

    return state;
  }
}
