// This file was auto-generated by the card stub generator.
// Card effects were implemented by an agent.
// If you have any questions or feedback, reach out to @C4 in the discord.

import { PokemonCard } from '../../../game/store/card/pokemon-card';
import { Stage, CardType } from '../../../game/store/card/card-types';
import { Card, GameMessage, StoreLike, State } from '../../../game';
import { Effect } from '../../../game/store/effects/effect';
import { ChooseCardsPrompt } from '../../../game/store/prompts/choose-cards-prompt';
import {WAS_ATTACK_USED, SHUFFLE_DECK, MOVE_CARDS } from '../../../game/store/prefabs/prefabs';

export class Litwick extends PokemonCard {
  public stage: Stage = Stage.BASIC;
  public cardType: CardType[] = [P];
  public hp: number = 50;
  public weakness = [{ type: D }];
  public resistance = [{ type: F, value: -20 }];
  public retreat = [C];

  public attacks = [
    {
      name: 'Slightly Simmer',
      cost: [C],
      damage: 0,
      text: 'Search your deck for up to 2 cards and discard them. Shuffle your deck afterward.'
    }
  ];

  public set: string = 'STS';
  public setNumber: string = '48';
  public cardImage: string = 'assets/cardback.png';
  public name: string = 'Litwick';
  public fullName: string = 'Litwick STS';

  public reduceEffect(store: StoreLike, state: State, effect: Effect): State {
    // Attack 1: Slightly Simmer
    // Ref: set-phantom-forces/battle-compressor-team-flare-gear.ts (search deck discard)
    if (WAS_ATTACK_USED(effect, 0, this)) {
      const player = effect.player;

      if (player.deck.cards.length === 0) {
        return state;
      }

      store.prompt(state, new ChooseCardsPrompt(
        player,
        GameMessage.CHOOSE_CARD_TO_DISCARD,
        player.deck,
        {},
        { min: 0, max: 2, allowCancel: true }
      ), (selected: Card[]) => {
        const cards = selected || [];
        if (cards.length > 0) {
          MOVE_CARDS(store, state, player.deck, player.discard, { cards: cards, sourceCard: this });
        }
        SHUFFLE_DECK(store, state, player);
      });
    }

    return state;
  }
}
