// This file was auto-generated by the card stub generator.
// Card effects were implemented by an agent.
// If you have any questions or feedback, reach out to @C4 in the discord.

import { PokemonCard } from '../../../game/store/card/pokemon-card';
import { Stage, CardType, CardTag } from '../../../game/store/card/card-types';
import {
  StoreLike,
  State,
  PlayerType,
  ChoosePokemonPrompt,
  GameMessage,
  SlotType,
} from '../../../game';
import { Effect } from '../../../game/store/effects/effect';
import { MOVE_POKEMON_OFF_BOARD, WAS_ATTACK_USED } from '../../../game/store/prefabs/prefabs';
import { MEGA_EVOLUTION_END_TURN } from '../../../game/store/prefabs/tool-prefabs';

export class MGardevoirEx extends PokemonCard {
  protected _tags = [CardTag.MEGA, CardTag.POKEMON_EX];
  public stage: Stage = Stage.MEGA;
  public evolvesFrom: string = 'Gardevoir-EX';
  public cardType: CardType[] = [Y, P];
  public hp: number = 210;
  public weakness = [{ type: M }];
  public resistance = [{ type: D, value: -20 }];
  public retreat = [C, C];

  public attacks = [
    {
      name: 'Despair Ray',
      cost: [Y, C],
      damage: 110,
      damageCalculation: '+',
      text: 'Discard as many of your Benched Pok\u00e9mon as you like. This attack does 10 more damage for each Benched Pok\u00e9mon you discarded in this way.',
    },
  ];

  public set: string = 'STS';
  public setNumber: string = '79';
  public cardImage: string = 'assets/cardback.png';
  public name: string = 'M Gardevoir-EX';
  public fullName: string = 'M Gardevoir-EX STS';

  public reduceEffect(store: StoreLike, state: State, effect: Effect): State {
    // Mega Evolution Rule: end turn when evolving (unless Spirit Link attached)
    MEGA_EVOLUTION_END_TURN(store, state, effect, this);

    // Despair Ray
    if (WAS_ATTACK_USED(effect, 0, this)) {
      const player = effect.player;

      // Player has more Pokemons than bench size, discard some
      const count = player.bench.length;
      store.prompt(
        state,
        new ChoosePokemonPrompt(
          player.id,
          GameMessage.CHOOSE_POKEMON_TO_DISCARD,
          PlayerType.BOTTOM_PLAYER,
          [SlotType.BENCH],
          { min: 0, max: count, allowCancel: false },
        ),
        (results) => {
          results = results || [];

          let discardCount = 0;

          // Discard all selected Pokemon
          for (let i = player.bench.length - 1; i >= 0; i--) {
            if (results.includes(player.bench[i])) {
              MOVE_POKEMON_OFF_BOARD(store, state, player.bench[i], {
                pokemonDestination: player.discard,
                sourceCard: this,
              });
              discardCount++;
            }
          }

          effect.damage += 10 * discardCount;
        },
      );
    }

    return state;
  }
}
