// This file was auto-generated by the card stub generator.
// Card effects were implemented by an agent.
// If you have any questions or feedback, reach out to @C4 in the discord.

import { PokemonCard } from '../../../game/store/card/pokemon-card';
import { Stage, CardType } from '../../../game/store/card/card-types';
import { Card, GameMessage, StoreLike, State } from '../../../game';
import { Effect } from '../../../game/store/effects/effect';
import { HealEffect } from '../../../game/store/effects/game-effects';
import { ChooseCardsPrompt } from '../../../game/store/prompts/choose-cards-prompt';
import {WAS_ATTACK_USED, MOVE_CARDS } from '../../../game/store/prefabs/prefabs';

export class Mantine extends PokemonCard {
  public stage: Stage = Stage.BASIC;
  public cardType: CardType[] = [W];
  public hp: number = 100;
  public weakness = [{ type: L }];
  public resistance = [{ type: F, value: -20 }];
  public retreat = [C];

  public attacks = [
    {
      name: 'Healing Wave',
      cost: [W],
      damage: 0,
      text: 'Discard as many cards as you like from your hand. Heal 10 damage from this Pokémon for each card you discarded in this way.'
    },
    {
      name: 'Dwindling Wave',
      cost: [W, W, W],
      damage: 90,
      damageCalculation: '-',
      text: 'This attack does 90 damage minus 10 damage for each damage counter on this Pokémon.'
    }
  ];

  public set: string = 'STS';
  public setNumber: string = '27';
  public cardImage: string = 'assets/cardback.png';
  public name: string = 'Mantine';
  public fullName: string = 'Mantine STS';

  public reduceEffect(store: StoreLike, state: State, effect: Effect): State {
    // Attack 1: Healing Wave
    // Ref: set-fates-collide/umbreon-ex.ts (Veil of Darkness - discard from hand)
    if (WAS_ATTACK_USED(effect, 0, this)) {
      const player = effect.player;

      if (player.hand.cards.length > 0) {
        store.prompt(state, new ChooseCardsPrompt(
          player,
          GameMessage.CHOOSE_CARD_TO_DISCARD,
          player.hand,
          {},
          { allowCancel: true, min: 0, max: player.hand.cards.length }
        ), (selected: Card[]) => {
          const cards = selected || [];
          if (cards.length > 0) {
            MOVE_CARDS(store, state, player.hand, player.discard, { cards: cards, sourceCard: this });
            const healEffect = new HealEffect(player, player.active, 10 * cards.length);
            store.reduceEffect(state, healEffect);
          }
        });
      }
    }

    // Attack 2: Dwindling Wave
    // Ref: set-plasma-storm/beartic.ts (Powerful Rage - damage counters on self)
    if (WAS_ATTACK_USED(effect, 1, this)) {
      const player = effect.player;
      const damageCounters = player.active.damage / 10;
      effect.damage = Math.max(0, 90 - 10 * damageCounters);
    }

    return state;
  }
}
