// This file was auto-generated by the card stub generator.
// Card effects were implemented by an agent.
// If you have any questions or feedback, reach out to @C4 in the discord.

import { PokemonCard } from '../../../game/store/card/pokemon-card';
import { Stage, CardType, SuperType } from '../../../game/store/card/card-types';
import { GameError, GameMessage, PlayerType, StoreLike, State, StateUtils } from '../../../game';
import { ChoosePokemonPrompt } from '../../../game/store/prompts/choose-pokemon-prompt';
import { ChooseCardsPrompt } from '../../../game/store/prompts/choose-cards-prompt';
import { SlotType } from '../../../game/store/actions/play-card-action';
import { Effect } from '../../../game/store/effects/effect';
import {WAS_ATTACK_USED, MOVE_CARDS } from '../../../game/store/prefabs/prefabs';

export class Meowth extends PokemonCard {
  public stage: Stage = Stage.BASIC;
  public cardType: CardType[] = [C];
  public hp: number = 60;
  public weakness = [{ type: F }];
  public retreat = [C];

  public attacks = [
    {
      name: 'Stall',
      cost: [C],
      damage: 0,
      text: 'You can use this attack only if you go second, and only on your first turn. Discard an Energy attached to 1 of your opponent\'s Pokémon.'
    },
    {
      name: 'Scratch',
      cost: [C, C],
      damage: 20,
      text: ''
    }
  ];

  public set: string = 'STS';
  public setNumber: string = '88';
  public cardImage: string = 'assets/cardback.png';
  public name: string = 'Meowth';
  public fullName: string = 'Meowth STS';

  public reduceEffect(store: StoreLike, state: State, effect: Effect): State {
    // Attack 1: Stall
    // Ref: set-unbroken-bonds/volcanion.ts (Flare Starter - turn check)
    if (WAS_ATTACK_USED(effect, 0, this)) {
      const player = effect.player;
      const opponent = StateUtils.getOpponent(state, player);

      // Can only be used if you go second, on your first turn (turn 2)
      if (state.turn !== 2) {
        throw new GameError(GameMessage.CANNOT_USE_ATTACK);
      }

      // Choose one of opponent's Pokemon
      return store.prompt(state, new ChoosePokemonPrompt(
        player.id,
        GameMessage.CHOOSE_POKEMON,
        PlayerType.TOP_PLAYER,
        [SlotType.ACTIVE, SlotType.BENCH],
        { min: 1, max: 1, allowCancel: false }
      ), targets => {
        if (!targets || targets.length === 0) { return; }
        const target = targets[0];
        const energyCards = target.cards.filter(c => c.superType === SuperType.ENERGY);
        if (energyCards.length === 0) { return; }

        store.prompt(state, new ChooseCardsPrompt(
          player,
          GameMessage.CHOOSE_CARD_TO_DISCARD,
          target,
          { superType: SuperType.ENERGY },
          { min: 1, max: 1, allowCancel: false }
        ), selected => {
          if (selected && selected.length > 0) {
            MOVE_CARDS(store, state, target, opponent.discard, { cards: [selected[0]], sourceCard: this });
          }
        });
      });
    }

    return state;
  }
}
