// This file was auto-generated by the card stub generator.
// Card effects were implemented by an agent.
// If you have any questions or feedback, reach out to @C4 in the discord.

import { PokemonCard } from '../../../game/store/card/pokemon-card';
import { Stage, CardType, SuperType, EnergyType } from '../../../game/store/card/card-types';
import { GameMessage, StoreLike, State } from '../../../game';
import { EnergyCard } from '../../../game/store/card/energy-card';
import { Effect } from '../../../game/store/effects/effect';
import {WAS_ATTACK_USED, MOVE_CARDS } from '../../../game/store/prefabs/prefabs';
import { ChooseCardsPrompt } from '../../../game/store/prompts/choose-cards-prompt';

export class Ponyta extends PokemonCard {
  public stage: Stage = Stage.BASIC;
  public cardType: CardType[] = [R];
  public hp: number = 60;
  public weakness = [{ type: W }];
  public retreat = [C];

  public attacks = [
    {
      name: 'Returning Flames',
      cost: [C],
      damage: 0,
      text: 'Put 2 [R] Energy cards from your discard pile into your hand.'
    },
    {
      name: 'Live Coal',
      cost: [R],
      damage: 10,
      text: ''
    }
  ];

  public set: string = 'STS';
  public setNumber: string = '16';
  public cardImage: string = 'assets/cardback.png';
  public name: string = 'Ponyta';
  public fullName: string = 'Ponyta STS';

  public reduceEffect(store: StoreLike, state: State, effect: Effect): State {
    // Attack 1: Returning Flames
    // Ref: set-breakthrough/simisage.ts (Fire Fling)
    if (WAS_ATTACK_USED(effect, 0, this)) {
      const player = effect.player;

      const blocked: number[] = [];
      player.discard.cards.forEach((card, index) => {
        if (!(card instanceof EnergyCard && card.energyType === EnergyType.BASIC && card.provides.includes(CardType.FIRE))) {
          blocked.push(index);
        }
      });

      const available = player.discard.cards.length - blocked.length;
      if (available > 0) {
        const count = Math.min(2, available);
        store.prompt(state, new ChooseCardsPrompt(
          player,
          GameMessage.CHOOSE_CARD_TO_HAND,
          player.discard,
          { superType: SuperType.ENERGY },
          { min: count, max: count, allowCancel: false, blocked }
        ), selected => {
          if (selected && selected.length > 0) {
            MOVE_CARDS(store, state, player.discard, player.hand, { cards: selected, sourceCard: this });
          }
        });
      }
    }

    return state;
  }
}
