// This file was auto-generated by the card stub generator.
// Card effects were implemented by an agent.
// If you have any questions or feedback, reach out to @C4 in the discord.

import { PokemonCard } from '../../../game/store/card/pokemon-card';
import { Stage, CardType, CardTag } from '../../../game/store/card/card-types';
import { StoreLike, State, EnergyCard } from '../../../game';
import { Effect } from '../../../game/store/effects/effect';
import {BREAK_RULE, WAS_ATTACK_USED, MOVE_CARDS } from '../../../game/store/prefabs/prefabs';

export class TalonflameBreak extends PokemonCard {
  protected _tags = [CardTag.BREAK];
  public stage: Stage = Stage.BREAK;
  public evolvesFrom: string = 'Talonflame';
  public cardType: CardType[] = [R];
  public hp: number = 170;
  public retreat = [];

  public attacks = [
    {
      name: 'Flare Blitz',
      cost: [R, R],
      damage: 150,
      text: 'Discard all [R] Energy attached to this Pokémon.',
    },
  ];

  public set: string = 'STS';
  public setNumber: string = '21';
  public cardImage: string = 'assets/cardback.png';
  public name: string = 'Talonflame BREAK';
  public fullName: string = 'Talonflame BREAK STS';

  public reduceEffect(store: StoreLike, state: State, effect: Effect): State {
    // Attack 1: Flare Blitz
    // Ref: set-x-and-y/talonflame.ts (discard all [R] Energy pattern)
    if (WAS_ATTACK_USED(effect, 0, this)) {
      const player = effect.player;
      const cards = player.active.cards.filter(
        (c) => c instanceof EnergyCard && c.provides.includes(CardType.FIRE),
      );
      cards.forEach((c) => {
        MOVE_CARDS(store, state, player.active, player.discard, { cards: [c], sourceCard: this });
      });
    }

    BREAK_RULE(effect, state, this);

    return state;
  }
}
