// This file was auto-generated by the card stub generator.
// Card effects were implemented by an agent.
// If you have any questions or feedback, reach out to @C4 in the discord.

import { PokemonCard } from '../../../game/store/card/pokemon-card';
import {
  Stage,
  CardType,
  CardTag,
  SuperType,
  TrainerType,
} from '../../../game/store/card/card-types';
import {
  Card,
  GameMessage,
  PlayerType,
  StoreLike,
  State,
  StateUtils,
} from '../../../game';
import { CheckPokemonTypeEffect } from '../../../game/store/effects/check-effects';
import { Effect } from '../../../game/store/effects/effect';
import { ChooseCardsPrompt } from '../../../game/store/prompts/choose-cards-prompt';
import { ShowCardsPrompt } from '../../../game/store/prompts/show-cards-prompt';
import {WAS_ATTACK_USED, SHUFFLE_DECK, MOVE_CARDS } from '../../../game/store/prefabs/prefabs';

export class FlorgesEx extends PokemonCard {
  protected _tags = [CardTag.POKEMON_EX];
  public stage: Stage = Stage.BASIC;
  public cardType: CardType[] = [Y];
  public hp: number = 160;
  public weakness = [{ type: M }];
  public resistance = [{ type: D, value: -20 }];
  public retreat = [C, C];

  public attacks = [
    {
      name: 'Lead',
      cost: [Y],
      damage: 0,
      text: 'Search your deck for a Supporter card, reveal it, and put it into your hand. Shuffle your deck afterward.',
    },
    {
      name: 'Bright Garden',
      cost: [Y, C],
      damage: 20,
      damageCalculation: 'x',
      text: 'This attack does 20 damage times the number of Grass Pokémon and Fairy Pokémon you have in play.',
    },
  ];

  public set: string = 'PHF';
  public setNumber: string = '67';
  public cardImage: string = 'assets/cardback.png';
  public name: string = 'Florges-EX';
  public fullName: string = 'Florges-EX PHF';

  public reduceEffect(store: StoreLike, state: State, effect: Effect): State {
    // Attack 1: Lead
    // Ref: set-x-and-y/gogoat.ts (Lead - search for Supporter)
    if (WAS_ATTACK_USED(effect, 0, this)) {
      const player = effect.player;
      const opponent = StateUtils.getOpponent(state, player);

      if (player.deck.cards.length === 0) {
        return state;
      }

      state = store.prompt(
        state,
        new ChooseCardsPrompt(
          player,
          GameMessage.CHOOSE_CARD_TO_HAND,
          player.deck,
          { superType: SuperType.TRAINER, trainerType: TrainerType.SUPPORTER },
          { min: 0, max: 1, allowCancel: true },
        ),
        (selected: Card[]) => {
          const cards = selected || [];

          if (cards.length > 0) {

            store.prompt(
              state,
              new ShowCardsPrompt(opponent.id, GameMessage.CARDS_SHOWED_BY_THE_OPPONENT, cards),
              () => {
                cards.forEach((card) => {
                  MOVE_CARDS(store, state, player.deck, player.hand, { cards: [card], sourceCard: this });
                });
              },
            );
          }

          SHUFFLE_DECK(store, state, player);
        },
      );
    }

    // Attack 2: Bright Garden
    // Ref: set-flashfire/shiftry.ts (Deranged Dance - Pokemon count pattern)
    if (WAS_ATTACK_USED(effect, 1, this)) {
      const player = effect.player;
      let count = 0;

      player.forEachPokemon(PlayerType.BOTTOM_PLAYER, (cardList) => {
        const checkType = new CheckPokemonTypeEffect(cardList);
        store.reduceEffect(state, checkType);

        if (
          checkType.cardTypes.includes(CardType.GRASS) ||
          checkType.cardTypes.includes(CardType.FAIRY)
        ) {
          count++;
        }
      });

      effect.damage = 20 * count;
    }

    return state;
  }
}
