// This file was auto-generated by the card stub generator.
// Card effects were implemented by an agent.
// If you have any questions or feedback, reach out to @C4 in the discord.

import { TrainerCard } from '../../../game/store/card/trainer-card';
import { TrainerType } from '../../../game/store/card/card-types';
import { StoreLike, State, StateUtils } from '../../../game';
import { Effect } from '../../../game/store/effects/effect';
import {
  AbstractAttackEffect,
  ApplyWeaknessEffect,
  DealDamageEffect,
  PutDamageEffect,
} from '../../../game/store/effects/attack-effects';
import { IS_TOOL_BLOCKED } from '../../../game/store/prefabs/prefabs';

export class BentSpoon extends TrainerCard {
  protected _trainerType: TrainerType = TrainerType.TOOL;
  public set: string = 'FCO';
  public setNumber: string = '93';
  public cardImage: string = 'assets/cardback.png';
  public name: string = 'Bent Spoon';
  public fullName: string = 'Bent Spoon FCO';
  public text: string =
    "Prevent all effects of your opponent's attacks, except damage, done to the Pokémon this card is attached to. (Existing effects are not removed.)";

  // Ref: set-steam-siege/magearna-ex.ts (Mystic Heart - prevent attack effects except damage)
  public reduceEffect(store: StoreLike, state: State, effect: Effect): State {
    if (effect instanceof AbstractAttackEffect) {
      // Check if the target has this tool attached
      if (!effect.target.tools.includes(this)) {
        return state;
      }

      const owner = StateUtils.findOwner(state, effect.target);

      if (IS_TOOL_BLOCKED(store, state, owner, this)) {
        return state;
      }

      // Only block effects from opponent's attacks
      if (effect.player === owner) {
        return state;
      }

      // Allow Weakness & Resistance
      if (effect instanceof ApplyWeaknessEffect) {
        return state;
      }
      // Allow damage
      if (effect instanceof PutDamageEffect) {
        return state;
      }
      // Allow damage
      if (effect instanceof DealDamageEffect) {
        return state;
      }

      effect.preventDefault = true;
    }

    return state;
  }
}
