// This file was auto-generated by the card stub generator.
// Card effects were implemented by an agent.
// If you have any questions or feedback, reach out to @C4 in the discord.

import { PokemonCard } from '../../../game/store/card/pokemon-card';
import { Stage, CardType, CardTag } from '../../../game/store/card/card-types';
import { StoreLike, State, StateUtils } from '../../../game';
import { Effect } from '../../../game/store/effects/effect';
import { WAS_ATTACK_USED } from '../../../game/store/prefabs/prefabs';
import { PREVENT_DAMAGE } from '../../../game/store/prefabs/effect-of-attack-prefabs';

export class GlaceonEx extends PokemonCard {
  protected _tags = [CardTag.POKEMON_EX];
  public stage: Stage = Stage.BASIC;
  public cardType: CardType[] = [W];
  public hp: number = 170;
  public weakness = [{ type: M }];
  public retreat = [C, C];

  public attacks = [
    {
      name: 'Second Bite',
      cost: [W, C],
      damage: 20,
      damageCalculation: '+',
      text: "This attack does 10 more damage for each damage counter on your opponent's Active Pokémon.",
    },
    {
      name: 'Crystal Ray',
      cost: [W, C, C],
      damage: 70,
      text: "During your opponent's next turn, prevent all damage done to this Pokémon by attacks from Evolution Pokémon.",
    },
  ];

  public set: string = 'FCO';
  public setNumber: string = '20';
  public cardImage: string = 'assets/cardback.png';
  public name: string = 'Glaceon-EX';
  public fullName: string = 'Glaceon-EX FCO';

  public reduceEffect(store: StoreLike, state: State, effect: Effect): State {
    // Attack 1: Second Bite
    // Ref: set-breakthrough/m-mewtwo-ex-2.ts (damage counter based damage)
    if (WAS_ATTACK_USED(effect, 0, this)) {
      const opponent = StateUtils.getOpponent(state, effect.player);
      const damageCounters = Math.floor(opponent.active.damage / 10);
      effect.damage += 10 * damageCounters;
    }

    if (WAS_ATTACK_USED(effect, 1, this)) {
      PREVENT_DAMAGE(store, state, effect, this, { sourceIsEvolution: true });
    }

    return state;
  }
}
