// This file was auto-generated by the card stub generator.
// Card effects were implemented by an agent.
// If you have any questions or feedback, reach out to @C4 in the discord.

import { PokemonCard } from '../../../game/store/card/pokemon-card';
import { Stage, CardType, BoardEffect } from '../../../game/store/card/card-types';
import { PowerType, StoreLike, State, StateUtils, GameMessage, ConfirmPrompt, PlayerType } from '../../../game';
import { Effect } from '../../../game/store/effects/effect';
import { EvolveEffect } from '../../../game/store/effects/game-effects';
import {IS_ABILITY_BLOCKED, MOVE_CARDS } from '../../../game/store/prefabs/prefabs';

export class Chandelure extends PokemonCard {
  public stage: Stage = Stage.STAGE_2;
  public evolvesFrom: string = 'Lampent';
  public cardType: CardType[] = [R];
  public hp: number = 150;
  public weakness = [{ type: W }];
  public retreat = [C, C];

  public powers = [{
    name: 'Mountain Roasting',
    powerType: PowerType.ABILITY,
    text: 'When you play this Pokémon from your hand to evolve 1 of your Pokémon during your turn, you may discard the top 3 cards of your opponent\'s deck.'
  }];

  public attacks = [
    {
      name: 'Heat Blast',
      cost: [R, C],
      damage: 90,
      text: ''
    }
  ];

  public regulationMark: string = 'F';
  public set: string = 'LOR';
  public setNumber: string = '26';
  public cardImage: string = 'assets/cardback.png';
  public name: string = 'Chandelure';
  public fullName: string = 'Chandelure LOR 26';

  public reduceEffect(store: StoreLike, state: State, effect: Effect): State {
    // Ability: Mountain Roasting - on-evolve, may discard top 3 cards of opponent's deck
    // Ref: set-astral-radiance/togekiss.ts (Shine of Happiness - EvolveEffect on-evolve ability pattern)
    // Ref: set-lost-origin/stonjourner.ts (opponent.deck.moveTo pattern)
    if (effect instanceof EvolveEffect && effect.pokemonCard === this) {
      const player = effect.player;

      if (IS_ABILITY_BLOCKED(store, state, player, this)) {
        return state;
      }

      const opponent = StateUtils.getOpponent(state, player);
      if (opponent.deck.cards.length === 0) {
        return state;
      }

      state = store.prompt(state, new ConfirmPrompt(
        player.id,
        GameMessage.WANT_TO_USE_ABILITY,
      ), wantToUse => {
        if (wantToUse) {
          player.forEachPokemon(PlayerType.BOTTOM_PLAYER, cardList => {
            if (cardList.getPokemonCard() === this) {
              cardList.addBoardEffect(BoardEffect.ABILITY_USED);
            }
          });

          const discardCount = Math.min(3, opponent.deck.cards.length);
          MOVE_CARDS(store, state, opponent.deck, opponent.discard, { count: discardCount, sourceCard: this });
        }
      });
    }

    return state;
  }
}
