// This file was auto-generated by the card stub generator.
// Card effects were implemented by an agent.
// If you have any questions or feedback, reach out to @C4 in the discord.

import { TrainerCard } from '../../../game/store/card/trainer-card';
import { TrainerType } from '../../../game/store/card/card-types';
import { StoreLike, State, GameError, GameMessage } from '../../../game';
import { Effect } from '../../../game/store/effects/effect';
import { WAS_TRAINER_USED } from '../../../game/store/prefabs/trainer-prefabs';
import { DRAW_CARDS, MOVE_CARDS } from '../../../game/store/prefabs/prefabs';

export class Iscan extends TrainerCard {
  protected _trainerType: TrainerType = TrainerType.SUPPORTER;
  public regulationMark: string = 'F';
  public set: string = 'LOR';
  public setNumber: string = '158';
  public cardImage: string = 'assets/cardback.png';
  public name: string = 'Iscan';
  public fullName: string = 'Iscan LOR 158';
  public text: string =
    'Draw 2 cards. If your Active Pokémon has "Hisuian" in its name, draw 2 more cards. You may play only 1 Supporter card during your turn.';

  public reduceEffect(store: StoreLike, state: State, effect: Effect): State {
    // Ref: set-astral-radiance/barry.ts (DRAW_CARDS Supporter), set-astral-radiance/choy.ts (WAS_TRAINER_USED),
    //      set-astral-radiance/colress-experiment.ts (supporter structure)
    if (WAS_TRAINER_USED(effect, this)) {
      const player = effect.player;

      if (player.supporterTurn > 0) {
        throw new GameError(GameMessage.SUPPORTER_ALREADY_PLAYED);
      }

      MOVE_CARDS(store, state, player.hand, player.supporter, { cards: [effect.trainerCard], sourceCard: this });

      // Draw 2 cards
      DRAW_CARDS(store, state, player, 2);

      // If active Pokemon has "Hisuian" in its name, draw 2 more
      const activePokemon = player.active.getPokemonCard();
      if (activePokemon && activePokemon.name.includes('Hisuian')) {
        DRAW_CARDS(store, state, player, 2);
      }

    }

    return state;
  }
}
