// This file was auto-generated by the card stub generator.
// Card effects were implemented by an agent.
// If you have any questions or feedback, reach out to @C4 in the discord.

import { PokemonCard } from '../../../game/store/card/pokemon-card';
import { Stage, CardType, SuperType } from '../../../game/store/card/card-types';
import { StoreLike, State, StateUtils, PlayerType, SlotType, GameMessage, AttachEnergyPrompt } from '../../../game';
import { CheckProvidedEnergyEffect } from '../../../game/store/effects/check-effects';
import { Effect } from '../../../game/store/effects/effect';
import {WAS_ATTACK_USED, MOVE_CARDS } from '../../../game/store/prefabs/prefabs';

export class Lunala extends PokemonCard {
  public stage: Stage = Stage.STAGE_2;
  public evolvesFrom: string = 'Cosmoem';
  public cardType: CardType[] = [P];
  public hp: number = 160;
  public weakness = [{ type: D }];
  public resistance = [{ type: F, value: -20 }];
  public retreat = [C, C];

  public attacks = [
    {
      name: 'Shatter Shot',
      cost: [P],
      damage: 40,
      damageCalculation: 'x',
      text: 'This attack does 40 damage times the amount of [P] Energy attached to this Pokémon.'
    },
    {
      name: 'Wings of the Moone',
      cost: [P, P, P],
      damage: 130,
      text: 'Move all Energy from this Pokémon to your Benched Pokémon in any way you like.'
    }
  ];

  public set: string = 'GRI';
  public setNumber: string = '61';
  public cardImage: string = 'assets/cardback.png';
  public name: string = 'Lunala';
  public fullName: string = 'Lunala GRI';

  public reduceEffect(store: StoreLike, state: State, effect: Effect): State {
    // Attack 1: Shatter Shot
    // Ref: set-sun-and-moon/gumshoos-gx.ts (Gumshoe Chance-GX - energy count)
    if (WAS_ATTACK_USED(effect, 0, this)) {
      const player = effect.player;

      const checkEnergy = new CheckProvidedEnergyEffect(player, player.active);
      store.reduceEffect(state, checkEnergy);

      let psychicCount = 0;
      checkEnergy.energyMap.forEach(em => {
        psychicCount += em.provides.filter(p => p === CardType.PSYCHIC || p === CardType.ANY).length;
      });

      effect.damage = 40 * psychicCount;
    }

    // Attack 2: Wings of the Moone
    // Ref: set-noble-victories/victini-2.ts (Stored Power)
    if (WAS_ATTACK_USED(effect, 1, this)) {
      const player = effect.player;
      const hasBench = player.bench.some(b => b.cards.length > 0);

      if (!hasBench) {
        return state;
      }

      const attachedEnergies = player.active.cards.filter(card =>
        card.superType === SuperType.ENERGY
      );

      if (attachedEnergies.length === 0) {
        return state;
      }

      return store.prompt(state, new AttachEnergyPrompt(
        player.id,
        GameMessage.ATTACH_ENERGY_TO_BENCH,
        player.active,
        PlayerType.BOTTOM_PLAYER,
        [SlotType.BENCH],
        { superType: SuperType.ENERGY },
        { allowCancel: false, min: attachedEnergies.length, max: attachedEnergies.length }
      ), transfers => {
        transfers = transfers || [];
        for (const transfer of transfers) {
          const target = StateUtils.getTarget(state, player, transfer.to);
          MOVE_CARDS(store, state, player.active, target, { cards: [transfer.card], sourceCard: this });
        }
      });
    }

    return state;
  }
}
