// This file was auto-generated by the card stub generator.
// Card effects were implemented by an agent.
// If you have any questions or feedback, reach out to @C4 in the discord.

import { TrainerCard } from '../../../game/store/card/trainer-card';
import { TrainerType, SuperType, CardTag } from '../../../game/store/card/card-types';
import { StoreLike, State, GameError, GameMessage, ChooseCardsPrompt } from '../../../game';
import { Effect } from '../../../game/store/effects/effect';
import { TrainerEffect } from '../../../game/store/effects/play-card-effects';
import { MOVE_CARDS } from '../../../game/store/prefabs/prefabs';

function* playCard(
  next: Function,
  store: StoreLike,
  state: State,
  effect: TrainerEffect,
): IterableIterator<State> {
  const player = effect.player;
  const name = effect.trainerCard.name;

  // Must have another Crossceiver in hand besides this one
  const second = player.hand.cards.find((c) => {
    return c.name === name && c !== effect.trainerCard;
  });
  if (second === undefined) {
    throw new GameError(GameMessage.CANNOT_PLAY_THIS_CARD);
  }

  // Check if discard has any Pokemon or Supporter cards
  const hasTarget = player.discard.cards.some((c) => {
    if (c.superType === SuperType.POKEMON) {
      return true;
    }
    if (c instanceof TrainerCard && c.trainerType === TrainerType.SUPPORTER) {
      return true;
    }
    return false;
  });

  if (!hasTarget) {
    throw new GameError(GameMessage.CANNOT_PLAY_THIS_CARD);
  }

  effect.preventDefault = true;
  MOVE_CARDS(store, state, player.hand, player.supporter, { cards: [effect.trainerCard], sourceCard: effect.trainerCard });

  // Block all cards that aren't Pokemon or Supporter
  const blocked: number[] = [];
  player.discard.cards.forEach((card, index) => {
    const isPokemon = card.superType === SuperType.POKEMON;
    const isSupporter = card instanceof TrainerCard && card.trainerType === TrainerType.SUPPORTER;
    if (!isPokemon && !isSupporter) {
      blocked.push(index);
    }
  });

  let selected: any[] = [];
  yield store.prompt(
    state,
    new ChooseCardsPrompt(
      player,
      GameMessage.CHOOSE_CARD_TO_HAND,
      player.discard,
      {},
      { min: 1, max: 1, allowCancel: false, blocked },
    ),
    (cards) => {
      selected = cards || [];
      next();
    },
  );

  selected.forEach((card) => {
    MOVE_CARDS(store, state, player.discard, player.hand, { cards: [card], sourceCard: effect.trainerCard });
  });

  // Discard both Crossceivers
  if (second !== undefined) {
    MOVE_CARDS(store, state, player.hand, player.discard, { cards: [second], sourceCard: effect.trainerCard });
  }
}

export class Crossceiver extends TrainerCard {
  protected _trainerType: TrainerType = TrainerType.ITEM;
  protected _tags = [CardTag.FUSION_STRIKE];
  public regulationMark: string = 'E';
  public set: string = 'FST';
  public setNumber: string = '231';
  public cardImage: string = 'assets/cardback.png';
  public name: string = 'Crossceiver';
  public fullName: string = 'Crossceiver FST 231';
  public text: string =
    'You must play 2 Crossceiver cards at once. (This effect works one time for 2 cards.) Put a Pokémon or a Supporter card from your discard pile into your hand. You may play any number of Item cards during your turn.';

  public reduceEffect(store: StoreLike, state: State, effect: Effect): State {
    // Ref: set-fusion-strike/cross-switcher.ts (two-at-once pattern), set-phantom-forces/vs-seeker.ts (discard search)
    if (effect instanceof TrainerEffect && effect.trainerCard === this) {
      const generator = playCard(() => generator.next(), store, state, effect);
      return generator.next().value;
    }

    return state;
  }
}
