// This file was auto-generated by the card stub generator.
// Card effects were implemented by an agent.
// If you have any questions or feedback, reach out to @C4 in the discord.

import { PokemonCard } from '../../../game/store/card/pokemon-card';
import { Stage, CardType } from '../../../game/store/card/card-types';
import { PowerType, StoreLike, State } from '../../../game';
import { Effect } from '../../../game/store/effects/effect';
import { ADAPTIVE_EVOLUTION } from '../../../game/store/prefabs/prefabs';

export class Caterpie extends PokemonCard {
  public stage: Stage = Stage.BASIC;
  public cardType: CardType[] = [G];
  public hp: number = 40;
  public weakness = [{ type: R }];
  public retreat = [C];

  public powers = [{
    name: 'Adaptive Evolution',
    useWhenInPlay: true,
    powerType: PowerType.ABILITY,
    text: 'This Pokémon can evolve during your first turn or the turn you play it.'
  }];

  public attacks = [
    {
      name: 'Bug Bite',
      cost: [G],
      damage: 10,
      text: ''
    }
  ];

  public set: string = 'FLF';
  public setNumber: string = '1';
  public cardImage: string = 'assets/cardback.png';
  public name: string = 'Caterpie';
  public fullName: string = 'Caterpie FLF';

  public reduceEffect(store: StoreLike, state: State, effect: Effect): State {
    return ADAPTIVE_EVOLUTION(store, state, effect, this);
  }
}
