// This file was auto-generated by the card stub generator.
// Card effects were implemented by an agent.
// If you have any questions or feedback, reach out to @C4 in the discord.

import { PokemonCard } from '../../../game/store/card/pokemon-card';
import { Stage, CardType, SuperType } from '../../../game/store/card/card-types';
import { PowerType, StoreLike, State, GameMessage, GameError, Card, ChooseCardsPrompt, PokemonCardList } from '../../../game';
import { Effect } from '../../../game/store/effects/effect';
import { HealEffect } from '../../../game/store/effects/game-effects';
import {WAS_ATTACK_USED, WAS_POWER_USED, IS_ABILITY_BLOCKED, ABILITY_USED, MOVE_CARDS } from '../../../game/store/prefabs/prefabs';
import { FLIP_A_COIN_IF_HEADS_DEAL_MORE_DAMAGE } from '../../../game/store/prefabs/attack-effects';
import { StateUtils } from '../../../game/store/state-utils';

export class Goodra extends PokemonCard {
  public stage: Stage = Stage.STAGE_2;
  public evolvesFrom: string = 'Sliggoo';
  public cardType: CardType[] = [N];
  public hp: number = 150;
  public weakness = [{ type: Y }];
  public retreat = [C, C, C];

  public powers = [{
    name: 'Gooey Regeneration',
    useWhenInPlay: true,
    powerType: PowerType.ABILITY,
    text: 'As often as you like during your turn (before your attack), you may discard an Energy attached to this Pok\u00e9mon. If you do, heal 60 damage from this Pok\u00e9mon.'
  }];

  public attacks = [
    {
      name: 'Heavy Whip',
      cost: [W, Y, C],
      damage: 80,
      damageCalculation: '+',
      text: 'Flip a coin. If heads, this attack does 40 more damage.'
    }
  ];

  public set: string = 'FLF';
  public setNumber: string = '74';
  public cardImage: string = 'assets/cardback.png';
  public name: string = 'Goodra';
  public fullName: string = 'Goodra FLF';

  public reduceEffect(store: StoreLike, state: State, effect: Effect): State {
    // Refs: set-dragons-majesty/feraligatr.ts (as-often-as-you-like discard energy), set-x-and-y/starmie.ts (discard energy + heal)
    if (WAS_POWER_USED(effect, 0, this)) {
      const player = effect.player;

      if (IS_ABILITY_BLOCKED(store, state, player, this)) {
        throw new GameError(GameMessage.BLOCKED_BY_EFFECT);
      }

      // Find the card list containing this Pokemon
      const cardList = StateUtils.findCardList(state, this) as PokemonCardList;

      // Check if there's any energy attached
      const hasEnergy = cardList.cards.some(c => c.superType === SuperType.ENERGY);
      if (!hasEnergy) {
        throw new GameError(GameMessage.CANNOT_USE_POWER);
      }

      // Check if there is damage to heal
      if (cardList.damage === 0) {
        throw new GameError(GameMessage.CANNOT_USE_POWER);
      }

      ABILITY_USED(player, this);

      store.prompt(state, new ChooseCardsPrompt(
        player,
        GameMessage.CHOOSE_CARD_TO_DISCARD,
        cardList,
        { superType: SuperType.ENERGY },
        { min: 1, max: 1, allowCancel: false }
      ), (selected: Card[]) => {
        const cards = selected || [];
        if (cards.length > 0) {
          MOVE_CARDS(store, state, cardList, player.discard, { cards: cards, sourceCard: this });

          const healEffect = new HealEffect(player, cardList, 60);
          store.reduceEffect(state, healEffect);
        }
      });
    }

    // Ref: set-x-and-y/timburr.ts (Pummel)
    if (WAS_ATTACK_USED(effect, 0, this)) {
      FLIP_A_COIN_IF_HEADS_DEAL_MORE_DAMAGE(store, state, effect, 40);
    }

    return state;
  }
}
