// This file was auto-generated by the card stub generator.
// Card effects were implemented by an agent.
// If you have any questions or feedback, reach out to @C4 in the discord.

import { PokemonCard } from '../../../game/store/card/pokemon-card';
import { Stage, CardType } from '../../../game/store/card/card-types';
import { StoreLike, State, CardList, GameMessage, OrderCardsPrompt } from '../../../game';
import { Effect } from '../../../game/store/effects/effect';
import {WAS_ATTACK_USED, MOVE_CARDS } from '../../../game/store/prefabs/prefabs';

export class AlolanDiglett extends PokemonCard {
  public stage: Stage = Stage.BASIC;
  public cardType: CardType[] = [M];
  public hp: number = 50;
  public weakness = [{ type: R }];
  public resistance = [{ type: P, value: -20 }];
  public retreat = [C];

  public attacks = [
    {
      name: 'Spelunk',
      cost: [],
      damage: 0,
      text: 'Look at the top 3 cards of your deck and put them back in any order.'
    },
    {
      name: 'Mud-Slap',
      cost: [M],
      damage: 10,
      text: ''
    }
  ];

  public set: string = 'SUM';
  public setNumber: string = '86';
  public cardImage: string = 'assets/cardback.png';
  public name: string = 'Alolan Diglett';
  public fullName: string = 'Alolan Diglett SUM';

  public reduceEffect(store: StoreLike, state: State, effect: Effect): State {
    // Attack 1: Spelunk
    // Ref: set-x-and-y/braixen.ts (Clairvoyant Eye - look at top 3 and reorder)
    if (WAS_ATTACK_USED(effect, 0, this)) {
      const player = effect.player;

      if (player.deck.cards.length === 0) {
        return state;
      }

      const deckTop = new CardList();
      MOVE_CARDS(store, state, player.deck, deckTop, { count: Math.min(3, player.deck.cards.length), sourceCard: this });

      return store.prompt(state, new OrderCardsPrompt(
        player.id,
        GameMessage.CHOOSE_CARDS_ORDER,
        deckTop,
        { allowCancel: false },
      ), order => {
        if (order === null) {
          return state;
        }

        deckTop.applyOrder(order);
        deckTop.moveToTopOfDestination(player.deck);
      });
    }

    return state;
  }
}
