// This file was auto-generated by the card stub generator.
// Card effects were implemented by an agent.
// If you have any questions or feedback, reach out to @C4 in the discord.

import { TrainerCard } from '../../../game/store/card/trainer-card';
import { TrainerType, SpecialCondition } from '../../../game/store/card/card-types';
import { StoreLike, State, GameMessage, SelectPrompt } from '../../../game';
import { Effect } from '../../../game/store/effects/effect';
import { TrainerEffect } from '../../../game/store/effects/play-card-effects';
import { HealEffect } from '../../../game/store/effects/game-effects';

export class BigMalasada extends TrainerCard {
  protected _trainerType: TrainerType = TrainerType.ITEM;
  public set: string = 'SUM';
  public setNumber: string = '114';
  public cardImage: string = 'assets/cardback.png';
  public name: string = 'Big Malasada';
  public fullName: string = 'Big Malasada SUM';
  public text: string = 'Heal 20 damage and remove a Special Condition from your Active Pokémon.';

  public reduceEffect(store: StoreLike, state: State, effect: Effect): State {
    // Ref: set-sun-and-moon/tsareena.ts (Trop Kick - heal + remove special conditions)
    if (effect instanceof TrainerEffect && effect.trainerCard === this) {
      const player = effect.player;

      // Heal 20 damage from active
      const healEffect = new HealEffect(player, player.active, 20);
      store.reduceEffect(state, healEffect);

      // Remove a Special Condition
      const specialConditions = player.active.specialConditions;
      if (specialConditions.length === 1) {
        player.active.specialConditions = [];
      } else if (specialConditions.length > 1) {
        // Player chooses which condition to remove
        const options: string[] = specialConditions.map((sc) => SpecialCondition[sc]);

        store.prompt(
          state,
          new SelectPrompt(player.id, GameMessage.CHOOSE_SPECIAL_CONDITION, options, {
            allowCancel: false,
          }),
          (choice) => {
            if (choice !== null && choice >= 0 && choice < specialConditions.length) {
              specialConditions.splice(choice, 1);
            }
          },
        );
      }
    }

    return state;
  }
}
