// This file was auto-generated by the card stub generator.
// Card effects were implemented by an agent.
// If you have any questions or feedback, reach out to @C4 in the discord.

import { PokemonCard } from '../../../game/store/card/pokemon-card';
import { Stage, CardType } from '../../../game/store/card/card-types';
import { StoreLike, State, StateUtils } from '../../../game';
import { Effect } from '../../../game/store/effects/effect';
import {WAS_ATTACK_USED, MOVE_CARDS } from '../../../game/store/prefabs/prefabs';

export class Carvanha extends PokemonCard {
  public stage: Stage = Stage.BASIC;
  public cardType: CardType[] = [D];
  public hp: number = 60;
  public weakness = [{ type: F }];
  public resistance = [{ type: P, value: -20 }];
  public retreat = [C];

  public attacks = [
    {
      name: 'Gnaw Through',
      cost: [C],
      damage: 0,
      text: 'Discard all Pokémon Tool cards from your opponent\'s Active Pokémon.'
    },
    {
      name: 'Bite',
      cost: [D, C],
      damage: 20,
      text: ''
    }
  ];

  public set: string = 'SUM';
  public setNumber: string = '81';
  public cardImage: string = 'assets/cardback.png';
  public name: string = 'Carvanha';
  public fullName: string = 'Carvanha SUM';

  public reduceEffect(store: StoreLike, state: State, effect: Effect): State {
    // Attack 1: Gnaw Through
    // Ref: set-x-and-y/skarmory-ex.ts (Joust)
    if (WAS_ATTACK_USED(effect, 0, this)) {
      const player = effect.player;
      const opponent = StateUtils.getOpponent(state, player);

      // Discard all tools from opponent's active
      const tools = opponent.active.tools.slice();
      tools.forEach(tool => {
        MOVE_CARDS(store, state, opponent.active, opponent.discard, { cards: [tool], sourceCard: this });
      });
    }

    return state;
  }
}
