// This file was auto-generated by the card stub generator.
// Card effects were implemented by an agent.
// If you have any questions or feedback, reach out to @C4 in the discord.

import { PokemonCard } from '../../../game/store/card/pokemon-card';
import { Stage, CardType, SuperType } from '../../../game/store/card/card-types';
import { PowerType, PlayerType, GameMessage, StoreLike, State } from '../../../game';
import { Effect } from '../../../game/store/effects/effect';
import { PowerEffect } from '../../../game/store/effects/game-effects';
import { AttachEnergyEffect } from '../../../game/store/effects/play-card-effects';
import { Card } from '../../../game/store/card/card';
import { ChooseCardsPrompt } from '../../../game/store/prompts/choose-cards-prompt';
import {SHUFFLE_DECK, MOVE_CARDS } from '../../../game/store/prefabs/prefabs';

export class Eevee extends PokemonCard {
  public stage: Stage = Stage.BASIC;
  public cardType: CardType[] = [C];
  public hp: number = 50;
  public weakness = [{ type: F }];
  public retreat = [C];

  public powers = [{
    name: 'Energy Evolution',
    powerType: PowerType.ABILITY,
    text: 'When you attach a basic Energy card from your hand to this Pokémon, you may search your deck for a card that evolves from this Pokémon that is the same type as that Energy card and put it onto this Pokémon. (This counts as evolving this Pokémon.) Shuffle your deck afterward.'
  }];

  public attacks = [
    {
      name: 'Gnaw',
      cost: [C, C],
      damage: 10,
      text: ''
    }
  ];

  public set: string = 'FFI';
  public setNumber: string = '80';
  public cardImage: string = 'assets/cardback.png';
  public name: string = 'Eevee';
  public fullName: string = 'Eevee FFI';

  public reduceEffect(store: StoreLike, state: State, effect: Effect): State {
    // Ability: Energy Evolution
    // Ref: set-sun-and-moon/eevee.ts (Energy Evolution)
    if (effect instanceof AttachEnergyEffect && effect.target.cards.includes(this)) {
      const player = effect.player;

      // Check if ability is blocked
      try {
        const powerEffect = new PowerEffect(player, this.powers[0], this);
        store.reduceEffect(state, powerEffect);
      } catch {
        return state;
      }

      // Determine what type the energy provides
      let eeveelutionType = CardType.COLORLESS;
      switch (effect.energyCard.name) {
        case 'Water Energy': eeveelutionType = CardType.WATER; break;
        case 'Fire Energy': eeveelutionType = CardType.FIRE; break;
        case 'Lightning Energy': eeveelutionType = CardType.LIGHTNING; break;
        case 'Grass Energy': eeveelutionType = CardType.GRASS; break;
        case 'Psychic Energy': eeveelutionType = CardType.PSYCHIC; break;
        case 'Darkness Energy': eeveelutionType = CardType.DARK; break;
        case 'Fairy Energy': eeveelutionType = CardType.FAIRY; break;
        default: eeveelutionType = CardType.COLORLESS; break;
      }

      if (eeveelutionType === CardType.COLORLESS) {
        return state;
      }

      if (player.deck.cards.length === 0) {
        return state;
      }

      player.forEachPokemon(PlayerType.BOTTOM_PLAYER, (cardList) => {
        if (cardList.getPokemonCard() === this) {
          let cards: Card[] = [];
          store.prompt(state, new ChooseCardsPrompt(
            player,
            GameMessage.CHOOSE_CARD_TO_EVOLVE,
            player.deck,
            { superType: SuperType.POKEMON, stage: Stage.STAGE_1, evolvesFrom: 'Eevee', cardType: [eeveelutionType] },
            { min: 0, max: 1, allowCancel: true }
          ), selected => {
            cards = selected || [];
            if (cards.length > 0) {
              MOVE_CARDS(store, state, player.deck, cardList, { cards: cards, sourceCard: this });
              cardList.clearEffects();
              cardList.pokemonPlayedTurn = state.turn;
            }
            SHUFFLE_DECK(store, state, player);
          });
        }
      });
    }

    return state;
  }
}
