// This file was auto-generated by the card stub generator.
// Card effects were implemented by an agent.
// If you have any questions or feedback, reach out to @C4 in the discord.

import { PokemonCard } from '../../../game/store/card/pokemon-card';
import { Stage, CardType, SuperType, TrainerType } from '../../../game/store/card/card-types';
import { Card, ChooseCardsPrompt, GameError, GameMessage, PowerType, StoreLike, State, StateUtils } from '../../../game';
import { TrainerCard } from '../../../game/store/card/trainer-card';
import { Effect } from '../../../game/store/effects/effect';
import {WAS_ATTACK_USED, WAS_POWER_USED, USE_ABILITY_ONCE_PER_TURN, ABILITY_USED, REMOVE_MARKER_AT_END_OF_TURN, SHOW_CARDS_TO_PLAYER, DISCARD_A_STADIUM_CARD_IN_PLAY, IS_ABILITY_BLOCKED, MOVE_CARDS } from '../../../game/store/prefabs/prefabs';

export class Gothitelle extends PokemonCard {
  public stage: Stage = Stage.STAGE_2;
  public evolvesFrom: string = 'Gothorita';
  public cardType: CardType[] = [P];
  public hp: number = 130;
  public weakness = [{ type: P }];
  public retreat = [C, C];

  public readonly TELEPORT_ROOM_MARKER = 'GOTHITELLE_FFI_TELEPORT_ROOM_MARKER';

  public powers = [{
    name: 'Teleport Room',
    useWhenInPlay: true,
    powerType: PowerType.ABILITY,
    text: 'Once during your turn (before your attack), you may discard any Stadium card in play. If you do, put a Stadium card with a different name from your discard pile into play.'
  }];

  public attacks = [
    {
      name: 'Psy Report',
      cost: [P, C, C],
      damage: 60,
      text: 'Your opponent reveals his or her hand.'
    }
  ];

  public set: string = 'FFI';
  public setNumber: string = '41';
  public cardImage: string = 'assets/cardback.png';
  public name: string = 'Gothitelle';
  public fullName: string = 'Gothitelle FFI';

  public reduceEffect(store: StoreLike, state: State, effect: Effect): State {
    // Ability: Teleport Room
    // Refs: set-flashfire/luxray.ts (reveal/discard pattern), set-phantom-forces/dimension-valley.ts (stadium handling)
    if (WAS_POWER_USED(effect, 0, this)) {
      const player = effect.player;

      if (IS_ABILITY_BLOCKED(store, state, player, this)) {
        throw new GameError(GameMessage.BLOCKED_BY_EFFECT);
      }

      // Check if there is a stadium in play
      const stadiumCard = StateUtils.getStadiumCard(state);
      if (stadiumCard === undefined) {
        throw new GameError(GameMessage.CANNOT_USE_POWER);
      }

      const stadiumName = stadiumCard.name;

      // Check if there is a different stadium card in discard
      const discardStadiums = player.discard.cards.filter(c =>
        c instanceof TrainerCard && c.trainerType === TrainerType.STADIUM && c.name !== stadiumName
      );

      if (discardStadiums.length === 0) {
        throw new GameError(GameMessage.CANNOT_USE_POWER);
      }

      USE_ABILITY_ONCE_PER_TURN(player, this.TELEPORT_ROOM_MARKER, this);
      ABILITY_USED(player, this);

      // Discard the current stadium
      DISCARD_A_STADIUM_CARD_IN_PLAY(state);

      // Choose a stadium from discard with a different name
      const blocked: number[] = [];
      player.discard.cards.forEach((card, index) => {
        if (!(card instanceof TrainerCard) || card.trainerType !== TrainerType.STADIUM || card.name === stadiumName) {
          blocked.push(index);
        }
      });

      return store.prompt(state, new ChooseCardsPrompt(
        player,
        GameMessage.CHOOSE_CARD_TO_HAND,
        player.discard,
        { superType: SuperType.TRAINER, trainerType: TrainerType.STADIUM },
        { min: 1, max: 1, allowCancel: false, blocked }
      ), (selected: Card[]) => {
        const cards = selected || [];
        if (cards.length > 0) {
          MOVE_CARDS(store, state, player.discard, player.stadium, { cards: [cards[0]], sourceCard: this });
        }
      });
    }

    REMOVE_MARKER_AT_END_OF_TURN(effect, this.TELEPORT_ROOM_MARKER, this);

    // Attack 1: Psy Report
    // Ref: set-flashfire/luxray.ts (Fang Snipe - reveal opponent hand)
    if (WAS_ATTACK_USED(effect, 0, this)) {
      const player = effect.player;
      const opponent = StateUtils.getOpponent(state, player);
      SHOW_CARDS_TO_PLAYER(store, state, player, opponent.hand.cards);
    }

    return state;
  }
}
