// This file was auto-generated by the card stub generator.
// Card effects were implemented by an agent.
// If you have any questions or feedback, reach out to @C4 in the discord.

import { PokemonCard } from '../../../game/store/card/pokemon-card';
import { Stage, CardType, SuperType, EnergyType } from '../../../game/store/card/card-types';
import { Card, ChooseCardsPrompt, GameError, GameMessage, PowerType, StoreLike, State, StateUtils } from '../../../game';
import { Effect } from '../../../game/store/effects/effect';
import {WAS_ATTACK_USED, WAS_POWER_USED, USE_ABILITY_ONCE_PER_TURN, ABILITY_USED, REMOVE_MARKER_AT_END_OF_TURN, IS_ABILITY_BLOCKED, MOVE_CARDS } from '../../../game/store/prefabs/prefabs';
import { HEAL_X_DAMAGE_FROM_THIS_POKEMON } from '../../../game/store/prefabs/attack-effects';
import { ADD_CONFUSION_TO_PLAYER_ACTIVE, ADD_POISON_TO_PLAYER_ACTIVE } from '../../../game/store/prefabs/prefabs';
import { EnergyCard } from '../../../game/store/card/energy-card';

export class Victreebel extends PokemonCard {
  public stage: Stage = Stage.STAGE_2;
  public evolvesFrom: string = 'Weepinbell';
  public cardType: CardType[] = [G];
  public hp: number = 130;
  public weakness = [{ type: R }];
  public retreat = [C, C];

  public readonly WAFTING_SCENT_MARKER = 'VICTREEBEL_FFI_WAFTING_SCENT_MARKER';

  public powers = [{
    name: 'Wafting Scent',
    useWhenInPlay: true,
    powerType: PowerType.ABILITY,
    text: 'Once during your turn (before your attack), you may discard a [G] Energy attached to this Pokémon. If you do, your opponent\'s Active Pokémon is now Confused and Poisoned.'
  }];

  public attacks = [
    {
      name: 'Spiral Drain',
      cost: [G, C, C],
      damage: 60,
      text: 'Heal 30 damage from this Pokémon.'
    }
  ];

  public set: string = 'FFI';
  public setNumber: string = '3';
  public cardImage: string = 'assets/cardback.png';
  public name: string = 'Victreebel';
  public fullName: string = 'Victreebel FFI';

  public reduceEffect(store: StoreLike, state: State, effect: Effect): State {
    // Ability: Wafting Scent
    // Ref: set-plasma-storm/ludicolo.ts (Groovy Dance - discard energy for condition)
    if (WAS_POWER_USED(effect, 0, this)) {
      const player = effect.player;

      if (IS_ABILITY_BLOCKED(store, state, player, this)) {
        throw new GameError(GameMessage.BLOCKED_BY_EFFECT);
      }

      const opponent = StateUtils.getOpponent(state, player);

      // Check for Grass Energy attached to this Pokemon
      const cardList = StateUtils.findCardList(state, this);
      const grassEnergy = cardList.cards.filter(c =>
        c instanceof EnergyCard && c.energyType === EnergyType.BASIC && c.name === 'Grass Energy'
      );

      if (grassEnergy.length === 0) {
        throw new GameError(GameMessage.CANNOT_USE_POWER);
      }

      USE_ABILITY_ONCE_PER_TURN(player, this.WAFTING_SCENT_MARKER, this);
      ABILITY_USED(player, this);

      // Discard a Grass Energy
      if (grassEnergy.length === 1) {
        MOVE_CARDS(store, state, cardList, player.discard, { cards: [grassEnergy[0]], sourceCard: this });
      } else {
        const blocked: number[] = [];
        cardList.cards.forEach((card, index) => {
          if (!(card instanceof EnergyCard) || card.energyType !== EnergyType.BASIC || card.name !== 'Grass Energy') {
            blocked.push(index);
          }
        });

        store.prompt(state, new ChooseCardsPrompt(
          player,
          GameMessage.CHOOSE_CARD_TO_DISCARD,
          cardList,
          { superType: SuperType.ENERGY, energyType: EnergyType.BASIC, name: 'Grass Energy' },
          { min: 1, max: 1, allowCancel: false, blocked }
        ), (selected: Card[]) => {
          const cards = selected || [];
          if (cards.length > 0) {
            MOVE_CARDS(store, state, cardList, player.discard, { cards: [cards[0]], sourceCard: this });
          }
        });
      }

      // Apply Confused and Poisoned to opponent's active
      ADD_CONFUSION_TO_PLAYER_ACTIVE(store, state, opponent, this);
      ADD_POISON_TO_PLAYER_ACTIVE(store, state, opponent, this);
    }

    REMOVE_MARKER_AT_END_OF_TURN(effect, this.WAFTING_SCENT_MARKER, this);

    // Attack 1: Spiral Drain
    // Ref: set-flashfire/goodra.ts (heal damage)
    if (WAS_ATTACK_USED(effect, 0, this)) {
      HEAL_X_DAMAGE_FROM_THIS_POKEMON(30, effect, store, state);
    }

    return state;
  }
}
