// This file was auto-generated by the card stub generator.
// Card effects were implemented by an agent.
// If you have any questions or feedback, reach out to @C4 in the discord.

import { TrainerCard } from '../../../game/store/card/trainer-card';
import { TrainerType, SuperType } from '../../../game/store/card/card-types';
import { StoreLike, State, GameError, GameMessage, PokemonCard } from '../../../game';
import { Effect } from '../../../game/store/effects/effect';
import { TrainerEffect } from '../../../game/store/effects/play-card-effects';
import { ChooseCardsPrompt } from '../../../game/store/prompts/choose-cards-prompt';
import { ShowCardsPrompt } from '../../../game/store/prompts/show-cards-prompt';
import { StateUtils } from '../../../game/store/state-utils';
import { MOVE_CARDS } from '../../../game/store/prefabs/prefabs';

export class AetherFoundationEmployee extends TrainerCard {
  protected _trainerType: TrainerType = TrainerType.SUPPORTER;
  public set: string = 'LOT';
  public setNumber: string = '168';
  public cardImage: string = 'assets/cardback.png';
  public name: string = 'Aether Foundation Employee';
  public fullName: string = 'Aether Foundation Employee LOT';
  public text: string =
    'Put 3 Pok\u00e9mon that have "Alolan" in their names from your discard pile into your hand. You may play only 1 Supporter card during your turn (before your attack).';

  public reduceEffect(store: StoreLike, state: State, effect: Effect): State {
    // Ref: set-paradox-rift/tulip.ts (discard pile card selection with blocked indices)
    if (effect instanceof TrainerEffect && effect.trainerCard === this) {
      const player = effect.player;
      const opponent = StateUtils.getOpponent(state, player);

      const blocked: number[] = [];
      let alolanCount = 0;
      player.discard.cards.forEach((c, index) => {
        if (c instanceof PokemonCard && c.name.includes('Alolan')) {
          alolanCount++;
        } else {
          blocked.push(index);
        }
      });

      if (alolanCount === 0) {
        throw new GameError(GameMessage.CANNOT_PLAY_THIS_CARD);
      }

      const maxCards = Math.min(3, alolanCount);

      store.prompt(
        state,
        new ChooseCardsPrompt(
          player,
          GameMessage.CHOOSE_CARD_TO_HAND,
          player.discard,
          { superType: SuperType.POKEMON },
          { min: 1, max: maxCards, allowCancel: false, blocked },
        ),
        (selected) => {
          const cards = selected || [];
          cards.forEach((c) => {
            MOVE_CARDS(store, state, player.discard, player.hand, { cards: [c], sourceCard: this });
          });

          if (cards.length > 0) {
            store.prompt(
              state,
              new ShowCardsPrompt(opponent.id, GameMessage.CARDS_SHOWED_BY_THE_OPPONENT, cards),
              () => {},
            );
          }
        },
      );
    }

    return state;
  }
}
