// This file was auto-generated by the card stub generator.
// Card effects were implemented by an agent.
// If you have any questions or feedback, reach out to @C4 in the discord.

import { PokemonCard } from '../../../game/store/card/pokemon-card';
import { Stage, CardType, SuperType } from '../../../game/store/card/card-types';
import { StoreLike, State, StateUtils, GameMessage, PlayerType, SlotType, CardList } from '../../../game';
import { Effect } from '../../../game/store/effects/effect';
import {WAS_ATTACK_USED, SHUFFLE_DECK, MOVE_CARDS } from '../../../game/store/prefabs/prefabs';
import { FLIP_A_COIN_IF_HEADS_DEAL_MORE_DAMAGE } from '../../../game/store/prefabs/attack-effects';
import { EnergyCard } from '../../../game/store/card/energy-card';
import { AttachEnergyPrompt } from '../../../game/store/prompts/attach-energy-prompt';

export class Azumarill extends PokemonCard {
  public stage: Stage = Stage.STAGE_1;
  public evolvesFrom: string = 'Marill';
  public cardType: CardType[] = [Y];
  public hp: number = 100;
  public weakness = [{ type: M }];
  public resistance = [{ type: D, value: -20 }];
  public retreat = [C, C];

  public attacks = [
    {
      name: 'Polka-Dot Search',
      cost: [Y],
      damage: 0,
      text: 'Look at the top 8 cards of your deck and attach any number of Energy cards you find there to your Pokémon in any way you like. Shuffle the other cards back into your deck.'
    },
    {
      name: 'Play Rough',
      cost: [Y, C, C],
      damage: 60,
      damageCalculation: '+',
      text: 'Flip a coin. If heads, this attack does 30 more damage.'
    }
  ];

  public set: string = 'LOT';
  public setNumber: string = '136';
  public cardImage: string = 'assets/cardback.png';
  public name: string = 'Azumarill';
  public fullName: string = 'Azumarill LOT';

  public reduceEffect(store: StoreLike, state: State, effect: Effect): State {
    // Attack 1: Polka-Dot Search
    // Ref: set-guardians-rising/brooklet-hill.ts (deck search pattern)
    if (WAS_ATTACK_USED(effect, 0, this)) {
      const player = effect.player;

      const deckTop = new CardList();
      MOVE_CARDS(store, state, player.deck, deckTop, { count: Math.min(8, player.deck.cards.length), sourceCard: this });

      const energyCards = deckTop.cards.filter(c => c instanceof EnergyCard);

      if (energyCards.length > 0) {
        store.prompt(state, new AttachEnergyPrompt(
          player.id,
          GameMessage.ATTACH_ENERGY_CARDS,
          deckTop,
          PlayerType.BOTTOM_PLAYER,
          [SlotType.ACTIVE, SlotType.BENCH],
          { superType: SuperType.ENERGY },
          { allowCancel: false, min: 0 }
        ), transfers => {
          transfers = transfers || [];
          for (const transfer of transfers) {
            const target = StateUtils.getTarget(state, player, transfer.to);
            MOVE_CARDS(store, state, deckTop, target, { cards: [transfer.card], sourceCard: this });
          }
          // Shuffle remaining cards back into deck
          MOVE_CARDS(store, state, deckTop, player.deck, { sourceCard: this });
          SHUFFLE_DECK(store, state, player);
        });
      } else {
        // No energy found, shuffle all back
        MOVE_CARDS(store, state, deckTop, player.deck, { sourceCard: this });
        SHUFFLE_DECK(store, state, player);
      }
    }

    // Attack 2: Play Rough
    // Ref: set-dragons-majesty/magikarp.ts (Play Rough)
    if (WAS_ATTACK_USED(effect, 1, this)) {
      FLIP_A_COIN_IF_HEADS_DEAL_MORE_DAMAGE(store, state, effect, 30);
    }

    return state;
  }
}
