// This file was auto-generated by the card stub generator.
// Card effects were implemented by an agent.
// If you have any questions or feedback, reach out to @C4 in the discord.

import { PokemonCard } from '../../../game/store/card/pokemon-card';
import { Stage, CardType, SuperType, TrainerType } from '../../../game/store/card/card-types';
import { StoreLike, State, StateUtils, GameMessage } from '../../../game';
import { TrainerCard } from '../../../game/store/card/trainer-card';
import { Effect } from '../../../game/store/effects/effect';
import { ChooseCardsPrompt } from '../../../game/store/prompts/choose-cards-prompt';
import { ShowCardsPrompt } from '../../../game/store/prompts/show-cards-prompt';
import {WAS_ATTACK_USED, SHUFFLE_DECK, MOVE_CARDS } from '../../../game/store/prefabs/prefabs';

export class Carbink extends PokemonCard {
  public stage: Stage = Stage.BASIC;
  public cardType: CardType[] = [F];
  public hp: number = 90;
  public weakness = [{ type: G }];
  public retreat = [C];

  public attacks = [
    {
      name: 'Diamond Gate',
      cost: [F],
      damage: 0,
      text: 'Search your deck for a Supporter card and a Stadium card, reveal them, and put them into your hand. Then, shuffle your deck.'
    },
    {
      name: 'Guard Press',
      cost: [F, F, C],
      damage: 60,
      text: 'During your opponent\'s next turn, this Pok\u00e9mon takes 20 less damage from attacks (after applying Weakness and Resistance).'
    }
  ];

  public set: string = 'LOT';
  public setNumber: string = '117';
  public cardImage: string = 'assets/cardback.png';
  public name: string = 'Carbink';
  public fullName: string = 'Carbink LOT';

  public reduceEffect(store: StoreLike, state: State, effect: Effect): State {
    // Attack 1: Diamond Gate
    // Ref: set-celestial-storm/mawile.ts (Mining - search deck for cards)
    if (WAS_ATTACK_USED(effect, 0, this)) {
      const player = effect.player;
      const opponent = StateUtils.getOpponent(state, player);

      // Search for Supporter
      const blockedSupporter: number[] = [];
      player.deck.cards.forEach((c, index) => {
        if (!(c instanceof TrainerCard && c.trainerType === TrainerType.SUPPORTER)) {
          blockedSupporter.push(index);
        }
      });

      store.prompt(state, new ChooseCardsPrompt(
        player,
        GameMessage.CHOOSE_CARD_TO_HAND,
        player.deck,
        { superType: SuperType.TRAINER, trainerType: TrainerType.SUPPORTER } as Partial<TrainerCard>,
        { min: 0, max: 1, allowCancel: true, blocked: blockedSupporter }
      ), supporterCards => {
        const cards1 = supporterCards || [];

        // Search for Stadium
        const blockedStadium: number[] = [];
        player.deck.cards.forEach((c, index) => {
          if (!(c instanceof TrainerCard && c.trainerType === TrainerType.STADIUM)) {
            blockedStadium.push(index);
          }
        });

        store.prompt(state, new ChooseCardsPrompt(
          player,
          GameMessage.CHOOSE_CARD_TO_HAND,
          player.deck,
          { superType: SuperType.TRAINER, trainerType: TrainerType.STADIUM } as Partial<TrainerCard>,
          { min: 0, max: 1, allowCancel: true, blocked: blockedStadium }
        ), stadiumCards => {
          const cards2 = stadiumCards || [];
          const allCards = [...cards1, ...cards2];

          allCards.forEach(c => {
            MOVE_CARDS(store, state, player.deck, player.hand, { cards: [c], sourceCard: this });
          });

          if (allCards.length > 0) {
            store.prompt(state, new ShowCardsPrompt(
              opponent.id,
              GameMessage.CARDS_SHOWED_BY_THE_OPPONENT,
              allCards
            ), () => { });
          }

          SHUFFLE_DECK(store, state, player);
        });
      });
    }

    // Attack 2: Guard Press
    // Ref: set-dragons-majesty/jangmo-o.ts (Rigidify - damage reduction marker pattern)
    if (WAS_ATTACK_USED(effect, 1, this)) {
      effect.player.active.damageReductionNextTurn = 20;
    }

    return state;
  }
}
