// This file was auto-generated by the card stub generator.
// Card effects were implemented by an agent.
// If you have any questions or feedback, reach out to @C4 in the discord.

import { TrainerCard } from '../../../game/store/card/trainer-card';
import { CardTag, CardType, TrainerType } from '../../../game/store/card/card-types';
import { StoreLike, State, StateUtils } from '../../../game';
import { Effect } from '../../../game/store/effects/effect';
import { DealDamageEffect } from '../../../game/store/effects/attack-effects';
import { ToolEffect } from '../../../game/store/effects/play-card-effects';
import { CheckPokemonTypeEffect } from '../../../game/store/effects/check-effects';

export class FairyCharmGrass extends TrainerCard {
  protected _trainerType: TrainerType = TrainerType.TOOL;
  public set: string = 'LOT';
  public setNumber: string = '174';
  public cardImage: string = 'assets/cardback.png';
  public name: string = 'Fairy Charm Grass';
  public fullName: string = 'Fairy Charm Grass LOT';
  public text: string =
    "Prevent all damage done to the Fairy Pok\u00e9mon this card is attached to by attacks from your opponent's Grass Pok\u00e9mon-GX and Grass Pok\u00e9mon-EX.";

  public reduceEffect(store: StoreLike, state: State, effect: Effect): State {
    // Ref: set-lost-origin/panic-mask.ts (tool-based damage prevention)
    if (effect instanceof DealDamageEffect && effect.target.tools.includes(this)) {
      const player = effect.player;
      const targetPlayer = StateUtils.findOwner(state, effect.target);

      // Try to reduce ToolEffect, to check if something is blocking the tool from working
      try {
        const stub = new ToolEffect(effect.player, this);
        store.reduceEffect(state, stub);
      } catch {
        return state;
      }

      if (effect.damage <= 0 || player === targetPlayer) {
        return state;
      }

      // Check if the attached Pokemon is a Fairy type
      const checkTargetType = new CheckPokemonTypeEffect(effect.target);
      store.reduceEffect(state, checkTargetType);
      if (!checkTargetType.cardTypes.includes(CardType.FAIRY)) {
        return state;
      }

      // Check if the attacking Pokemon is Grass GX/EX
      const attackingPokemon = player.active.getPokemonCard();
      if (attackingPokemon) {
        const checkAttackerType = new CheckPokemonTypeEffect(player.active);
        store.reduceEffect(state, checkAttackerType);
        const isGrass = checkAttackerType.cardTypes.includes(CardType.GRASS);
        const isGxOrEx =
          attackingPokemon.hasTag(CardTag.POKEMON_GX) ||
          attackingPokemon.hasTag(CardTag.POKEMON_EX);

        if (isGrass && isGxOrEx) {
          effect.damage = 0;
        }
      }
    }

    return state;
  }
}
