// This file was auto-generated by the card stub generator.
// Card effects were implemented by an agent.
// If you have any questions or feedback, reach out to @C4 in the discord.

import {
  ADD_CONFUSION_TO_PLAYER_ACTIVE,
  AFTER_ATTACK,
  COIN_FLIP_PROMPT,
  SHUFFLE_DECK,
  WAS_ATTACK_USED,
  MOVE_POKEMON_OFF_BOARD,
} from '../../../game/store/prefabs/prefabs';
import { CardType, Stage } from '../../../game/store/card/card-types';
import { StateUtils } from '../../../game/store/state-utils';
import { PokemonCard } from '../../../game/store/card/pokemon-card';
import { Effect } from '../../../game/store/effects/effect';
import { State, StoreLike } from '../../../game';
import { AfterAttackEffect, EndTurnEffect } from '../../../game/store/effects/game-phase-effects';
export class TapuFini extends PokemonCard {
  public stage: Stage = Stage.BASIC;
  public cardType: CardType[] = [Y];
  public hp: number = 120;
  public weakness = [{ type: M }];
  public resistance = [{ type: D, value: -20 }];
  public retreat = [C];

  public attacks = [{
    name: 'Dream Away',
    cost: [Y, C],
    damage: 0,
    text: 'Flip a coin. If heads, your opponent shuffles their Active Pokémon and all cards attached to it into their deck.'
  }, {
    name: 'Wonder Shine',
    cost: [Y, Y, C],
    damage: 100,
    text: 'Your opponent\'s Active Pokémon is now Confused.'
  }];

  public set: string = 'LOT';
  public setNumber: string = '151';
  public cardImage: string = 'assets/cardback.png';
  public name: string = 'Tapu Fini';
  public fullName: string = 'Tapu Fini LOT';

  public usedDreamAway = false;

  public reduceEffect(store: StoreLike, state: State, effect: Effect): State {
    // Attack 1: Dream Away
    // Refs: AGENTS-patterns.md (coin flip), set-steam-siege/bastiodon.ts (AfterAttackEffect pattern)
    if (WAS_ATTACK_USED(effect, 0, this)) {
      COIN_FLIP_PROMPT(store, state, effect.player, result => {
        if (result) {
          this.usedDreamAway = true;
        }
      });
    }

    // Shuffle opponent's active into deck after attack
    if (effect instanceof AfterAttackEffect && this.usedDreamAway) {
      this.usedDreamAway = false;
      const player = effect.player;
      const opponent = StateUtils.getOpponent(state, player);

      MOVE_POKEMON_OFF_BOARD(store, state, opponent.active, {
        pokemonDestination: opponent.deck,
        sourceCard: this,
      });
      SHUFFLE_DECK(store, state, opponent);
    }

    if (effect instanceof EndTurnEffect) {
      this.usedDreamAway = false;
    }

    // Attack 2: Wonder Shine
    // Ref: set-celestial-storm/deoxys-2.ts (Confused status)
    if (AFTER_ATTACK(effect, 1, this)) {
      ADD_CONFUSION_TO_PLAYER_ACTIVE(store, state, effect.opponent, this);
    }

    return state;
  }
}
