// This file was auto-generated by the card stub generator.
// Card effects were implemented by an agent.
// If you have any questions or feedback, reach out to @C4 in the discord.

import { PokemonCard } from '../../../game/store/card/pokemon-card';
import { Stage, CardType } from '../../../game/store/card/card-types';
import { PowerType, StoreLike, State, StateUtils, GameError, GameMessage, Card, PlayerType, SuperType } from '../../../game';
import { Effect } from '../../../game/store/effects/effect';
import { CheckProvidedEnergyEffect } from '../../../game/store/effects/check-effects';
import { ChooseCardsPrompt } from '../../../game/store/prompts/choose-cards-prompt';
import {WAS_ATTACK_USED, WAS_POWER_USED, IS_ABILITY_BLOCKED, USE_ABILITY_ONCE_PER_TURN, ABILITY_USED, REMOVE_MARKER_AT_END_OF_TURN, ADD_MARKER, HAS_MARKER, MOVE_CARDS } from '../../../game/store/prefabs/prefabs';

export class Typhlosion extends PokemonCard {
  public stage: Stage = Stage.STAGE_2;
  public evolvesFrom: string = 'Quilava';
  public cardType: CardType[] = [R];
  public hp: number = 160;
  public weakness = [{ type: W }];
  public retreat = [C, C];

  public powers = [{
    name: 'Blazing Energy',
    useWhenInPlay: true,
    powerType: PowerType.ABILITY,
    text: 'Once during your turn (before your attack), you may use this Ability. All Energy attached to your Pokémon are [R] Energy instead of their usual type until the end of your turn. (This includes cards that come into play on this turn.)'
  }];

  public attacks = [
    {
      name: 'Lost Flame',
      cost: [R, R, R, R],
      damage: 120,
      text: 'Put 2 Energy attached to your opponent\'s Active Pokémon in the Lost Zone.'
    }
  ];

  public set: string = 'LOT';
  public setNumber: string = '42';
  public cardImage: string = 'assets/cardback.png';
  public name: string = 'Typhlosion';
  public fullName: string = 'Typhlosion LOT';

  public readonly BLAZING_ENERGY_MARKER = 'TYPHLOSION_LOT_BLAZING_ENERGY_MARKER';
  public readonly BLAZING_ENERGY_ACTIVE_MARKER = 'TYPHLOSION_LOT_BLAZING_ENERGY_ACTIVE_MARKER';

  public reduceEffect(store: StoreLike, state: State, effect: Effect): State {
    // Ability: Blazing Energy
    // Ref: set-evolutions/charizard.ts (Energy Burn - energy type override)
    if (WAS_POWER_USED(effect, 0, this)) {
      const player = effect.player;

      if (IS_ABILITY_BLOCKED(store, state, player, this)) {
        throw new GameError(GameMessage.BLOCKED_BY_EFFECT);
      }

      USE_ABILITY_ONCE_PER_TURN(player, this.BLAZING_ENERGY_MARKER, this);
      ABILITY_USED(player, this);

      ADD_MARKER(this.BLAZING_ENERGY_ACTIVE_MARKER, player, this);
    }

    // Intercept energy checks to override types to Fire while marker is active
    if (effect instanceof CheckProvidedEnergyEffect) {
      let owner: any = null;
      state.players.forEach(p => {
        p.forEachPokemon(PlayerType.BOTTOM_PLAYER, (cardList) => {
          if (cardList.getPokemonCard() === this) {
            owner = p;
          }
        });
      });

      if (owner && HAS_MARKER(this.BLAZING_ENERGY_ACTIVE_MARKER, owner, this)) {
        // Check if the source belongs to the same player
        let sourceOwner: any = null;
        state.players.forEach(p => {
          p.forEachPokemon(PlayerType.BOTTOM_PLAYER, (cardList) => {
            if (cardList === effect.source) {
              sourceOwner = p;
            }
          });
        });

        if (sourceOwner === owner) {
          effect.energyMap.forEach(em => {
            em.provides = em.provides.map(() => CardType.FIRE);
          });
        }
      }
    }

    REMOVE_MARKER_AT_END_OF_TURN(effect, this.BLAZING_ENERGY_MARKER, this);
    REMOVE_MARKER_AT_END_OF_TURN(effect, this.BLAZING_ENERGY_ACTIVE_MARKER, this);

    // Attack 1: Lost Flame
    // Ref: set-lost-origin/bouffalant.ts (Lost Headbutt - energy to Lost Zone)
    if (WAS_ATTACK_USED(effect, 0, this)) {
      const player = effect.player;
      const opponent = StateUtils.getOpponent(state, player);

      const energyCount = opponent.active.cards.filter(c => c.superType === SuperType.ENERGY).length;
      if (energyCount === 0) {
        return state;
      }

      const toRemove = Math.min(2, energyCount);

      store.prompt(state, new ChooseCardsPrompt(
        player,
        GameMessage.CHOOSE_CARD_TO_DISCARD,
        opponent.active,
        { superType: SuperType.ENERGY },
        { min: toRemove, max: toRemove, allowCancel: false }
      ), (selected: Card[]) => {
        const cards = selected || [];
        cards.forEach(card => {
          MOVE_CARDS(store, state, opponent.active, opponent.lostzone, { cards: [card], sourceCard: this });
        });
      });
    }

    return state;
  }
}
