// This file was auto-generated by the card stub generator.
// Card effects were implemented by an agent.
// If you have any questions or feedback, reach out to @C4 in the discord.

import { PokemonCard } from '../../../game/store/card/pokemon-card';
import {
  Stage,
  CardType,
  CardTag,
  SuperType,
  EnergyType,
} from '../../../game/store/card/card-types';
import {
  PowerType,
  StoreLike,
  State,
  StateUtils,
  ConfirmPrompt,
  GameMessage,
  ChooseCardsPrompt,
} from '../../../game';
import { EnergyCard } from '../../../game/store/card/energy-card';
import { Effect } from '../../../game/store/effects/effect';
import { PlayPokemonEffect } from '../../../game/store/effects/play-card-effects';
import {WAS_ATTACK_USED, IS_ABILITY_BLOCKED, MOVE_CARDS } from '../../../game/store/prefabs/prefabs';
import { DISCARD_X_ENERGY_FROM_THIS_POKEMON } from '../../../game/store/prefabs/costs';

export class GiratinaPrismStar extends PokemonCard {
  protected _tags = [CardTag.PRISM_STAR];
  public stage: Stage = Stage.BASIC;
  public cardType: CardType[] = [P];
  public hp: number = 160;
  public weakness = [{ type: D }];
  public resistance = [{ type: F, value: -20 }];
  public retreat = [C, C];

  public powers = [
    {
      name: 'Chaotic Star',
      powerType: PowerType.ABILITY,
      text: 'When you play this Pokémon from your hand onto your Bench during your turn, you may attach 2 [P] Energy cards from your hand to it.',
    },
  ];

  public attacks = [
    {
      name: 'Crisis Dive',
      cost: [P, P, P, P],
      damage: 160,
      text: 'Discard 2 Energy from this Pokémon.',
    },
  ];

  public set: string = 'UPR';
  public setNumber: string = '58';
  public cardImage: string = 'assets/cardback.png';
  public name: string = 'Giratina Prism Star';
  public fullName: string = 'Giratina \u25C7 UPR';

  public reduceEffect(store: StoreLike, state: State, effect: Effect): State {
    // Ability: Chaotic Star (on-play-from-hand)
    // Ref: set-guardians-rising/oricorio-3.ts (Vital Dance - PlayPokemonEffect pattern)
    if (effect instanceof PlayPokemonEffect && effect.pokemonCard === this) {
      const player = effect.player;

      if (IS_ABILITY_BLOCKED(store, state, player, this)) {
        return state;
      }

      // Check if there are [P] Energy cards in hand
      const psychicEnergyInHand = player.hand.cards.filter(
        (c) =>
          c instanceof EnergyCard &&
          c.energyType === EnergyType.BASIC &&
          c.provides.includes(CardType.PSYCHIC),
      );

      if (psychicEnergyInHand.length === 0) {
        return state;
      }

      state = store.prompt(
        state,
        new ConfirmPrompt(player.id, GameMessage.WANT_TO_USE_ABILITY),
        (wantToUse) => {
          if (wantToUse) {
            const maxAttach = Math.min(2, psychicEnergyInHand.length);

            store.prompt(
              state,
              new ChooseCardsPrompt(
                player,
                GameMessage.CHOOSE_CARD_TO_ATTACH,
                player.hand,
                { superType: SuperType.ENERGY, energyType: EnergyType.BASIC },
                {
                  min: 0,
                  max: maxAttach,
                  allowCancel: true,
                  blocked: player.hand.cards.reduce<number[]>((blocked, c, i) => {
                    if (
                      !(
                        c instanceof EnergyCard &&
                        c.energyType === EnergyType.BASIC &&
                        c.provides.includes(CardType.PSYCHIC)
                      )
                    ) {
                      blocked.push(i);
                    }
                    return blocked;
                  }, []),
                },
              ),
              (selected) => {
                const cards = selected || [];
                const pokemonList = StateUtils.findCardList(state, this);
                cards.forEach((card) => {
                  MOVE_CARDS(store, state, player.hand, pokemonList, { cards: [card], sourceCard: this });
                });
              },
            );
          }
        },
      );
    }

    // Attack 1: Crisis Dive
    // Ref: AGENTS-patterns.md (Discard 2 Energy from this Pokemon)
    if (WAS_ATTACK_USED(effect, 0, this)) {
      DISCARD_X_ENERGY_FROM_THIS_POKEMON(store, state, effect, 2);
    }

    return state;
  }
}
