// This file was auto-generated by the card stub generator.
// Card effects were implemented by an agent.
// If you have any questions or feedback, reach out to @C4 in the discord.

import { PokemonCard } from '../../../game/store/card/pokemon-card';
import { Stage, CardType, EnergyType, TrainerType } from '../../../game/store/card/card-types';
import { PowerType, StoreLike, State, StateUtils, GameMessage } from '../../../game';
import { TrainerCard } from '../../../game/store/card/trainer-card';
import { EnergyCard } from '../../../game/store/card/energy-card';
import { Effect } from '../../../game/store/effects/effect';
import { CheckAttackCostEffect } from '../../../game/store/effects/check-effects';
import { ChooseCardsPrompt } from '../../../game/store/prompts/choose-cards-prompt';
import {WAS_ATTACK_USED, IS_ABILITY_BLOCKED, MOVE_CARDS } from '../../../game/store/prefabs/prefabs';

export class MowRotom extends PokemonCard {
  public stage: Stage = Stage.BASIC;
  public cardType: CardType[] = [G];
  public hp: number = 90;
  public weakness = [{ type: R }];
  public retreat = [C];

  public powers = [{
    name: 'Roto Motor',
    powerType: PowerType.ABILITY,
    text: 'If you have 9 or more Pokémon Tool cards in your discard pile, ignore all Energy in the attack cost of each of this Pokémon\'s attacks.'
  }];

  public attacks = [
    {
      name: 'Special Mow',
      cost: [G, C, C],
      damage: 60,
      text: 'Discard a Special Energy from your opponent\'s Active Pokémon.'
    }
  ];

  public set: string = 'UPR';
  public setNumber: string = '14';
  public cardImage: string = 'assets/cardback.png';
  public name: string = 'Mow Rotom';
  public fullName: string = 'Mow Rotom UPR';

  public reduceEffect(store: StoreLike, state: State, effect: Effect): State {
    // Ability: Roto Motor (passive - ignore energy cost if 9+ tools in discard)
    // Ref: set-steam-siege/yanmega.ts (Sonic Vision - CheckAttackCostEffect passive)
    if (effect instanceof CheckAttackCostEffect && effect.player.active.cards.includes(this)) {
      if (effect.player.active.getPokemonCard() !== this) {
        return state;
      }

      const player = effect.player;

      if (IS_ABILITY_BLOCKED(store, state, player, this)) {
        return state;
      }

      const toolCount = player.discard.cards.filter(c =>
        c instanceof TrainerCard && c.trainerType === TrainerType.TOOL
      ).length;

      if (toolCount >= 9) {
        effect.cost = [];
      }
    }

    // Attack 1: Special Mow
    // Ref: set-crimson-invasion/octillery.ts (Special Artillery - discard Special Energy from opponent)
    if (WAS_ATTACK_USED(effect, 0, this)) {
      const player = effect.player;
      const opponent = StateUtils.getOpponent(state, player);

      const hasSpecialEnergy = opponent.active.cards.some(c =>
        c instanceof EnergyCard && c.energyType === EnergyType.SPECIAL
      );

      if (hasSpecialEnergy) {
        // Build blocked list for non-special energy cards
        const blocked: number[] = [];
        opponent.active.cards.forEach((c, index) => {
          if (!(c instanceof EnergyCard) || c.energyType !== EnergyType.SPECIAL) {
            blocked.push(index);
          }
        });

        store.prompt(state, new ChooseCardsPrompt(
          player,
          GameMessage.CHOOSE_CARD_TO_DISCARD,
          opponent.active,
          {},
          { min: 1, max: 1, allowCancel: false, blocked }
        ), selected => {
          if (selected && selected.length > 0) {
            MOVE_CARDS(store, state, opponent.active, opponent.discard, { cards: [selected[0]], sourceCard: this });
          }
        });
      }
    }

    return state;
  }
}
