// This file was auto-generated by the card stub generator.
// Card effects were implemented by an agent.
// If you have any questions or feedback, reach out to @C4 in the discord.

import { PokemonCard } from '../../../game/store/card/pokemon-card';
import { Stage, CardType, SuperType } from '../../../game/store/card/card-types';
import { StoreLike, State, StateUtils, GameMessage, PlayerType, SlotType, MoveEnergyPrompt, CardTarget } from '../../../game';
import { Effect } from '../../../game/store/effects/effect';
import {WAS_ATTACK_USED, MOVE_CARDS } from '../../../game/store/prefabs/prefabs';
import { DISCARD_X_ENERGY_FROM_THIS_POKEMON } from '../../../game/store/prefabs/costs';

export class AlolanGolem extends PokemonCard {
  public stage: Stage = Stage.STAGE_2;
  public evolvesFrom: string = 'Alolan Graveler';
  public cardType: CardType[] = [L];
  public hp: number = 180;
  public weakness = [{ type: F }];
  public resistance = [{ type: M, value: -20 }];
  public retreat = [C, C, C, C];

  public attacks = [
    {
      name: 'Electromagnetic Bomb',
      cost: [],
      damage: 20,
      damageCalculation: 'x',
      text: 'Move any number of [L] Energy from your Benched Pokémon to this Pokémon. This attack does 20 damage for each Energy card you moved in this way.'
    },
    {
      name: 'Super Zap Cannon',
      cost: [L, C, C, C, C],
      damage: 190,
      text: 'Discard 2 Energy from this Pokémon.'
    }
  ];

  public set: string = 'TEU';
  public setNumber: string = '37';
  public cardImage: string = 'assets/cardback.png';
  public name: string = 'Alolan Golem';
  public fullName: string = 'Alolan Golem TEU';

  public reduceEffect(store: StoreLike, state: State, effect: Effect): State {
    // Attack 1: Electromagnetic Bomb
    // Ref: set-ultra-prism/palkia-gx.ts (Spatial Control - move energy from bench)
    if (WAS_ATTACK_USED(effect, 0, this)) {
      const player = effect.player;

      // Only allow moving from bench to active, and only Lightning Energy
      const blockedTo = player.bench.map((_, index) => {
        return { player: PlayerType.BOTTOM_PLAYER, slot: SlotType.BENCH, index } as CardTarget;
      });

      const blockedFrom = [{ player: PlayerType.BOTTOM_PLAYER, slot: SlotType.ACTIVE, index: 0 } as CardTarget];

      store.prompt(state, new MoveEnergyPrompt(
        player.id,
        GameMessage.MOVE_ENERGY_CARDS,
        PlayerType.BOTTOM_PLAYER,
        [SlotType.BENCH, SlotType.ACTIVE],
        { superType: SuperType.ENERGY, cardType: [CardType.LIGHTNING] },
        { allowCancel: true, blockedTo, blockedFrom }
      ), transfers => {
        if (transfers === null) {
          effect.damage = 0;
          return;
        }

        for (const transfer of transfers) {
          const source = StateUtils.getTarget(state, player, transfer.from);
          MOVE_CARDS(store, state, source, player.active, { cards: [transfer.card], sourceCard: this });
        }

        effect.damage = 20 * transfers.length;
      });
    }

    // Attack 2: Super Zap Cannon
    // Ref: AGENTS-patterns.md (discard energy from this Pokemon)
    if (WAS_ATTACK_USED(effect, 1, this)) {
      DISCARD_X_ENERGY_FROM_THIS_POKEMON(store, state, effect, 2);
    }

    return state;
  }
}
