// This file was auto-generated by the card stub generator.
// Card effects were implemented by an agent.
// If you have any questions or feedback, reach out to @C4 in the discord.

import { PokemonCard } from '../../../game/store/card/pokemon-card';
import {
  Stage,
  CardType,
  CardTag,
  SuperType,
  EnergyType,
} from '../../../game/store/card/card-types';
import {
  Card,
  ChooseCardsPrompt,
  EnergyCard,
  GameMessage,
  GameError,
  PokemonCardList,
  PowerType,
  StoreLike,
  State,
  StateUtils,
} from '../../../game';
import { DiscardCardsEffect } from '../../../game/store/effects/attack-effects';
import { Effect } from '../../../game/store/effects/effect';
import {WAS_ATTACK_USED,
  WAS_POWER_USED,
  IS_ABILITY_BLOCKED,
  ABILITY_USED,
  USE_ABILITY_ONCE_PER_TURN,
  REMOVE_MARKER_AT_END_OF_TURN,
  BLOCK_IF_GX_ATTACK_USED,
  SHUFFLE_DECK, MOVE_CARDS } from '../../../game/store/prefabs/prefabs';

export class IncineroarGx extends PokemonCard {
  protected _tags = [CardTag.POKEMON_GX];
  public stage: Stage = Stage.STAGE_2;
  public evolvesFrom: string = 'Torracat';
  public cardType: CardType[] = [D];
  public hp: number = 250;
  public weakness = [{ type: F }];
  public resistance = [{ type: P, value: -20 }];
  public retreat = [C, C, C];

  public readonly SCAR_CHARGE_MARKER = 'INCINEROAR_GX_SCAR_CHARGE_MARKER';

  public powers = [
    {
      name: 'Scar Charge',
      useWhenInPlay: true,
      powerType: PowerType.ABILITY,
      text: 'Once during your turn (before your attack), you may put 3 damage counters on this Pokémon. If you do, search your deck for up to 3 [D] Energy cards and attach them to this Pokémon. Then, shuffle your deck.',
    },
  ];

  public attacks = [
    {
      name: 'Crushing Punch',
      cost: [C, C, C],
      damage: 130,
      text: "Discard a Special Energy from your opponent's Active Pokémon.",
    },
    {
      name: 'Darkest Tornado-GX',
      cost: [C, C, C],
      damage: 10,
      damageCalculation: '+',
      text: "This attack does 50 more damage for each damage counter on this Pokémon. (You can't use more than 1 GX attack in a game.)",
    },
  ];

  public set: string = 'TEU';
  public setNumber: string = '97';
  public cardImage: string = 'assets/cardback.png';
  public name: string = 'Incineroar-GX';
  public fullName: string = 'Incineroar-GX TEU';

  public reduceEffect(store: StoreLike, state: State, effect: Effect): State {
    // Ability: Scar Charge
    // Ref: set-team-up/tapu-koko-prism-star.ts (Dance of the Ancients - search and attach energy)
    if (WAS_POWER_USED(effect, 0, this)) {
      const player = effect.player;

      if (IS_ABILITY_BLOCKED(store, state, player, this)) {
        throw new GameError(GameMessage.BLOCKED_BY_EFFECT);
      }

      USE_ABILITY_ONCE_PER_TURN(player, this.SCAR_CHARGE_MARKER, this);
      ABILITY_USED(player, this);

      // Put 3 damage counters on this Pokemon
      const cardList = StateUtils.findCardList(state, this) as PokemonCardList;
      cardList.damage += 30;

      // Search deck for up to 3 [D] Energy and attach to this Pokemon
      const hasEnergy = player.deck.cards.some(
        (c) =>
          c instanceof EnergyCard &&
          c.energyType === EnergyType.BASIC &&
          c.provides.includes(CardType.DARK),
      );

      if (hasEnergy) {
        state = store.prompt(
          state,
          new ChooseCardsPrompt(
            player,
            GameMessage.CHOOSE_CARD_TO_HAND,
            player.deck,
            { superType: SuperType.ENERGY, energyType: EnergyType.BASIC, name: 'Darkness Energy' },
            { allowCancel: true, min: 0, max: 3 },
          ),
          (selected: Card[] | null) => {
            const cards = selected || [];
            cards.forEach((c) => {
              MOVE_CARDS(store, state, player.deck, cardList, { cards: [c], sourceCard: this });
            });
            SHUFFLE_DECK(store, state, player);
          },
        );
      } else {
        SHUFFLE_DECK(store, state, player);
      }
    }

    REMOVE_MARKER_AT_END_OF_TURN(effect, this.SCAR_CHARGE_MARKER, this);

    // Attack 1: Crushing Punch
    // Ref: set-breakpoint/golduck.ts (Derail - discard a Special Energy from opponent's active)
    if (WAS_ATTACK_USED(effect, 0, this)) {
      const player = effect.player;
      const opponent = StateUtils.getOpponent(state, player);

      const hasSpecialEnergy = opponent.active.cards.some(
        (c) => c instanceof EnergyCard && c.energyType === EnergyType.SPECIAL,
      );

      if (hasSpecialEnergy) {
        store.prompt(
          state,
          new ChooseCardsPrompt(
            player,
            GameMessage.CHOOSE_CARD_TO_DISCARD,
            opponent.active,
            { superType: SuperType.ENERGY, energyType: EnergyType.SPECIAL },
            { min: 1, max: 1, allowCancel: false },
          ),
          (selected) => {
            const cards: Card[] = selected || [];
            if (cards.length > 0) {
              const discardEnergy = new DiscardCardsEffect(effect, cards);
              discardEnergy.target = opponent.active;
              store.reduceEffect(state, discardEnergy);
            }
          },
        );
      }
    }

    // Attack 2: Darkest Tornado-GX
    // Ref: AGENTS-patterns.md (damage per damage counter)
    if (WAS_ATTACK_USED(effect, 1, this)) {
      const player = effect.player;

      BLOCK_IF_GX_ATTACK_USED(player);
      player.usedGX = true;

      const damageCounters = player.active.damage / 10;
      effect.damage += 50 * damageCounters;
    }

    return state;
  }
}
