// This file was auto-generated by the card stub generator.
// Card effects were implemented by an agent.
// If you have any questions or feedback, reach out to @C4 in the discord.

import { PokemonCard } from '../../../game/store/card/pokemon-card';
import { Stage, CardType, SuperType } from '../../../game/store/card/card-types';
import { StoreLike, State, ChooseCardsPrompt, GameMessage } from '../../../game';
import { Effect } from '../../../game/store/effects/effect';
import {WAS_ATTACK_USED, SHUFFLE_DECK, MOVE_CARDS } from '../../../game/store/prefabs/prefabs';

export class Spiritomb extends PokemonCard {
  public stage: Stage = Stage.BASIC;
  public cardType: CardType[] = [D];
  public hp: number = 70;
  public retreat = [C];

  public attacks = [
    {
      name: 'Spirit Compressor',
      cost: [C],
      damage: 0,
      text: 'Search your deck for up to 4 Pokémon and discard them. Then, shuffle your deck.'
    },
    {
      name: 'Spooky Shot',
      cost: [C],
      damage: 20,
      text: ''
    }
  ];

  public set: string = 'TEU';
  public setNumber: string = '89';
  public cardImage: string = 'assets/cardback.png';
  public name: string = 'Spiritomb';
  public fullName: string = 'Spiritomb TEU';

  public reduceEffect(store: StoreLike, state: State, effect: Effect): State {
    // Attack 1: Spirit Compressor
    // Ref: set-celestial-storm/banette.ts (search deck for cards to discard)
    if (WAS_ATTACK_USED(effect, 0, this)) {
      const player = effect.player;

      if (player.deck.cards.length === 0) {
        return state;
      }

      store.prompt(state, new ChooseCardsPrompt(
        player,
        GameMessage.CHOOSE_CARD_TO_DISCARD,
        player.deck,
        { superType: SuperType.POKEMON },
        { min: 0, max: 4, allowCancel: true }
      ), selected => {
        const cards = selected || [];
        cards.forEach(c => {
          MOVE_CARDS(store, state, player.deck, player.discard, { cards: [c], sourceCard: this });
        });

        SHUFFLE_DECK(store, state, player);
      });
    }

    return state;
  }
}
