// This file was auto-generated by the card stub generator.
// Card effects were implemented by an agent.
// If you have any questions or feedback, reach out to @C4 in the discord.

import { PokemonCard } from '../../../game/store/card/pokemon-card';
import { Stage, CardType, CardTag } from '../../../game/store/card/card-types';
import { StoreLike, State } from '../../../game';
import { EnergyCard } from '../../../game/store/card/energy-card';
import { Effect } from '../../../game/store/effects/effect';
import {BREAK_RULE, WAS_ATTACK_USED, MOVE_CARDS } from '../../../game/store/prefabs/prefabs';

export class NinetalesBreak extends PokemonCard {
  protected _tags = [CardTag.BREAK];
  public stage: Stage = Stage.BREAK;
  public evolvesFrom: string = 'Ninetales';
  public cardType: CardType[] = [R];
  public hp: number = 140;
  public retreat = [];

  public attacks = [
    {
      name: 'Explosive Fireball',
      cost: [R, C],
      damage: 10,
      damageCalculation: '+',
      text: 'Discard all [R] Energy attached to this Pokémon. This attack does 60 more damage for each Energy card discarded in this way.',
    },
  ];

  public set: string = 'EVO';
  public setNumber: string = '16';
  public cardImage: string = 'assets/cardback.png';
  public name: string = 'Ninetales BREAK';
  public fullName: string = 'Ninetales BREAK EVO';

  public reduceEffect(store: StoreLike, state: State, effect: Effect): State {
    // Attack 1: Explosive Fireball
    // Ref: AGENTS.md (Discard all [type] Energy - manual pattern), set-primal-clash/manectric.ts
    if (WAS_ATTACK_USED(effect, 0, this)) {
      const player = effect.player;
      const fireEnergy = player.active.cards.filter(
        (c) => c instanceof EnergyCard && c.provides.includes(CardType.FIRE),
      );
      const discardCount = fireEnergy.length;
      fireEnergy.forEach((c) => {
        MOVE_CARDS(store, state, player.active, player.discard, { cards: [c], sourceCard: this });
      });
      effect.damage += 60 * discardCount;
    }

    BREAK_RULE(effect, state, this);

    return state;
  }
}
