// This file was auto-generated by the card stub generator.
// Card effects were implemented by an agent.
// If you have any questions or feedback, reach out to @C4 in the discord.

import { PokemonCard } from '../../../game/store/card/pokemon-card';
import { Stage, CardType } from '../../../game/store/card/card-types';
import { StoreLike, State } from '../../../game';
import { Effect } from '../../../game/store/effects/effect';
import { WAS_ATTACK_USED, SELECT_PROMPT } from '../../../game/store/prefabs/prefabs';
import { DEFENDING_POKEMON_WEAKNESS_IS_NOW } from '../../../game/store/prefabs/effect-of-attack-prefabs';

export class Porygon extends PokemonCard {
  public stage: Stage = Stage.BASIC;
  public cardType: CardType[] = [C];
  public hp: number = 60;
  public weakness = [{ type: F }];
  public retreat = [C];

  public attacks = [
    {
      name: 'Conversion 3',
      cost: [C],
      damage: 0,
      text: 'Choose Grass, Fire, Water, Lightning, Psychic, Fighting, Darkness, Metal, Fairy, or Dragon type. The Defending Pok\u00e9mon\'s Weakness is now that type until the end of your next turn. (The amount of Weakness doesn\'t change.)'
    }
  ];

  public set: string = 'EVO';
  public setNumber: string = '71';
  public cardImage: string = 'assets/cardback.png';
  public name: string = 'Porygon';
  public fullName: string = 'Porygon EVO';

  public reduceEffect(store: StoreLike, state: State, effect: Effect): State {
    if (WAS_ATTACK_USED(effect, 0, this)) {
      const player = effect.player;
      const typeNames = ['Grass', 'Fire', 'Water', 'Lightning', 'Psychic', 'Fighting', 'Darkness', 'Metal', 'Fairy', 'Dragon'];

      SELECT_PROMPT(store, state, player, typeNames, choice => {
        const typeMap: { [key: string]: CardType } = {
          'Grass': CardType.GRASS,
          'Fire': CardType.FIRE,
          'Water': CardType.WATER,
          'Lightning': CardType.LIGHTNING,
          'Psychic': CardType.PSYCHIC,
          'Fighting': CardType.FIGHTING,
          'Darkness': CardType.DARK,
          'Metal': CardType.METAL,
          'Fairy': CardType.FAIRY,
          'Dragon': CardType.DRAGON,
        };
        DEFENDING_POKEMON_WEAKNESS_IS_NOW(store, state, effect, this, typeMap[choice] || CardType.COLORLESS);
      });
    }

    return state;
  }
}
