// This file was auto-generated by the card stub generator.
// Card effects were implemented by an agent.
// If you have any questions or feedback, reach out to @C4 in the discord.

import { PokemonCard } from '../../../game/store/card/pokemon-card';
import { Stage, CardType } from '../../../game/store/card/card-types';
import { StoreLike, State } from '../../../game';
import { Effect } from '../../../game/store/effects/effect';
import { DEVOLVE_DEFENDING_AFTER_ATTACK, WAS_ATTACK_USED } from '../../../game/store/prefabs/prefabs';
import { THIS_POKEMON_HAS_NO_WEAKNESS_DURING_OPPONENTS_NEXT_TURN } from '../../../game/store/prefabs/effect-of-attack-prefabs';

export class Golurk extends PokemonCard {
  public stage: Stage = Stage.STAGE_1;
  public evolvesFrom: string = 'Golett';
  public cardType: CardType[] = [P];
  public hp: number = 130;
  public weakness = [{ type: D }];
  public retreat = [C, C, C, C];

  public attacks = [
    {
      name: 'Devolution Punch',
      cost: [P, C, C],
      damage: 60,
      text: 'Devolve the Defending Pokémon and put the highest Stage evolution card on it into your opponent\'s hand.'
    },
    {
      name: 'Ghost Hammer',
      cost: [P, P, C, C],
      damage: 90,
      text: 'During your opponent\'s next turn, this Pokémon has no Weakness.'
    }
  ];

  public set: string = 'BCR';
  public setNumber: string = '150';
  public cardImage: string = 'assets/cardback.png';
  public name: string = 'Golurk';
  public fullName: string = 'Golurk BCR';
  public reduceEffect(store: StoreLike, state: State, effect: Effect): State {
    // Attack 1: Devolution Punch
    // Ref: set-lost-thunder/dialga.ts (Turn Back Time)
    if (WAS_ATTACK_USED(effect, 0, this)) {
      return state;
    }

    state = DEVOLVE_DEFENDING_AFTER_ATTACK(store, state, effect, 0, this, 'hand');

    if (WAS_ATTACK_USED(effect, 1, this)) {
      return THIS_POKEMON_HAS_NO_WEAKNESS_DURING_OPPONENTS_NEXT_TURN(store, state, effect, this);
    }

    return state;
  }
}
