// This file was auto-generated by the card stub generator.
// Card effects were implemented by an agent.
// If you have any questions or feedback, reach out to @C4 in the discord.

import { PokemonCard } from '../../../game/store/card/pokemon-card';
import { Stage, CardType } from '../../../game/store/card/card-types';
import { StateUtils, StoreLike, State } from '../../../game';
import { Effect } from '../../../game/store/effects/effect';
import {MULTIPLE_COIN_FLIPS_PROMPT, WAS_ATTACK_USED, MOVE_CARDS } from '../../../game/store/prefabs/prefabs';

export class Mienshao extends PokemonCard {
  public stage: Stage = Stage.STAGE_1;
  public evolvesFrom: string = 'Mienfoo';
  public cardType: CardType[] = [F];
  public hp: number = 90;
  public weakness = [{ type: P }];
  public retreat = [C];

  public attacks = [{
    name: 'Knock Off',
    cost: [F, C],
    damage: 20,
    text: 'Discard a random card from your opponent\'s hand.'
  }, {
    name: 'Double Whip',
    cost: [F, C, C],
    damage: 70,
    damageCalculation: 'x',
    text: 'Flip 2 coins. This attack does 70 damage times the number of heads.'
  }];

  public set: string = 'BCR';
  public setNumber: string = '88';
  public cardImage: string = 'assets/cardback.png';
  public name: string = 'Mienshao';
  public fullName: string = 'Mienshao BCR';

  public reduceEffect(store: StoreLike, state: State, effect: Effect): State {
    // Attack 1: Knock Off
    // Ref: set-emerging-powers/purrloin.ts (random discard from hand)
    if (WAS_ATTACK_USED(effect, 0, this)) {
      const opponent = StateUtils.getOpponent(state, effect.player);
      if (opponent.hand.cards.length === 0) {
        return state;
      }

      const randomIndex = Math.floor(Math.random() * opponent.hand.cards.length);
      const cardToDiscard = opponent.hand.cards[randomIndex];
      MOVE_CARDS(store, state, opponent.hand, opponent.discard, { cards: [cardToDiscard], sourceCard: this });
    }

    // Attack 2: Double Whip
    // Ref: set-boundaries-crossed/black-kyurem.ts (Dual Claw)
    if (WAS_ATTACK_USED(effect, 1, this)) {
      MULTIPLE_COIN_FLIPS_PROMPT(store, state, effect.player, 2, results => {
        effect.damage = 70 * results.filter(r => r).length;
      });
    }

    return state;
  }
}
