// This file was auto-generated by the card stub generator.
// Card effects were implemented by an agent.
// If you have any questions or feedback, reach out to @C4 in the discord.

import { TrainerCard } from '../../../game/store/card/trainer-card';
import { CardTag, TrainerType } from '../../../game/store/card/card-types';
import { StoreLike, State, StateUtils } from '../../../game';
import { Effect } from '../../../game/store/effects/effect';
import { CheckAttackCostEffect } from '../../../game/store/effects/check-effects';
import { PokemonCardList } from '../../../game/store/state/pokemon-card-list';
import { IS_TOOL_BLOCKED } from '../../../game/store/prefabs/prefabs';

export class VictoryPiece extends TrainerCard {
  protected _trainerType: TrainerType = TrainerType.TOOL;
  protected _tags = [CardTag.ACE_SPEC];
  public set: string = 'PLS';
  public setNumber: string = '130';
  public cardImage: string = 'assets/cardback.png';
  public name: string = 'Victory Piece';
  public fullName: string = 'Victory Piece PLS';
  public text: string =
    "If this card is attached to Victini-EX, Victini-EX can use its attacks regardless of the amount or type of Energy attached to it. You can't have more than 1 ACE SPEC card in your deck.";

  public reduceEffect(store: StoreLike, state: State, effect: Effect): State {
    // Ref: set-phantom-forces/dimension-valley.ts (CheckAttackCostEffect for cost reduction)
    if (effect instanceof CheckAttackCostEffect) {
      // Find where this tool is attached
      const cardList = StateUtils.findCardList(state, this);

      // Check if the card list is a PokemonCardList (i.e., attached to a Pokemon)
      if (!(cardList instanceof PokemonCardList)) {
        return state;
      }

      const pokemonCard = cardList.getPokemonCard();
      if (!pokemonCard || pokemonCard.name !== 'Victini-EX') {
        return state;
      }

      if (IS_TOOL_BLOCKED(store, state, effect.player, this)) {
        return state;
      }

      // Check if the attack is being used by the Pokemon with this tool
      if (effect.player.active === cardList) {
        effect.cost = [];
      }
    }

    return state;
  }
}
