// This file was auto-generated by the card stub generator.
// Card effects were implemented by an agent.
// If you have any questions or feedback, reach out to @C4 in the discord.

import { PokemonCard } from '../../../game/store/card/pokemon-card';
import { Stage, CardType, CardTag } from '../../../game/store/card/card-types';
import { StoreLike, State, StateUtils } from '../../../game';
import { Effect } from '../../../game/store/effects/effect';
import {WAS_ATTACK_USED, MOVE_CARDS } from '../../../game/store/prefabs/prefabs';

export class CharizardV extends PokemonCard {
  protected _tags = [CardTag.POKEMON_V];
  public stage: Stage = Stage.BASIC;
  public cardType: CardType[] = [R];
  public hp: number = 220;
  public weakness = [{ type: W }];
  public retreat = [C, C];

  public attacks = [
    {
      name: 'Incinerate',
      cost: [R, R, C],
      damage: 90,
      text: "Before doing damage, discard all Pokémon Tools from your opponent's Active Pokémon.",
    },
    {
      name: 'Heat Blast',
      cost: [R, R, R, C],
      damage: 180,
      text: '',
    },
  ];

  public regulationMark: string = 'F';
  public set: string = 'BRS';
  public setNumber: string = '17';
  public cardImage: string = 'assets/cardback.png';
  public name: string = 'Charizard V';
  public fullName: string = 'Charizard V BRS 17';

  public reduceEffect(store: StoreLike, state: State, effect: Effect): State {
    // Attack 1: Incinerate
    // Ref: set-unbroken-bonds/lickilicky.ts (Eat Up - discard all tools from opponent's active)
    if (WAS_ATTACK_USED(effect, 0, this)) {
      const player = effect.player;
      const opponent = StateUtils.getOpponent(state, player);
      const activePokemon = opponent.active;

      if (activePokemon.tools.length > 0) {
        MOVE_CARDS(store, state, activePokemon, opponent.discard, { cards: [...activePokemon.tools], sourceCard: this });
      }
    }

    return state;
  }
}
