// This file was auto-generated by the card stub generator.
// Card effects were implemented by an agent.
// If you have any questions or feedback, reach out to @C4 in the discord.

import { PokemonCard } from '../../../game/store/card/pokemon-card';
import { Stage, CardType } from '../../../game/store/card/card-types';
import { StoreLike, State, StateUtils } from '../../../game';
import { Effect } from '../../../game/store/effects/effect';
import { AfterAttackEffect, EndTurnEffect } from '../../../game/store/effects/game-phase-effects';
import {WAS_ATTACK_USED, SHUFFLE_DECK, MOVE_CARDS } from '../../../game/store/prefabs/prefabs';
import { DISCARD_X_ENERGY_FROM_THIS_POKEMON } from '../../../game/store/prefabs/costs';

export class Staraptor extends PokemonCard {
  public stage: Stage = Stage.STAGE_2;
  public evolvesFrom: string = 'Staravia';
  public cardType: CardType[] = [C];
  public hp: number = 150;
  public weakness = [{ type: L }];
  public resistance = [{ type: F, value: -30 }];
  public retreat = [C];

  public attacks = [
    {
      name: 'Strong Breeze',
      cost: [C, C, C],
      damage: 0,
      text: 'Your opponent shuffles their Active Pokémon and all attached cards into their deck.'
    },
    {
      name: 'Spinning Bird',
      cost: [C, C, C, C],
      damage: 180,
      text: 'Discard 2 Energy from this Pokémon.'
    }
  ];

  public regulationMark: string = 'F';
  public set: string = 'BRS';
  public setNumber: string = '119';
  public cardImage: string = 'assets/cardback.png';
  public name: string = 'Staraptor';
  public fullName: string = 'Staraptor BRS 119';

  public usedStrongBreeze = false;

  public reduceEffect(store: StoreLike, state: State, effect: Effect): State {
    // Attack 1: Strong Breeze
    // Ref: set-plasma-freeze/staraptor.ts (Strong Breeze - shuffle opponent's active and all attached into deck)
    if (WAS_ATTACK_USED(effect, 0, this)) {
      this.usedStrongBreeze = true;
    }

    if (effect instanceof AfterAttackEffect && this.usedStrongBreeze) {
      this.usedStrongBreeze = false;
      const player = effect.player;
      const opponent = StateUtils.getOpponent(state, player);

      // Move all cards from opponent's active to their deck
      const cardsToShuffle = opponent.active.cards.slice();
      cardsToShuffle.forEach(card => {
        MOVE_CARDS(store, state, opponent.active, opponent.deck, { cards: [card], sourceCard: this });
      });
      opponent.active.clearEffects();

      SHUFFLE_DECK(store, state, opponent);
    }

    if (effect instanceof EndTurnEffect) {
      this.usedStrongBreeze = false;
    }

    // Attack 2: Spinning Bird
    // Ref: AGENTS-patterns.md (discard X energy from this Pokemon - DISCARD_X_ENERGY_FROM_THIS_POKEMON)
    if (WAS_ATTACK_USED(effect, 1, this)) {
      DISCARD_X_ENERGY_FROM_THIS_POKEMON(store, state, effect, 2);
    }

    return state;
  }
}
