// This file was auto-generated by the card stub generator.
// Card effects were implemented by an agent.
// If you have any questions or feedback, reach out to @C4 in the discord.

import { TrainerCard } from '../../../game/store/card/trainer-card';
import { TrainerType, CardType } from '../../../game/store/card/card-types';
import { StoreLike, State, StateUtils, pokemonHasCardType } from '../../../game';
import { Effect } from '../../../game/store/effects/effect';
import { DealDamageEffect } from '../../../game/store/effects/attack-effects';
import { IS_TOOL_BLOCKED } from '../../../game/store/prefabs/prefabs';

export class FireResistantGloves extends TrainerCard {
  protected _trainerType: TrainerType = TrainerType.TOOL;
  public regulationMark: string = 'E';
  public set: string = 'CRE';
  public setNumber: string = '138';
  public cardImage: string = 'assets/cardback.png';
  public name: string = 'Fire-Resistant Gloves';
  public fullName: string = 'Fire-Resistant Gloves CRE';
  public text: string =
    "Attach a Pokémon Tool to 1 of your Pokémon that doesn't already have a Pokémon Tool attached. The attacks of the Pokémon this card is attached to do 30 more damage to your opponent's Active Fire Pokémon (before applying Weakness and Resistance). You may play any number of Item cards during your turn.";

  public reduceEffect(store: StoreLike, state: State, effect: Effect): State {
    // Ref: set-chilling-reign/justified-gloves.ts (DealDamageEffect + source.tools + type check)
    if (!(effect instanceof DealDamageEffect) || !effect.source.tools.includes(this)) {
      return state;
    }

    if (IS_TOOL_BLOCKED(store, state, effect.player, this)) {
      return state;
    }

    const opponent = StateUtils.getOpponent(state, effect.player);
    // Only applies to attacks targeting opponent's active
    if (effect.target !== opponent.active || effect.damage <= 0) {
      return state;
    }

    const targetCard = effect.target.getPokemonCard();
    if (targetCard && pokemonHasCardType(targetCard, CardType.FIRE)) {
      effect.damage += 30;
    }

    return state;
  }
}
