// This file was auto-generated by the card stub generator.
// Card effects were implemented by an agent.
// If you have any questions or feedback, reach out to @C4 in the discord.

import { TrainerCard } from '../../../game/store/card/trainer-card';
import { TrainerType } from '../../../game/store/card/card-types';
import { StoreLike, State, StateUtils } from '../../../game';
import { Effect } from '../../../game/store/effects/effect';
import { DealDamageEffect } from '../../../game/store/effects/attack-effects';
import { IS_TOOL_BLOCKED } from '../../../game/store/prefabs/prefabs';

export class GalarianChestplate extends TrainerCard {
  protected _trainerType: TrainerType = TrainerType.TOOL;
  public regulationMark: string = 'E';
  public set: string = 'CRE';
  public setNumber: string = '141';
  public cardImage: string = 'assets/cardback.png';
  public name: string = 'Galarian Chestplate';
  public fullName: string = 'Galarian Chestplate CRE';
  public text: string =
    'Attach a Pokémon Tool to 1 of your Pokémon that doesn\'t already have a Pokémon Tool attached. If the Pokémon this card is attached to has "Galarian" in its name, it takes 30 less damage from attacks from your opponent\'s Pokémon (after applying Weakness and Resistance). You may play any number of Item cards during your turn.';

  public reduceEffect(store: StoreLike, state: State, effect: Effect): State {
    // Ref: set-unbroken-bonds/fairy-charm-lightning.ts (DealDamageEffect + target.tools check + damage reduction)
    if (effect instanceof DealDamageEffect && effect.target.tools.includes(this)) {
      const player = StateUtils.findOwner(state, effect.target);

      if (IS_TOOL_BLOCKED(store, state, player, this)) {
        return state;
      }

      // Only reduces damage if the attached Pokemon has "Galarian" in its name
      const attachedPokemon = effect.target.getPokemonCard();
      if (attachedPokemon && attachedPokemon.name.includes('Galarian')) {
        effect.damage = Math.max(0, effect.damage - 30);
      }
    }

    return state;
  }
}
