// This file was auto-generated by the card stub generator.
// Card effects were implemented by an agent.
// If you have any questions or feedback, reach out to @C4 in the discord.

import { TrainerCard } from '../../../game/store/card/trainer-card';
import { TrainerType, CardTag } from '../../../game/store/card/card-types';
import { StoreLike, State, StateUtils } from '../../../game';
import { Effect } from '../../../game/store/effects/effect';
import { WAS_TRAINER_USED } from '../../../game/store/prefabs/trainer-prefabs';
import { DRAW_CARDS } from '../../../game/store/prefabs/prefabs';

export class Honey extends TrainerCard {
  protected _trainerType: TrainerType = TrainerType.SUPPORTER;
  public regulationMark: string = 'E';
  public set: string = 'CRE';
  public setNumber: string = '142';
  public cardImage: string = 'assets/cardback.png';
  public name: string = 'Honey';
  public fullName: string = 'Honey CRE';
  public text: string =
    "Draw a card for each of your opponent's Benched Pokémon V. You may play only 1 Supporter card during your turn.";

  public reduceEffect(store: StoreLike, state: State, effect: Effect): State {
    // Ref: set-chilling-reign/doctor.ts (WAS_TRAINER_USED pattern), set-roaring-skies/altaria.ts (draw for each bench count)
    if (WAS_TRAINER_USED(effect, this)) {
      const player = effect.player;
      const opponent = StateUtils.getOpponent(state, player);

      // Count opponent's benched Pokemon V (including VMAX, VSTAR)
      let vCount = 0;
      opponent.bench.forEach((slot) => {
        const card = slot.getPokemonCard();
        if (
          card &&
          (card.hasTag(CardTag.POKEMON_V) ||
            card.hasTag(CardTag.POKEMON_VMAX) ||
            card.hasTag(CardTag.POKEMON_VSTAR))
        ) {
          vCount++;
        }
      });

      DRAW_CARDS(store, state, player, vCount);
    }

    return state;
  }
}
