// This file was auto-generated by the card stub generator.
// Card effects were implemented by an agent.
// If you have any questions or feedback, reach out to @C4 in the discord.

import { PokemonCard } from '../../../game/store/card/pokemon-card';
import { Stage, CardType, CardTag } from '../../../game/store/card/card-types';
import {
  ChoosePokemonPrompt,
  GameMessage,
  PlayerType,
  PowerType,
  SlotType,
  StoreLike,
  State,
  StateUtils,
  PokemonCardList,
} from '../../../game';
import { Effect } from '../../../game/store/effects/effect';
import { AfterAttackEffect, EndTurnEffect } from '../../../game/store/effects/game-phase-effects';
import { PlayPokemonEffect } from '../../../game/store/effects/play-card-effects';
import { CardTarget } from '../../../game/store/actions/play-card-action';
import {WAS_ATTACK_USED,
  IS_ABILITY_BLOCKED,
  CONFIRMATION_PROMPT, MOVE_CARDS } from '../../../game/store/prefabs/prefabs';
import { PUT_THIS_POKEMON_AND_ALL_ATTACHED_CARDS_INTO_YOUR_HAND } from '../../../game/store/prefabs/attack-effects';

export class LiepardV extends PokemonCard {
  protected _tags = [CardTag.POKEMON_V];
  public stage: Stage = Stage.BASIC;
  public cardType: CardType[] = [D];
  public hp: number = 190;
  public weakness = [{ type: G }];
  public retreat = [C];

  public powers = [
    {
      name: 'Hidden Claw',
      powerType: PowerType.ABILITY,
      text: "When you play this Pokémon from your hand onto your Bench during your turn, you may discard a Pokémon Tool from a Pokémon (yours or your opponent's).",
    },
  ];

  public attacks = [
    {
      name: 'Shadow Ripper',
      cost: [D, C, C],
      damage: 110,
      text: 'You may put this Pokémon and all attached cards into your hand.',
    },
  ];

  public regulationMark: string = 'E';
  public set: string = 'CRE';
  public setNumber: string = '104';
  public cardImage: string = 'assets/cardback.png';
  public name: string = 'Liepard V';
  public fullName: string = 'Liepard V CRE';

  public wantsToShadowRipper: boolean = false;

  public reduceEffect(store: StoreLike, state: State, effect: Effect): State {
    // Ability: Hidden Claw
    // Ref: set-rebel-clash/eldegoss-v.ts (PlayPokemonEffect trigger when played from hand to bench)
    if (effect instanceof PlayPokemonEffect && effect.pokemonCard === this) {
      const player = effect.player;
      const opponent = StateUtils.getOpponent(state, player);

      if (IS_ABILITY_BLOCKED(store, state, player, this)) {
        return state;
      }

      // Collect all Pokemon with tools from both sides
      const hasPokemonWithTools = (() => {
        let found = false;
        player.forEachPokemon(PlayerType.BOTTOM_PLAYER, (cardList) => {
          if (cardList.tools.length > 0) found = true;
        });
        opponent.forEachPokemon(PlayerType.TOP_PLAYER, (cardList) => {
          if (cardList.tools.length > 0) found = true;
        });
        return found;
      })();

      if (!hasPokemonWithTools) {
        return state;
      }

      CONFIRMATION_PROMPT(store, state, player, (result) => {
        if (!result) return;

        // Block Pokemon without tools
        const blocked: CardTarget[] = [];
        player.forEachPokemon(PlayerType.BOTTOM_PLAYER, (cardList, _card, target) => {
          if (cardList.tools.length === 0) blocked.push(target);
        });
        opponent.forEachPokemon(PlayerType.TOP_PLAYER, (cardList, _card, target) => {
          if (cardList.tools.length === 0) blocked.push(target);
        });

        store.prompt(
          state,
          new ChoosePokemonPrompt(
            player.id,
            GameMessage.CHOOSE_POKEMON_TO_DISCARD_CARDS,
            PlayerType.ANY,
            [SlotType.ACTIVE, SlotType.BENCH],
            { allowCancel: false, min: 1, max: 1, blocked },
          ),
          (selected: PokemonCardList[] | null) => {
            const targets: PokemonCardList[] = selected || [];
            if (targets.length === 0) return;

            const target = targets[0];
            if (target.tools.length > 0) {
              // Find which player owns this target to discard tool to correct discard pile
              const targetOwner = StateUtils.findOwner(state, target);
              MOVE_CARDS(store, state, target, targetOwner.discard, { cards: [target.tools[0]], sourceCard: this });
            }
          },
        );
      });
    }

    // Attack 1: Shadow Ripper
    // Ref: set-chilling-reign/shaymin.ts (Sky Return - PUT_THIS_POKEMON_AND_ALL_ATTACHED_CARDS_INTO_YOUR_HAND with AfterAttackEffect)
    if (WAS_ATTACK_USED(effect, 0, this)) {
      this.wantsToShadowRipper = true;
    }

    if (effect instanceof AfterAttackEffect && this.wantsToShadowRipper) {
      this.wantsToShadowRipper = false;
      CONFIRMATION_PROMPT(store, state, effect.player, (result) => {
        if (result) {
          PUT_THIS_POKEMON_AND_ALL_ATTACHED_CARDS_INTO_YOUR_HAND(store, state, effect);
        }
      });
    }

    if (effect instanceof EndTurnEffect) {
      this.wantsToShadowRipper = false;
    }

    return state;
  }
}
