// This file was auto-generated by the card stub generator.
// Card effects were implemented by an agent.
// If you have any questions or feedback, reach out to @C4 in the discord.

import { Attack, PokemonCard } from '../../../game';
import { CardTag, CardType, TrainerType } from '../../../game/store/card/card-types';
import { TrainerCard } from '../../../game/store/card/trainer-card';
import { CheckProvidedEnergyEffect } from '../../../game/store/effects/check-effects';
import { CheckPokemonAttacksEffect } from '../../../game/store/effects/check-effects';
import { Effect } from '../../../game/store/effects/effect';
import { AttackEffect } from '../../../game/store/effects/game-effects';

import { IS_TOOL_BLOCKED } from '../../../game/store/prefabs/prefabs';

import { State } from '../../../game/store/state/state';
import { StoreLike } from '../../../game/store/store-like';

export class RapidStrikeScrollOfTheSkies extends TrainerCard {
  protected _trainerType: TrainerType = TrainerType.TOOL;
  protected _tags = [CardTag.RAPID_STRIKE];
  public regulationMark: string = 'E';
  public set: string = 'CRE';
  public setNumber: string = '151';
  public cardImage: string = 'assets/cardback.png';
  public name: string = 'Rapid Strike Scroll of the Skies';
  public fullName: string = 'Rapid Strike Scroll of the Skies CRE';
  public text: string =
    "Attach a Pokémon Tool to 1 of your Pokémon that doesn't already have a Pokémon Tool attached. The Rapid Strike Pokémon this card is attached to can use the attack on this card. (You still need the necessary Energy to use this attack.) You may play any number of Item cards during your turn.";

  // Attack granted to Rapid Strike Pokemon: Gravdrop
  // Ref: https://bulbapedia.bulbagarden.net/wiki/Rapid_Strike_Scroll_of_the_Skies_(Chilling_Reign_151)
  public attacks: Attack[] = [
    {
      name: 'Gravdrop',
      cost: [CardType.LIGHTNING, CardType.COLORLESS],
      damage: 10,
      damageCalculation: '+',
      text: "This attack does 50 more damage for each Energy attached to your opponent's Active Pokémon.",
    },
  ];

  // Ref: set-battle-styles/single-strike-scroll-of-scorn.ts (tool attack pattern)
  public reduceEffect(store: StoreLike, state: State, effect: Effect): State {
    // Add attack to Rapid Strike Pokemon that has this tool
    if (
      effect instanceof CheckPokemonAttacksEffect &&
      effect.player.active.getPokemonCard()?.tools.includes(this) &&
      !effect.attacks.includes(this.attacks[0])
    ) {
      if (IS_TOOL_BLOCKED(store, state, effect.player, this)) {
        return state;
      }

      effect.attacks.push(this.attacks[0]);
    }

    // Gravdrop: only usable by Rapid Strike Pokemon with this tool
    if (effect instanceof AttackEffect && effect.attack === this.attacks[0]) {
      const player = effect.player;

      if (
        !player.active.cards.some((c) => c instanceof PokemonCard && c.hasTag(CardTag.RAPID_STRIKE))
      ) {
        return state;
      }

      // Count all Energy attached to opponent's Active Pokemon (use reduce to count units, not cards)
      const checkEnergy = new CheckProvidedEnergyEffect(effect.opponent, effect.opponent.active);
      store.reduceEffect(state, checkEnergy);
      const energyCount = checkEnergy.energyMap.reduce((sum, em) => sum + em.provides.length, 0);
      effect.damage += energyCount * 50;
    }

    return state;
  }
}
