// This file was auto-generated by the card stub generator.
// Card effects were implemented by an agent.
// If you have any questions or feedback, reach out to @C4 in the discord.

import { PokemonCard } from '../../../game/store/card/pokemon-card';
import { Stage, CardType } from '../../../game/store/card/card-types';
import { GameMessage, StoreLike, State } from '../../../game';
import { Effect } from '../../../game/store/effects/effect';
import { ChooseCardsPrompt } from '../../../game/store/prompts/choose-cards-prompt';
import {WAS_ATTACK_USED, MULTIPLE_COIN_FLIPS_PROMPT, MOVE_CARDS } from '../../../game/store/prefabs/prefabs';

export class Slurpuff extends PokemonCard {
  public stage: Stage = Stage.STAGE_1;
  public evolvesFrom: string = 'Swirlix';
  public cardType: CardType[] = [P];
  public hp: number = 110;
  public weakness = [{ type: M }];
  public retreat = [C, C];

  public attacks = [{
    name: 'Follow the Scent',
    cost: [C, C],
    damage: 0,
    text: 'Flip 3 coins. Put a number of cards up to the number of heads from your discard pile into your hand.'
  }, {
    name: 'Fairy Wind',
    cost: [C, C, C],
    damage: 80,
    text: ''
  }];

  public regulationMark: string = 'E';

  public set: string = 'CRE';
  public setNumber: string = '68';
  public cardImage: string = 'assets/cardback.png';
  public name: string = 'Slurpuff';
  public fullName: string = 'Slurpuff CRE';

  public reduceEffect(store: StoreLike, state: State, effect: Effect): State {
    // Attack 1: Follow the Scent
    // Ref: set-mysterious-treasures/time-space-distortion.ts (Flip 3 coins, retrieve cards from discard)
    if (WAS_ATTACK_USED(effect, 0, this)) {
      const player = effect.player;

      if (player.discard.cards.length === 0) {
        return state;
      }

      MULTIPLE_COIN_FLIPS_PROMPT(store, state, player, 3, results => {
        const headsCount = results.filter(r => r).length;

        if (headsCount === 0) {
          return state;
        }

        const maxCards = Math.min(player.discard.cards.length, headsCount);
        store.prompt(state, new ChooseCardsPrompt(
          player,
          GameMessage.CHOOSE_CARD_TO_HAND,
          player.discard,
          {},
          { min: 0, max: maxCards, allowCancel: false }
        ), selected => {
          if (selected && selected.length > 0) {
            MOVE_CARDS(store, state, player.discard, player.hand, { cards: selected, sourceCard: this });
          }
        });
      });
    }

    return state;
  }
}
