// This file was auto-generated by the card stub generator.
// Card effects were implemented by an agent.
// If you have any questions or feedback, reach out to @C4 in the discord.

import { PokemonCard } from '../../../game/store/card/pokemon-card';
import { Stage, CardType, CardTag } from '../../../game/store/card/card-types';
import { StoreLike, State, StateUtils } from '../../../game';
import { Effect } from '../../../game/store/effects/effect';
import {WAS_ATTACK_USED, MOVE_CARDS } from '../../../game/store/prefabs/prefabs';

export class Thwackey extends PokemonCard {
  protected _tags = [CardTag.RAPID_STRIKE];
  public stage: Stage = Stage.STAGE_1;
  public evolvesFrom: string = 'Grookey';
  public cardType: CardType[] = [G];
  public hp: number = 100;
  public weakness = [{ type: R }];
  public retreat = [C, C];

  public attacks = [
    {
      name: 'Knock Off',
      cost: [G, C],
      damage: 30,
      text: "Discard a random card from your opponent's hand.",
    },
  ];

  public regulationMark: string = 'E';
  public set: string = 'CRE';
  public setNumber: string = '17';
  public cardImage: string = 'assets/cardback.png';
  public name: string = 'Thwackey';
  public fullName: string = 'Thwackey CRE';

  public reduceEffect(store: StoreLike, state: State, effect: Effect): State {
    // Attack 1: Knock Off
    // Ref: AGENTS-patterns.md (discard a random card from opponent's hand)
    if (WAS_ATTACK_USED(effect, 0, this)) {
      const player = effect.player;
      const opponent = StateUtils.getOpponent(state, player);

      if (opponent.hand.cards.length > 0) {
        const randomIndex = Math.floor(Math.random() * opponent.hand.cards.length);
        const randomCard = opponent.hand.cards[randomIndex];
        MOVE_CARDS(store, state, opponent.hand, opponent.discard, { cards: [randomCard], sourceCard: this });
      }
    }

    return state;
  }
}
