// This file was auto-generated by the card stub generator.
// Card effects were implemented by an agent.
// If you have any questions or feedback, reach out to @C4 in the discord.

import { PokemonCard } from '../../../game/store/card/pokemon-card';
import { Stage, CardType, SuperType, EnergyType } from '../../../game/store/card/card-types';
import { StoreLike, State, EnergyCard, ChooseCardsPrompt, GameMessage, PlayerType } from '../../../game';
import { Effect } from '../../../game/store/effects/effect';
import { CheckProvidedEnergyEffect } from '../../../game/store/effects/check-effects';
import {WAS_ATTACK_USED, MOVE_CARDS } from '../../../game/store/prefabs/prefabs';
import { YOUR_OPPPONENTS_ACTIVE_POKEMON_IS_NOW_CONFUSED } from '../../../game/store/prefabs/attack-effects';

export class Weezing extends PokemonCard {
  public stage: Stage = Stage.STAGE_1;
  public evolvesFrom: string = 'Koffing';
  public cardType: CardType[] = [D];
  public hp: number = 130;
  public weakness = [{ type: F }];
  public retreat = [C, C];

  public attacks = [
    {
      name: 'Mixin\' Toxin',
      cost: [D],
      damage: 0,
      text: 'Your opponent\'s Active Pokémon is now Confused. Attach a [D] Energy card from your discard pile to this Pokémon.'
    },
    {
      name: 'Smog Burst',
      cost: [D, C],
      damage: 20,
      damageCalculation: '+',
      text: 'This attack does 20 more damage for each [D] Energy attached to all of your Pokémon.'
    }
  ];

  public regulationMark: string = 'E';
  public set: string = 'CRE';
  public setNumber: string = '95';
  public cardImage: string = 'assets/cardback.png';
  public name: string = 'Weezing';
  public fullName: string = 'Weezing CRE';

  public reduceEffect(store: StoreLike, state: State, effect: Effect): State {
    // Attack 1: Mixin' Toxin
    // Ref: set-battle-styles/cacturne.ts (CheckProvidedEnergyEffect for Dark energy),
    //      set-rebel-clash/sandaconda-v.ts (attach energy from discard to this Pokemon),
    //      AGENTS-patterns.md (YOUR_OPPPONENTS_ACTIVE_POKEMON_IS_NOW_CONFUSED)
    if (WAS_ATTACK_USED(effect, 0, this)) {
      const player = effect.player;

      YOUR_OPPPONENTS_ACTIVE_POKEMON_IS_NOW_CONFUSED(store, state, effect);

      // Find a [D] Energy in discard
      const darkEnergy = player.discard.cards.filter(c =>
        c instanceof EnergyCard &&
        c.energyType === EnergyType.BASIC &&
        c.name === 'Darkness Energy'
      );

      if (darkEnergy.length === 0) { return state; }

      return store.prompt(state, new ChooseCardsPrompt(
        player,
        GameMessage.CHOOSE_CARD_TO_ATTACH,
        player.discard,
        { superType: SuperType.ENERGY, energyType: EnergyType.BASIC, name: 'Darkness Energy' },
        { min: 1, max: 1, allowCancel: false }
      ), selected => {
        if (selected && selected.length > 0) {
          MOVE_CARDS(store, state, player.discard, player.active, { cards: [selected[0]], sourceCard: this });
        }
      });
    }

    // Attack 2: Smog Burst
    // Ref: set-battle-styles/kingdra.ts (count energy across all my Pokemon using forEachPokemon + CheckProvidedEnergyEffect)
    if (WAS_ATTACK_USED(effect, 1, this)) {
      const player = effect.player;

      let darkEnergyCount = 0;
      player.forEachPokemon(PlayerType.BOTTOM_PLAYER, (cardList) => {
        const checkEnergy = new CheckProvidedEnergyEffect(player, cardList);
        store.reduceEffect(state, checkEnergy);
        darkEnergyCount += checkEnergy.energyMap.reduce((sum, em) => {
          return sum + em.provides.filter(t => t === CardType.DARK || t === CardType.ANY).length;
        }, 0);
      });

      effect.damage += darkEnergyCount * 20;
    }

    return state;
  }
}
