// This file was auto-generated by the card stub generator.
// Card effects were implemented by an agent.
// If you have any questions or feedback, reach out to @C4 in the discord.

import { TrainerCard } from '../../../game/store/card/trainer-card';
import { EnergyType, TrainerType } from '../../../game/store/card/card-types';
import { StoreLike, State, StateUtils } from '../../../game';
import { EnergyCard } from '../../../game/store/card/energy-card';
import { DealDamageEffect } from '../../../game/store/effects/attack-effects';
import { Effect } from '../../../game/store/effects/effect';
import { IS_TOOL_BLOCKED } from '../../../game/store/prefabs/prefabs';

export class AssaultVest extends TrainerCard {
  protected _trainerType: TrainerType = TrainerType.TOOL;
  public set: string = 'BKT';
  public setNumber: string = '133';
  public cardImage: string = 'assets/cardback.png';
  public name: string = 'Assault Vest';
  public fullName: string = 'Assault Vest BKT';
  public text: string =
    "Any damage done to the Pokémon this card is attached to by attacks from your opponent's Pokémon that have any Special Energy attached to them is reduced by 40 (after applying Weakness and Resistance).";

  // Ref: set-x-and-y/hard-charm.ts (Tool damage reduction with IS_TOOL_BLOCKED + DealDamageEffect)
  public reduceEffect(store: StoreLike, state: State, effect: Effect): State {
    if (effect instanceof DealDamageEffect && effect.target.tools.includes(this)) {
      const player = StateUtils.findOwner(state, effect.target);

      if (IS_TOOL_BLOCKED(store, state, player, this)) {
        return state;
      }

      // Only reduce damage from opponent's Pokemon that have Special Energy
      const opponent = StateUtils.getOpponent(state, player);
      if (effect.source === opponent.active || opponent.bench.includes(effect.source)) {
        const hasSpecialEnergy = effect.source.cards.some(
          (c) => c instanceof EnergyCard && c.energyType === EnergyType.SPECIAL,
        );

        if (hasSpecialEnergy) {
          effect.damage = Math.max(0, effect.damage - 40);
        }
      }
    }

    return state;
  }
}
