// This file was auto-generated by the card stub generator.
// Card effects were implemented by an agent.
// If you have any questions or feedback, reach out to @C4 in the discord.

import { PokemonCard } from '../../../game/store/card/pokemon-card';
import { Stage, CardType } from '../../../game/store/card/card-types';
import { StoreLike, State } from '../../../game';
import { EnergyCard } from '../../../game/store/card/energy-card';
import { Effect } from '../../../game/store/effects/effect';
import {WAS_ATTACK_USED, MOVE_CARDS } from '../../../game/store/prefabs/prefabs';

export class Quilava extends PokemonCard {
  public stage: Stage = Stage.STAGE_1;
  public evolvesFrom: string = 'Cyndaquil';
  public cardType: CardType[] = [R];
  public hp: number = 80;
  public weakness = [{ type: W }];
  public retreat = [C];

  public attacks = [
    {
      name: 'Mini Eruption',
      cost: [R, C],
      damage: 30,
      damageCalculation: '+',
      text: 'Discard the top card of your deck. If that card is an Energy card, this attack does 30 more damage.'
    }
  ];

  public set: string = 'BKT';
  public setNumber: string = '19';
  public cardImage: string = 'assets/cardback.png';
  public name: string = 'Quilava';
  public fullName: string = 'Quilava BKT';

  public reduceEffect(store: StoreLike, state: State, effect: Effect): State {
    // Attack 1: Mini Eruption
    // Ref: set-ancient-origins/lugia-ex.ts (conditional damage with deck checking)
    if (WAS_ATTACK_USED(effect, 0, this)) {
      const player = effect.player;

      if (player.deck.cards.length > 0) {
        const topCard = player.deck.cards[0];
        MOVE_CARDS(store, state, player.deck, player.discard, { cards: [topCard], sourceCard: this });

        if (topCard instanceof EnergyCard) {
          effect.damage += 30;
        }
      }
    }

    return state;
  }
}
