// This file was auto-generated by the card stub generator.
// Card effects were implemented by an agent.
// If you have any questions or feedback, reach out to @C4 in the discord.

import { PokemonCard } from '../../../game/store/card/pokemon-card';
import { Stage, CardType, EnergyType, SuperType } from '../../../game/store/card/card-types';
import { EnergyCard } from '../../../game/store/card/energy-card';
import { GameMessage, StoreLike, State } from '../../../game';
import { Effect } from '../../../game/store/effects/effect';
import {WAS_ATTACK_USED, MOVE_CARDS } from '../../../game/store/prefabs/prefabs';
import { ChooseCardsPrompt } from '../../../game/store/prompts/choose-cards-prompt';

export class Simipour extends PokemonCard {
  public stage: Stage = Stage.STAGE_1;
  public evolvesFrom: string = 'Panpour';
  public cardType: CardType[] = [W];
  public hp: number = 90;
  public weakness = [{ type: G }];
  public retreat = [C];

  public attacks = [
    {
      name: 'Green Fling',
      cost: [C],
      damage: 0,
      text: 'Put 3 [G] Energy from your discard pile into your hand.'
    },
    {
      name: 'Hand Fling',
      cost: [C, C],
      damage: 0,
      text: 'This attack does 10 damage times the number of cards in your hand.'
    }
  ];

  public set: string = 'BKT';
  public setNumber: string = '42';
  public cardImage: string = 'assets/cardback.png';
  public name: string = 'Simipour';
  public fullName: string = 'Simipour BKT';

  public reduceEffect(store: StoreLike, state: State, effect: Effect): State {
    // Attack 1: Green Fling
    // Ref: set-furious-fists/minun.ts (Negative Discard)
    if (WAS_ATTACK_USED(effect, 0, this)) {
      const player = effect.player;

      const blocked: number[] = [];
      player.discard.cards.forEach((card, index) => {
        if (!(card instanceof EnergyCard && card.energyType === EnergyType.BASIC && card.provides.includes(CardType.GRASS))) {
          blocked.push(index);
        }
      });

      const available = player.discard.cards.length - blocked.length;
      if (available > 0) {
        const count = Math.min(3, available);
        store.prompt(state, new ChooseCardsPrompt(
          player,
          GameMessage.CHOOSE_CARD_TO_HAND,
          player.discard,
          { superType: SuperType.ENERGY },
          { min: count, max: count, allowCancel: false, blocked }
        ), selected => {
          if (selected && selected.length > 0) {
            MOVE_CARDS(store, state, player.discard, player.hand, { cards: selected, sourceCard: this });
          }
        });
      }
    }

    // Attack 2: Hand Fling
    // Ref: AGENTS-patterns.md (damage based on hand size)
    if (WAS_ATTACK_USED(effect, 1, this)) {
      const player = effect.player;
      effect.damage = 10 * player.hand.cards.length;
    }

    return state;
  }
}
