// This file was auto-generated by the card stub generator.
// Card effects were implemented by an agent.
// If you have any questions or feedback, reach out to @C4 in the discord.

import { PokemonCard } from '../../../game/store/card/pokemon-card';
import { Stage, CardType, SuperType } from '../../../game/store/card/card-types';
import { StoreLike, State } from '../../../game';
import { Effect } from '../../../game/store/effects/effect';
import {WAS_ATTACK_USED, MOVE_CARDS } from '../../../game/store/prefabs/prefabs';
import { DISCARD_X_ENERGY_FROM_THIS_POKEMON } from '../../../game/store/prefabs/costs';
import { DISCARD_AN_ENERGY_FROM_OPPONENTS_ACTIVE_POKEMON } from '../../../game/store/prefabs/attack-effects';

export class Typhlosion extends PokemonCard {
  public stage: Stage = Stage.STAGE_2;
  public evolvesFrom: string = 'Quilava';
  public cardType: CardType[] = [R];
  public hp: number = 150;
  public weakness = [{ type: W }];
  public retreat = [C, C, C];

  public attacks = [
    {
      name: 'Massive Eruption',
      cost: [R],
      damage: 80,
      damageCalculation: 'x',
      text: 'Discard the top 5 cards of your deck. This attack does 80 damage times the number of Energy cards you discarded.'
    },
    {
      name: 'Flare Destroy',
      cost: [R, R, C],
      damage: 130,
      text: 'Discard an Energy attached to this Pokémon. Then, discard an Energy attached to your opponent\'s Active Pokémon.'
    }
  ];

  public set: string = 'BKT';
  public setNumber: string = '20';
  public cardImage: string = 'assets/cardback.png';
  public name: string = 'Typhlosion';
  public fullName: string = 'Typhlosion BKT';

  public reduceEffect(store: StoreLike, state: State, effect: Effect): State {
    // Attack 1: Massive Eruption
    // Ref: set-plasma-storm/heatmor.ts (Fiery Licks - discard top cards, count energy)
    if (WAS_ATTACK_USED(effect, 0, this)) {
      const player = effect.player;

      const cardsToDiscard = player.deck.cards.slice(0, Math.min(5, player.deck.cards.length));
      const energyCount = cardsToDiscard.filter(c => c.superType === SuperType.ENERGY).length;

      MOVE_CARDS(store, state, player.deck, player.discard, { cards: cardsToDiscard, sourceCard: this });
      effect.damage = 80 * energyCount;
    }

    // Attack 2: Flare Destroy
    // Refs: set-breakthrough/cyndaquil.ts (Ember - discard energy from self), AGENTS-patterns.md (discard opponent energy)
    if (WAS_ATTACK_USED(effect, 1, this)) {
      DISCARD_X_ENERGY_FROM_THIS_POKEMON(store, state, effect, 1);
      DISCARD_AN_ENERGY_FROM_OPPONENTS_ACTIVE_POKEMON(store, state, effect);
    }

    return state;
  }
}
