// This file was auto-generated by the card stub generator.
// Card effects were implemented by an agent.
// If you have any questions or feedback, reach out to @C4 in the discord.

import { PokemonCard } from '../../../game/store/card/pokemon-card';
import { Stage, CardType, SuperType, EnergyType } from '../../../game/store/card/card-types';
import { GameMessage, StoreLike, State, StateUtils, PlayerType, SlotType } from '../../../game';
import { EnergyCard } from '../../../game/store/card/energy-card';
import { Effect } from '../../../game/store/effects/effect';
import { AttachEnergyPrompt } from '../../../game/store/prompts/attach-energy-prompt';
import {WAS_ATTACK_USED, MOVE_CARDS } from '../../../game/store/prefabs/prefabs';
import { DISCARD_X_ENERGY_FROM_THIS_POKEMON } from '../../../game/store/prefabs/costs';

export class Blaziken extends PokemonCard {
  public stage: Stage = Stage.STAGE_2;
  public evolvesFrom: string = 'Combusken';
  public cardType: CardType[] = [R];
  public hp: number = 140;
  public weakness = [{ type: W }];
  public retreat = [C];

  public attacks = [
    {
      name: 'Spreading Flames',
      cost: [R],
      damage: 0,
      text: 'Attach 3 [R] Energy cards from your discard pile to your Pokémon in any way you like.'
    },
    {
      name: 'Heat Blow',
      cost: [R, C],
      damage: 100,
      text: 'Discard an Energy attached to this Pokémon.'
    }
  ];

  public set: string = 'PRC';
  public setNumber: string = '28';
  public cardImage: string = 'assets/cardback.png';
  public name: string = 'Blaziken';
  public fullName: string = 'Blaziken PRC';

  public reduceEffect(store: StoreLike, state: State, effect: Effect): State {
    // Attack 1: Spreading Flames
    // Ref: set-rebel-clash/coalossal.ts (Tar Generator - energy attach from discard)
    if (WAS_ATTACK_USED(effect, 0, this)) {
      const player = effect.player;

      const fireEnergyInDiscard = player.discard.cards.filter(c =>
        c instanceof EnergyCard && c.energyType === EnergyType.BASIC && c.provides.includes(CardType.FIRE)
      );

      if (fireEnergyInDiscard.length === 0) {
        return state;
      }

      const count = Math.min(3, fireEnergyInDiscard.length);

      return store.prompt(state, new AttachEnergyPrompt(
        player.id,
        GameMessage.ATTACH_ENERGY_CARDS,
        player.discard,
        PlayerType.BOTTOM_PLAYER,
        [SlotType.ACTIVE, SlotType.BENCH],
        { superType: SuperType.ENERGY, energyType: EnergyType.BASIC, name: 'Fire Energy' },
        { min: count, max: count, allowCancel: false }
      ), transfers => {
        transfers = transfers || [];
        for (const transfer of transfers) {
          const target = StateUtils.getTarget(state, player, transfer.to);
          MOVE_CARDS(store, state, player.discard, target, { cards: [transfer.card], sourceCard: this });
        }
      });
    }

    // Attack 2: Heat Blow
    // Ref: AGENTS-patterns.md (discard energy from self)
    if (WAS_ATTACK_USED(effect, 1, this)) {
      DISCARD_X_ENERGY_FROM_THIS_POKEMON(store, state, effect, 1);
    }

    return state;
  }
}
