// This file was auto-generated by the card stub generator.
// Card effects were implemented by an agent.
// If you have any questions or feedback, reach out to @C4 in the discord.

import { PokemonCard } from '../../../game/store/card/pokemon-card';
import { Stage, CardType, SuperType, EnergyType } from '../../../game/store/card/card-types';
import { Card, ConfirmPrompt, GameError, GameMessage, MoveEnergyPrompt, CardTarget, PowerType, StoreLike, State, StateUtils, PlayerType, SlotType } from '../../../game';
import { EnergyCard } from '../../../game/store/card/energy-card';
import { Effect } from '../../../game/store/effects/effect';
import { CheckProvidedEnergyEffect } from '../../../game/store/effects/check-effects';
import { DiscardCardsEffect } from '../../../game/store/effects/attack-effects';
import {WAS_ATTACK_USED, WAS_POWER_USED, IS_ABILITY_BLOCKED, ABILITY_USED, MOVE_CARDS } from '../../../game/store/prefabs/prefabs';

export class Eelektross extends PokemonCard {
  public stage: Stage = Stage.STAGE_2;
  public evolvesFrom: string = 'Eelektrik';
  public cardType: CardType[] = [L];
  public hp: number = 140;
  public weakness = [{ type: F }];
  public resistance = [{ type: M, value: -20 }];
  public retreat = [C, C, C];

  public powers = [{
    name: 'Energy Connect',
    useWhenInPlay: true,
    powerType: PowerType.ABILITY,
    text: 'As often as you like during your turn (before your attack), you may move a basic Energy attached to 1 of your Benched Pokémon to your Active Pokémon.'
  }];

  public attacks = [
    {
      name: 'Electricannon',
      cost: [L, L, C, C],
      damage: 80,
      damageCalculation: '+',
      text: 'You may discard all [L] Energy attached to this Pokémon. If you do, this attack does 50 more damage.'
    }
  ];

  public set: string = 'PRC';
  public setNumber: string = '65';
  public cardImage: string = 'assets/cardback.png';
  public name: string = 'Eelektross';
  public fullName: string = 'Eelektross PRC';

  public reduceEffect(store: StoreLike, state: State, effect: Effect): State {
    // Ability: Energy Connect
    // Ref: set-perfect-order/dewgong.ts (Wash Out - move energy from bench to active)
    if (WAS_POWER_USED(effect, 0, this)) {
      const player = effect.player;

      if (IS_ABILITY_BLOCKED(store, state, player, this)) {
        throw new GameError(GameMessage.BLOCKED_BY_EFFECT);
      }

      // Check if there's any basic Energy on benched Pokemon
      let hasBasicEnergyOnBench = false;
      player.forEachPokemon(PlayerType.BOTTOM_PLAYER, (cardList) => {
        if (cardList !== player.active) {
          const checkEnergy = new CheckProvidedEnergyEffect(player, cardList);
          store.reduceEffect(state, checkEnergy);
          if (checkEnergy.energyMap.some(em => em.card instanceof EnergyCard && em.card.energyType === EnergyType.BASIC)) {
            hasBasicEnergyOnBench = true;
          }
        }
      });

      if (!hasBasicEnergyOnBench) {
        throw new GameError(GameMessage.CANNOT_USE_POWER);
      }

      const blockedFrom: CardTarget[] = [];
      const blockedTo: CardTarget[] = [];

      player.forEachPokemon(PlayerType.BOTTOM_PLAYER, (cardList, card, target) => {
        if (cardList === player.active) {
          blockedFrom.push(target);
        } else {
          blockedTo.push(target);
        }
      });

      return store.prompt(state, new MoveEnergyPrompt(
        player.id,
        GameMessage.MOVE_ENERGY_CARDS,
        PlayerType.BOTTOM_PLAYER,
        [SlotType.ACTIVE, SlotType.BENCH],
        { superType: SuperType.ENERGY, energyType: EnergyType.BASIC },
        { allowCancel: true, min: 0, max: 1, blockedFrom, blockedTo }
      ), transfers => {
        if (transfers && transfers.length > 0) {
          for (const transfer of transfers) {
            const source = StateUtils.getTarget(state, player, transfer.from);
            MOVE_CARDS(store, state, source, player.active, { cards: [transfer.card], sourceCard: this });
          }
          ABILITY_USED(player, this);
        }
      });
    }

    // Attack 1: Electricannon
    // Ref: set-x-and-y/talonflame.ts (Flare Blitz - discard all type energy)
    if (WAS_ATTACK_USED(effect, 0, this)) {
      const player = effect.player;

      const checkEnergy = new CheckProvidedEnergyEffect(player);
      store.reduceEffect(state, checkEnergy);

      const lightningCards: Card[] = [];
      for (const em of checkEnergy.energyMap) {
        if (em.provides.some(t => t === CardType.LIGHTNING || t === CardType.ANY)) {
          lightningCards.push(em.card);
        }
      }

      if (lightningCards.length > 0) {
        state = store.prompt(state, new ConfirmPrompt(
          player.id,
          GameMessage.WANT_TO_USE_ABILITY,
        ), wantToDiscard => {
          if (wantToDiscard) {
            const discardEnergy = new DiscardCardsEffect(effect, lightningCards);
            discardEnergy.target = player.active;
            store.reduceEffect(state, discardEnergy);
            effect.damage += 50;
          }
        });
      }
    }

    return state;
  }
}
