// This file was auto-generated by the card stub generator.
// Card effects were implemented by an agent.
// If you have any questions or feedback, reach out to @C4 in the discord.

import { PokemonCard } from '../../../game/store/card/pokemon-card';
import { Stage, CardType, SuperType } from '../../../game/store/card/card-types';
import { GameMessage, StoreLike, State, StateUtils, PlayerType, SlotType } from '../../../game';
import { EnergyCard } from '../../../game/store/card/energy-card';
import { Effect } from '../../../game/store/effects/effect';
import { AttachEnergyPrompt } from '../../../game/store/prompts/attach-energy-prompt';
import {WAS_ATTACK_USED, SHUFFLE_DECK, MOVE_CARDS } from '../../../game/store/prefabs/prefabs';

export class Excadrill2 extends PokemonCard {
  public stage: Stage = Stage.STAGE_1;
  public evolvesFrom: string = 'Drilbur';
  public cardType: CardType[] = [M];
  public hp: number = 110;
  public weakness = [{ type: R }];
  public resistance = [{ type: P, value: -20 }];
  public retreat = [C, C, C];

  public attacks = [
    {
      name: 'Dredge',
      cost: [C],
      damage: 0,
      text: 'Search your deck for 2 Energy cards and attach them to this Pokémon. Shuffle your deck afterward.'
    },
    {
      name: 'Mach Claw',
      cost: [M, C, C],
      damage: 50,
      text: 'This attack\'s damage isn\'t affected by Resistance.'
    }
  ];

  public set: string = 'PRC';
  public setNumber: string = '97';
  public cardImage: string = 'assets/cardback.png';
  public name: string = 'Excadrill';
  public fullName: string = 'Excadrill PRC 97';

  public reduceEffect(store: StoreLike, state: State, effect: Effect): State {
    // Attack 1: Dredge
    // Ref: set-phantom-forces/jellicent.ts (Meddling - energy search + attach pattern)
    if (WAS_ATTACK_USED(effect, 0, this)) {
      const player = effect.player;

      const energyInDeck = player.deck.cards.filter(c => c instanceof EnergyCard);
      if (energyInDeck.length === 0) {
        return SHUFFLE_DECK(store, state, player);
      }

      const count = Math.min(2, energyInDeck.length);

      return store.prompt(state, new AttachEnergyPrompt(
        player.id,
        GameMessage.ATTACH_ENERGY_CARDS,
        player.deck,
        PlayerType.BOTTOM_PLAYER,
        [SlotType.ACTIVE],
        { superType: SuperType.ENERGY },
        { min: 0, max: count, allowCancel: false }
      ), transfers => {
        transfers = transfers || [];
        for (const transfer of transfers) {
          const target = StateUtils.getTarget(state, player, transfer.to);
          MOVE_CARDS(store, state, player.deck, target, { cards: [transfer.card], sourceCard: this });
        }
        SHUFFLE_DECK(store, state, player);
      });
    }

    // Attack 2: Mach Claw
    // Ref: set-furious-fists/breloom.ts (Sky Uppercut)
    if (WAS_ATTACK_USED(effect, 1, this)) {
      effect.ignoreResistance = true;
    }

    return state;
  }
}
