// This file was auto-generated by the card stub generator.
// Card effects were implemented by an agent.
// If you have any questions or feedback, reach out to @C4 in the discord.

import { PokemonCard } from '../../../game/store/card/pokemon-card';
import { Stage, CardType } from '../../../game/store/card/card-types';
import { ChoosePokemonPrompt, GameMessage, PlayerType, PokemonCardList, SlotType, StoreLike, State, StateUtils, CardTarget } from '../../../game';
import { Effect } from '../../../game/store/effects/effect';
import {WAS_ATTACK_USED, SELECT_PROMPT, MOVE_CARDS } from '../../../game/store/prefabs/prefabs';
import { BLOCK_RETREAT } from '../../../game/store/prefabs/effect-of-attack-prefabs';
export class MrMime extends PokemonCard {
  public stage: Stage = Stage.BASIC;
  public cardType: CardType[] = [Y];
  public hp: number = 80;
  public weakness = [{ type: M }];
  public resistance = [{ type: D, value: -20 }];
  public retreat = [C, C];

  public attacks = [
    {
      name: 'Trick',
      cost: [C],
      damage: 0,
      text: 'Move a Pokémon Tool card attached to 1 of either player\'s Pokémon to another of that player\'s Pokémon that doesn\'t already have a Pokémon Tool attached to it. If there is no Pokémon to move the Pokémon Tool card to, this attack does nothing.'
    },
    {
      name: 'Lock Up',
      cost: [Y, C],
      damage: 30,
      text: 'The Defending Pokémon can\'t retreat during your opponent\'s next turn.'
    }
  ];

  public set: string = 'PRC';
  public setNumber: string = '101';
  public cardImage: string = 'assets/cardback.png';
  public name: string = 'Mr. Mime';
  public fullName: string = 'Mr. Mime PRC';

  public reduceEffect(store: StoreLike, state: State, effect: Effect): State {
    // Attack 1: Trick
    // Ref: set-furious-fists/tool-retriever.ts (tool movement pattern)
    if (WAS_ATTACK_USED(effect, 0, this)) {
      const player = effect.player;
      const opponent = StateUtils.getOpponent(state, player);

      // Check if there is any valid move on either side
      let canMovePlayer = false;
      let canMoveOpponent = false;
      let playerToolCount = 0;
      let playerNoToolCount = 0;
      let opponentToolCount = 0;
      let opponentNoToolCount = 0;

      player.forEachPokemon(PlayerType.BOTTOM_PLAYER, (cardList) => {
        if (cardList.tools.length > 0) { playerToolCount++; } else { playerNoToolCount++; }
      });

      opponent.forEachPokemon(PlayerType.TOP_PLAYER, (cardList) => {
        if (cardList.tools.length > 0) { opponentToolCount++; } else { opponentNoToolCount++; }
      });

      canMovePlayer = playerToolCount > 0 && playerNoToolCount > 0;
      canMoveOpponent = opponentToolCount > 0 && opponentNoToolCount > 0;

      if (!canMovePlayer && !canMoveOpponent) {
        return state;
      }

      const moveToolFromSide = (sidePlayer: any, sidePlayerType: PlayerType) => {
        const blockedSources: CardTarget[] = [];
        sidePlayer.forEachPokemon(sidePlayerType, (cardList: PokemonCardList, _card: PokemonCard, target: CardTarget) => {
          if (cardList.tools.length === 0) {
            blockedSources.push(target);
          }
        });

        store.prompt(state, new ChoosePokemonPrompt(
          player.id,
          GameMessage.CHOOSE_POKEMON,
          sidePlayerType,
          [SlotType.ACTIVE, SlotType.BENCH],
          { min: 1, max: 1, allowCancel: false, blocked: blockedSources }
        ), sourceTargets => {
          if (!sourceTargets || sourceTargets.length === 0) { return; }

          const source = sourceTargets[0];
          const tool = source.tools[0];

          const blockedDest: CardTarget[] = [];
          sidePlayer.forEachPokemon(sidePlayerType, (cardList: PokemonCardList, _card: PokemonCard, target: CardTarget) => {
            if (cardList.tools.length > 0 || cardList === source) {
              blockedDest.push(target);
            }
          });

          store.prompt(state, new ChoosePokemonPrompt(
            player.id,
            GameMessage.CHOOSE_POKEMON,
            sidePlayerType,
            [SlotType.ACTIVE, SlotType.BENCH],
            { min: 1, max: 1, allowCancel: false, blocked: blockedDest }
          ), destTargets => {
            if (!destTargets || destTargets.length === 0) { return; }

            const dest = destTargets[0];
            const toolIdx = source.tools.indexOf(tool);
            if (toolIdx !== -1) { source.tools.splice(toolIdx, 1); }
            MOVE_CARDS(store, state, source, dest, { cards: [tool], sourceCard: this });
            const cardIdx = dest.cards.indexOf(tool);
            if (cardIdx !== -1) { dest.cards.splice(cardIdx, 1); }
            dest.tools.push(tool);
          });
        });
      };

      if (canMovePlayer && canMoveOpponent) {
        // Let the player choose which side
        SELECT_PROMPT(store, state, player, ['Your Pokémon', 'Opponent\'s Pokémon'], choice => {
          if (choice === 0) {
            moveToolFromSide(player, PlayerType.BOTTOM_PLAYER);
          } else {
            moveToolFromSide(opponent, PlayerType.TOP_PLAYER);
          }
        });
      } else if (canMovePlayer) {
        moveToolFromSide(player, PlayerType.BOTTOM_PLAYER);
      } else {
        moveToolFromSide(opponent, PlayerType.TOP_PLAYER);
      }
    }

    // Attack 2: Lock Up
    // Ref: set-phantom-forces/galvantula.ts (Electroweb)
    if (WAS_ATTACK_USED(effect, 1, this)) {
      BLOCK_RETREAT(store, state, effect, this);
    }
    return state;
  }
}
