// This file was auto-generated by the card stub generator.
// Card effects were implemented by an agent.
// If you have any questions or feedback, reach out to @C4 in the discord.

import { PokemonCard } from '../../../game/store/card/pokemon-card';
import { Stage, CardType, SuperType } from '../../../game/store/card/card-types';
import { PowerType, StoreLike, State, GameMessage, PlayerType } from '../../../game';
import { Effect } from '../../../game/store/effects/effect';
import { EvolveEffect } from '../../../game/store/effects/game-effects';
import { Card } from '../../../game/store/card/card';
import { ChooseCardsPrompt } from '../../../game/store/prompts/choose-cards-prompt';
import { ConfirmPrompt } from '../../../game/store/prompts/confirm-prompt';
import {ADD_MARKER, HAS_MARKER, IS_ABILITY_BLOCKED, REMOVE_MARKER_AT_END_OF_TURN, SHUFFLE_DECK, MOVE_CARDS } from '../../../game/store/prefabs/prefabs';

export class Eevee extends PokemonCard {
  public stage: Stage = Stage.BASIC;
  public cardType: CardType[] = [C];
  public hp: number = 50;
  public weakness = [{ type: F }];
  public retreat = [C];

  public powers = [{
    name: 'Resonant Evolution',
    powerType: PowerType.ABILITY,
    text: 'Once during your turn, when you play a Pokémon from your hand to evolve 1 of your other Eevee, you may search your deck for a card that evolves from this Pokémon and put it onto this Pokémon to evolve it. Then, shuffle your deck.'
  }];

  public attacks = [
    {
      name: 'Tackle',
      cost: [C, C],
      damage: 20,
      text: ''
    }
  ];

  public readonly RESONANT_EVOLUTION_MARKER = 'EEVEE_ASR_RESONANT_EVOLUTION_MARKER';

  public regulationMark: string = 'F';
  public set: string = 'ASR';
  public setNumber: string = '119';
  public cardImage: string = 'assets/cardback.png';
  public name: string = 'Eevee';
  public fullName: string = 'Eevee ASR 119';

  public reduceEffect(store: StoreLike, state: State, effect: Effect): State {
    // Ability: Resonant Evolution
    // Triggered when another Eevee evolves - we may search deck for a card that evolves from this Eevee
    // Ref: set-journey-together/lycanroc.ts (EvolveEffect + PowerEffect ability-blocked check + ConfirmPrompt)
    // Ref: set-furious-fists/eevee.ts (search for Eevee evolution + SHUFFLE_DECK)
    if (effect instanceof EvolveEffect
      && effect.player !== undefined
      && effect.pokemonCard.evolvesFrom === 'Eevee'
      && !effect.target.cards.includes(this)) {
      // Another Eevee is evolving; this Eevee may also evolve
      const player = effect.player;

      // Once per turn enforcement
      if (HAS_MARKER(this.RESONANT_EVOLUTION_MARKER, player, this)) {
        return state;
      }

      // Check if ability is blocked
      if (IS_ABILITY_BLOCKED(store, state, player, this)) {
        return state;
      }

      // Find this Eevee in play
      let thisEeveeFound = false;
      player.forEachPokemon(PlayerType.BOTTOM_PLAYER, (cardList) => {
        if (cardList.getPokemonCard() === this) {
          thisEeveeFound = true;
        }
      });

      if (!thisEeveeFound) {
        return state;
      }

      if (player.deck.cards.length === 0) {
        return state;
      }

      store.prompt(state, new ConfirmPrompt(
        player.id,
        GameMessage.WANT_TO_USE_ABILITY,
      ), wantToUse => {
        if (!wantToUse) {
          return;
        }

        ADD_MARKER(this.RESONANT_EVOLUTION_MARKER, player, this);

        let cards: Card[] = [];
        store.prompt(state, new ChooseCardsPrompt(
          player,
          GameMessage.CHOOSE_CARD_TO_EVOLVE,
          player.deck,
          { superType: SuperType.POKEMON, evolvesFrom: 'Eevee' },
          { min: 0, max: 1, allowCancel: true }
        ), selected => {
          cards = selected || [];

          if (cards.length > 0) {
            const evolutionCard = cards[0];
            // Find this Eevee's cardList and evolve it
            player.forEachPokemon(PlayerType.BOTTOM_PLAYER, (cardList) => {
              if (cardList.getPokemonCard() === this) {
                MOVE_CARDS(store, state, player.deck, cardList, { cards: [evolutionCard], sourceCard: this });
                cardList.clearEffects();
                cardList.pokemonPlayedTurn = state.turn;
              }
            });
          }

          SHUFFLE_DECK(store, state, player);
        });
      });
    }

    REMOVE_MARKER_AT_END_OF_TURN(effect, this.RESONANT_EVOLUTION_MARKER, this);

    return state;
  }
}
