// This file was auto-generated by the card stub generator.
// Card effects were implemented by an agent.
// If you have any questions or feedback, reach out to @C4 in the discord.

import { PokemonCard } from '../../../game/store/card/pokemon-card';
import { Stage, CardType, SuperType, EnergyType } from '../../../game/store/card/card-types';
import { PowerType, StoreLike, State, GameMessage, GameError, StateUtils } from '../../../game';
import { EnergyCard } from '../../../game/store/card/energy-card';
import { Effect } from '../../../game/store/effects/effect';
import { ChooseCardsPrompt } from '../../../game/store/prompts/choose-cards-prompt';
import {WAS_ATTACK_USED, WAS_POWER_USED, IS_ABILITY_BLOCKED, ABILITY_USED, USE_ABILITY_ONCE_PER_TURN, REMOVE_MARKER_AT_END_OF_TURN, ADD_BURN_TO_PLAYER_ACTIVE, ADD_CONFUSION_TO_PLAYER_ACTIVE, MOVE_CARDS } from '../../../game/store/prefabs/prefabs';
import { BLOCK_RETREAT } from '../../../game/store/prefabs/effect-of-attack-prefabs';
export class HisuianTyphlosion extends PokemonCard {
  public stage: Stage = Stage.STAGE_2;
  public evolvesFrom: string = 'Quilava';
  public cardType: CardType[] = [P];
  public hp: number = 150;
  public weakness = [{ type: D }];
  public resistance = [{ type: F, value: -30 }];
  public retreat = [C];

  public powers = [{
    name: 'Supernatural Orb',
    useWhenInPlay: true,
    powerType: PowerType.ABILITY,
    text: 'You must discard a [P] Energy card from your hand in order to use this Ability. Once during your turn, you may make your opponent\'s Active Pokémon Burned and Confused.'
  }];

  public attacks = [
    {
      name: 'Shadow Bind',
      cost: [P, C],
      damage: 90,
      text: 'During your opponent\'s next turn, the Defending Pokémon can\'t retreat.'
    }
  ];

  public regulationMark: string = 'F';
  public set: string = 'ASR';
  public setNumber: string = '52';
  public cardImage: string = 'assets/cardback.png';
  public name: string = 'Hisuian Typhlosion';
  public fullName: string = 'Hisuian Typhlosion ASR 52';

  public readonly SUPERNATURAL_ORB_MARKER = 'HISUIAN_TYPHLOSION_ASR_SUPERNATURAL_ORB_MARKER';

  public reduceEffect(store: StoreLike, state: State, effect: Effect): State {
    // Ability: Supernatural Orb
    // Ref: set-forbidden-light/volcanion.ts (Jet Geyser - discard energy from hand, once per turn, IS_ABILITY_BLOCKED check)
    if (WAS_POWER_USED(effect, 0, this)) {
      const player = effect.player;
      const opponent = StateUtils.getOpponent(state, player);

      if (IS_ABILITY_BLOCKED(store, state, player, this)) {
        throw new GameError(GameMessage.BLOCKED_BY_EFFECT);
      }

      // Check if player has a Psychic Energy in hand
      const psychicInHand = player.hand.cards.some(c =>
        c instanceof EnergyCard && c.energyType === EnergyType.BASIC && c.provides.includes(CardType.PSYCHIC)
      );

      if (!psychicInHand) {
        throw new GameError(GameMessage.CANNOT_USE_POWER);
      }

      USE_ABILITY_ONCE_PER_TURN(player, this.SUPERNATURAL_ORB_MARKER, this);
      ABILITY_USED(player, this);

      // Discard a Psychic Energy from hand
      const blocked: number[] = [];
      player.hand.cards.forEach((card, index) => {
        if (!(card instanceof EnergyCard) || card.energyType !== EnergyType.BASIC || !card.provides.includes(CardType.PSYCHIC)) {
          blocked.push(index);
        }
      });

      store.prompt(state, new ChooseCardsPrompt(
        player,
        GameMessage.CHOOSE_CARD_TO_DISCARD,
        player.hand,
        { superType: SuperType.ENERGY },
        { min: 1, max: 1, allowCancel: false, blocked }
      ), cards => {
        cards = cards || [];
        cards.forEach(card => {
          MOVE_CARDS(store, state, player.hand, player.discard, { cards: [card], sourceCard: this });
        });

        // Make opponent's Active Pokémon Burned and Confused
        ADD_BURN_TO_PLAYER_ACTIVE(store, state, opponent, this);
        ADD_CONFUSION_TO_PLAYER_ACTIVE(store, state, opponent, this);
      });
    }

    REMOVE_MARKER_AT_END_OF_TURN(effect, this.SUPERNATURAL_ORB_MARKER, this);

    // Attack 1: Shadow Bind
    // Ref: set-astral-radiance/hisuian-overqwil.ts (Pinning - BLOCK_RETREAT pattern)
    if (WAS_ATTACK_USED(effect, 0, this)) {
      return BLOCK_RETREAT(store, state, effect, this);
    }
    return state;
  }
}
