// This file was auto-generated by the card stub generator.
// Card effects were implemented by an agent.
// If you have any questions or feedback, reach out to @C4 in the discord.

import {ADD_CONFUSION_TO_PLAYER_ACTIVE, AFTER_ATTACK, SHOW_CARDS_TO_PLAYER, SHUFFLE_DECK, WAS_ATTACK_USED, MOVE_CARDS } from '../../../game/store/prefabs/prefabs';
import { CardType, Stage } from '../../../game/store/card/card-types';
import { StateUtils } from '../../../game/store/state-utils';
import { ChooseCardsPrompt } from '../../../game/store/prompts/choose-cards-prompt';
import { GameMessage } from '../../../game/game-message';
import { PokemonCard } from '../../../game/store/card/pokemon-card';
import { Effect } from '../../../game/store/effects/effect';
import { State, StoreLike } from '../../../game';
export class Mismagius extends PokemonCard {
  public stage: Stage = Stage.STAGE_1;
  public evolvesFrom: string = 'Misdreavus';
  public cardType: CardType[] = [P];
  public hp: number = 90;
  public weakness = [{ type: D }];
  public resistance = [{ type: F, value: -30 }];
  public retreat = [C];

  public attacks = [
    {
      name: 'Ominous Prose',
      cost: [P],
      damage: 0,
      text: 'Your opponent reveals their hand. If they have 4 or more cards in their hand, choose all but 3, and your opponent shuffles the chosen cards into their deck.'
    },
    {
      name: 'Psybeam',
      cost: [P, C],
      damage: 50,
      text: 'Your opponent\'s Active Pokémon is now Confused.'
    }
  ];

  public regulationMark: string = 'F';
  public set: string = 'ASR';
  public setNumber: string = '59';
  public cardImage: string = 'assets/cardback.png';
  public name: string = 'Mismagius';
  public fullName: string = 'Mismagius ASR 59';

  public reduceEffect(store: StoreLike, state: State, effect: Effect): State {
    // Attack 1: Ominous Prose
    // Ref: set-furious-fists/watchog.ts (Held-Item Inspection - reveal hand, choose to shuffle)
    if (WAS_ATTACK_USED(effect, 0, this)) {
      const player = effect.player;
      const opponent = StateUtils.getOpponent(state, player);

      // Show opponent's hand to both players
      const opponentHandSnapshot = [...opponent.hand.cards];
      SHOW_CARDS_TO_PLAYER(store, state, player, opponentHandSnapshot);

      // If opponent has 4 or more cards, player chooses all but 3 to shuffle back
      if (opponent.hand.cards.length >= 4) {
        const cardsToShuffle = opponent.hand.cards.length - 3;

        store.prompt(state, new ChooseCardsPrompt(
          player,
          GameMessage.CHOOSE_CARD_TO_DECK,
          opponent.hand,
          {},
          { min: cardsToShuffle, max: cardsToShuffle, allowCancel: false }
        ), selected => {
          if (selected && selected.length > 0) {
            selected.forEach(card => {
              MOVE_CARDS(store, state, opponent.hand, opponent.deck, { cards: [card], sourceCard: this });
            });
            SHUFFLE_DECK(store, state, opponent);
          }
        });
      }
    }

    // Attack 2: Psybeam
    // Ref: set-unbroken-bonds/chatot.ts (Tone-Deaf - confused)
    if (AFTER_ATTACK(effect, 1, this)) {
      ADD_CONFUSION_TO_PLAYER_ACTIVE(store, state, effect.opponent, this);
    }

    return state;
  }
}
