// This file was auto-generated by the card stub generator.
// Card effects were implemented by an agent.
// If you have any questions or feedback, reach out to @C4 in the discord.

import { PokemonCard } from '../../../game/store/card/pokemon-card';
import { Stage, CardType } from '../../../game/store/card/card-types';
import { StoreLike, State, StateUtils, GameMessage, ConfirmPrompt, Card } from '../../../game';
import { Effect } from '../../../game/store/effects/effect';
import { DealDamageEffect } from '../../../game/store/effects/attack-effects';
import { ChooseCardsPrompt } from '../../../game/store/prompts/choose-cards-prompt';
import {WAS_ATTACK_USED, MOVE_CARDS } from '../../../game/store/prefabs/prefabs';

export class Cinccino extends PokemonCard {
  public stage: Stage = Stage.STAGE_1;
  public evolvesFrom: string = 'Minccino';
  public cardType: CardType[] = [C];
  public hp: number = 90;
  public weakness = [{ type: F }];
  public retreat = [C];

  public attacks = [
    {
      name: 'Amazing Plea',
      cost: [C],
      damage: 0,
      text: 'Choose 2 cards from your discard pile. Then, ask your opponent if you may put them into your hand. If yes, put those cards into your hand. If no, this attack does 80 damage to your opponent\'s Active Pokémon.'
    }
  ];

  public set: string = 'CIN';
  public setNumber: string = '86';
  public cardImage: string = 'assets/cardback.png';
  public name: string = 'Cinccino';
  public fullName: string = 'Cinccino CIN';

  public reduceEffect(store: StoreLike, state: State, effect: Effect): State {
    // Attack 1: Amazing Plea
    // Ref: set-burning-shadows/eelektross.ts (ConfirmPrompt pattern)
    if (WAS_ATTACK_USED(effect, 0, this)) {
      const player = effect.player;
      const opponent = StateUtils.getOpponent(state, player);

      if (player.discard.cards.length === 0) {
        return state;
      }

      const maxCards = Math.min(2, player.discard.cards.length);

      store.prompt(state, new ChooseCardsPrompt(
        player,
        GameMessage.CHOOSE_CARD_TO_HAND,
        player.discard,
        {},
        { min: maxCards, max: maxCards, allowCancel: false }
      ), (selected: Card[] | null) => {
        const cards = selected || [];

        if (cards.length === 0) {
          return;
        }

        // Ask opponent if player may put them into hand
        store.prompt(state, new ConfirmPrompt(
          opponent.id,
          GameMessage.WANT_TO_USE_ABILITY
        ), (opponentSaysYes: boolean) => {
          if (opponentSaysYes) {
            // Put the cards into player's hand
            cards.forEach(card => {
              MOVE_CARDS(store, state, player.discard, player.hand, { cards: [card], sourceCard: this });
            });
          } else {
            // Do 80 damage to opponent's Active Pokemon
            const damageEffect = new DealDamageEffect(effect, 80);
            damageEffect.target = opponent.active;
            store.reduceEffect(state, damageEffect);
          }
        });
      });
    }

    return state;
  }
}
