// This file was auto-generated by the card stub generator.
// Card effects were implemented by an agent.
// If you have any questions or feedback, reach out to @C4 in the discord.

import { PokemonCard } from '../../../game/store/card/pokemon-card';
import { Stage, CardType, SuperType } from '../../../game/store/card/card-types';
import { PowerType, StoreLike, State, GameMessage, GameError, PokemonCardList } from '../../../game';
import { Effect } from '../../../game/store/effects/effect';
import { ChooseCardsPrompt } from '../../../game/store/prompts/choose-cards-prompt';
import {WAS_POWER_USED, IS_ABILITY_BLOCKED, ABILITY_USED, USE_ABILITY_ONCE_PER_TURN, REMOVE_MARKER_AT_END_OF_TURN, SHUFFLE_DECK, MOVE_CARDS } from '../../../game/store/prefabs/prefabs';
import { StateUtils } from '../../../game/store/state-utils';

export class Karrablast extends PokemonCard {
  public stage: Stage = Stage.BASIC;
  public cardType: CardType[] = [G];
  public hp: number = 60;
  public weakness = [{ type: R }];
  public retreat = [C, C];

  public readonly SHELL_ON_MARKER = 'KARRABLAST_CIN_SHELL_ON_MARKER';

  public powers = [{
    name: 'Shell On',
    useWhenInPlay: true,
    powerType: PowerType.ABILITY,
    text: 'Once during your turn (before your attack), you may discard a Shelmet from your hand. If you do, search your deck for a card that evolves from this Pokémon and put it onto this Pokémon to evolve it. Then, shuffle your deck.'
  }];

  public attacks = [
    {
      name: 'Peck',
      cost: [C, C, C],
      damage: 30,
      text: ''
    }
  ];

  public set: string = 'CIN';
  public setNumber: string = '7';
  public cardImage: string = 'assets/cardback.png';
  public name: string = 'Karrablast';
  public fullName: string = 'Karrablast CIN';

  public reduceEffect(store: StoreLike, state: State, effect: Effect): State {
    // Ability: Shell On
    // Ref: set-x-and-y/inkay.ts (Upside-Down Evolution)
    if (WAS_POWER_USED(effect, 0, this)) {
      const player = effect.player;

      if (IS_ABILITY_BLOCKED(store, state, player, this)) {
        throw new GameError(GameMessage.BLOCKED_BY_EFFECT);
      }

      // Check if player has Shelmet in hand
      const shelmetInHand = player.hand.cards.filter(c =>
        c instanceof PokemonCard && c.name === 'Shelmet'
      );

      if (shelmetInHand.length === 0) {
        throw new GameError(GameMessage.CANNOT_USE_POWER);
      }

      USE_ABILITY_ONCE_PER_TURN(player, this.SHELL_ON_MARKER, this);
      ABILITY_USED(player, this);

      // Discard a Shelmet from hand
      const cardList = StateUtils.findCardList(state, this) as PokemonCardList;

      // Build blocked list for non-Shelmet cards
      const blocked: number[] = [];
      player.hand.cards.forEach((card, index) => {
        if (!(card instanceof PokemonCard) || card.name !== 'Shelmet') {
          blocked.push(index);
        }
      });

      store.prompt(state, new ChooseCardsPrompt(
        player,
        GameMessage.CHOOSE_CARD_TO_DISCARD,
        player.hand,
        { superType: SuperType.POKEMON },
        { min: 1, max: 1, allowCancel: false, blocked }
      ), selectedShelmet => {
        const discardCards = selectedShelmet || [];
        discardCards.forEach(card => {
          MOVE_CARDS(store, state, player.hand, player.discard, { cards: [card], sourceCard: this });
        });

        // Search deck for a card that evolves from this Pokemon
        const evolveBlocked: number[] = [];
        player.deck.cards.forEach((card, index) => {
          if (!(card instanceof PokemonCard) || card.evolvesFrom !== 'Karrablast') {
            evolveBlocked.push(index);
          }
        });

        store.prompt(state, new ChooseCardsPrompt(
          player,
          GameMessage.CHOOSE_CARD_TO_EVOLVE,
          player.deck,
          { superType: SuperType.POKEMON },
          { min: 0, max: 1, allowCancel: true, blocked: evolveBlocked }
        ), selectedEvolution => {
          if (selectedEvolution && selectedEvolution.length > 0) {
            const evolutionCard = selectedEvolution[0] as PokemonCard;
            MOVE_CARDS(store, state, player.deck, cardList, { cards: [evolutionCard], sourceCard: this });
            cardList.clearEffects();
            cardList.pokemonPlayedTurn = state.turn;
          }
          SHUFFLE_DECK(store, state, player);
        });
      });
    }

    REMOVE_MARKER_AT_END_OF_TURN(effect, this.SHELL_ON_MARKER, this);

    return state;
  }
}
