// This file was auto-generated by the card stub generator.
// Card effects were implemented by an agent.
// If you have any questions or feedback, reach out to @C4 in the discord.

import { PokemonCard } from '../../../game/store/card/pokemon-card';
import { Stage, CardType, SuperType } from '../../../game/store/card/card-types';
import { PowerType, StoreLike, State, StateUtils, GameMessage, PokemonCardList } from '../../../game';
import { Effect } from '../../../game/store/effects/effect';
import { DealDamageEffect, PutDamageEffect } from '../../../game/store/effects/attack-effects';
import { ChooseCardsPrompt } from '../../../game/store/prompts/choose-cards-prompt';
import {WAS_ATTACK_USED, IS_ABILITY_BLOCKED, SHUFFLE_DECK, MOVE_CARDS } from '../../../game/store/prefabs/prefabs';

export class Magikarp extends PokemonCard {
  public stage: Stage = Stage.BASIC;
  public cardType: CardType[] = [W];
  public hp: number = 30;
  public weakness = [{ type: L }];
  public retreat = [C];

  public powers = [{
    name: 'Submerge',
    powerType: PowerType.ABILITY,
    text: 'As long as this Pokémon is on your Bench, prevent all damage done to this Pokémon by attacks (both yours and your opponent\'s).'
  }];

  public attacks = [
    {
      name: 'Waterfall Evolution',
      cost: [W, C, C],
      damage: 0,
      text: 'Search your deck for a card that evolves from this Pokémon and put it onto this Pokémon to evolve it. Then, shuffle your deck.'
    }
  ];

  public set: string = 'CIN';
  public setNumber: string = '17';
  public cardImage: string = 'assets/cardback.png';
  public name: string = 'Magikarp';
  public fullName: string = 'Magikarp CIN';

  public reduceEffect(store: StoreLike, state: State, effect: Effect): State {
    // Ability: Submerge (passive - prevent all damage on bench)
    // Ref: set-ultra-prism/magnemite.ts (Solid Unit)
    if (effect instanceof PutDamageEffect && effect.target.cards.includes(this) && effect.target.getPokemonCard() === this) {
      const player = StateUtils.findOwner(state, effect.target);

      // Check if this Pokemon is on the bench (not active)
      if (effect.target === player.active) {
        return state;
      }

      if (IS_ABILITY_BLOCKED(store, state, player, this)) {
        return state;
      }

      effect.preventDefault = true;
      return state;
    }

    if (effect instanceof DealDamageEffect && effect.target.cards.includes(this) && effect.target.getPokemonCard() === this) {
      const player = StateUtils.findOwner(state, effect.target);

      // Check if this Pokemon is on the bench (not active)
      if (effect.target === player.active) {
        return state;
      }

      if (IS_ABILITY_BLOCKED(store, state, player, this)) {
        return state;
      }

      effect.preventDefault = true;
      return state;
    }

    // Attack 1: Waterfall Evolution
    // Ref: set-x-and-y/inkay.ts (Upside-Down Evolution - evolution search)
    if (WAS_ATTACK_USED(effect, 0, this)) {
      const player = effect.player;
      const cardList = StateUtils.findCardList(state, this) as PokemonCardList;

      const blocked: number[] = [];
      player.deck.cards.forEach((card, index) => {
        if (!(card instanceof PokemonCard) || card.evolvesFrom !== 'Magikarp') {
          blocked.push(index);
        }
      });

      store.prompt(state, new ChooseCardsPrompt(
        player,
        GameMessage.CHOOSE_CARD_TO_EVOLVE,
        player.deck,
        { superType: SuperType.POKEMON },
        { min: 0, max: 1, allowCancel: true, blocked }
      ), selected => {
        if (selected && selected.length > 0) {
          const evolutionCard = selected[0] as PokemonCard;
          MOVE_CARDS(store, state, player.deck, cardList, { cards: [evolutionCard], sourceCard: this });
          cardList.clearEffects();
          cardList.pokemonPlayedTurn = state.turn;
        }
        SHUFFLE_DECK(store, state, player);
      });
    }

    return state;
  }
}
