// This file was auto-generated by the card stub generator.
// Card effects were implemented by an agent.
// If you have any questions or feedback, reach out to @C4 in the discord.

import { PokemonCard } from '../../../game/store/card/pokemon-card';
import { Stage, CardType, SuperType, TrainerType } from '../../../game/store/card/card-types';
import { StoreLike, State, Card, GameMessage, TrainerCard } from '../../../game';
import { Effect } from '../../../game/store/effects/effect';
import { ChooseCardsPrompt } from '../../../game/store/prompts/choose-cards-prompt';
import {WAS_ATTACK_USED, MOVE_CARDS } from '../../../game/store/prefabs/prefabs';

export class Oranguru extends PokemonCard {
  public stage: Stage = Stage.BASIC;
  public cardType: CardType[] = [P];
  public hp: number = 110;
  public weakness = [{ type: P }];
  public retreat = [C, C];

  public attacks = [
    {
      name: 'Fixer of the Forest',
      cost: [P],
      damage: 0,
      text: 'Put 3 Pokémon Tool cards from your discard pile into your hand.'
    },
    {
      name: 'Zen Headbutt',
      cost: [P, C, C],
      damage: 70,
      text: ''
    }
  ];

  public set: string = 'CIN';
  public setNumber: string = '48';
  public cardImage: string = 'assets/cardback.png';
  public name: string = 'Oranguru';
  public fullName: string = 'Oranguru CIN';

  public reduceEffect(store: StoreLike, state: State, effect: Effect): State {
    // Attack 1: Fixer of the Forest
    // Ref: set-dark-explorers/cofagrigus.ts (ChooseCardsPrompt for tools)
    if (WAS_ATTACK_USED(effect, 0, this)) {
      const player = effect.player;

      // Count available Tool cards in discard
      const toolsInDiscard = player.discard.cards.filter(c =>
        c instanceof TrainerCard && c.trainerType === TrainerType.TOOL
      );

      if (toolsInDiscard.length === 0) {
        return state;
      }

      // Discard pile is public knowledge, so min should match max (up to 3)
      const count = Math.min(3, toolsInDiscard.length);

      return store.prompt(state, new ChooseCardsPrompt(
        player,
        GameMessage.CHOOSE_CARD_TO_HAND,
        player.discard,
        { superType: SuperType.TRAINER, trainerType: TrainerType.TOOL },
        { min: count, max: 3, allowCancel: false }
      ), (selected: Card[]) => {
        const cards = selected || [];
        cards.forEach(card => {
          MOVE_CARDS(store, state, player.discard, player.hand, { cards: [card], sourceCard: this });
        });
      });
    }

    return state;
  }
}
