// This file was auto-generated by the card stub generator.
// Card effects were implemented by an agent.
// If you have any questions or feedback, reach out to @C4 in the discord.

import {ADD_SLEEP_TO_PLAYER_ACTIVE, AFTER_ATTACK, WAS_ATTACK_USED, MOVE_CARDS } from '../../../game/store/prefabs/prefabs';
import { CardType, Stage, SuperType } from '../../../game/store/card/card-types';
import { StateUtils } from '../../../game/store/state-utils';
import { GameMessage } from '../../../game/game-message';
import { ChooseCardsPrompt } from '../../../game/store/prompts/choose-cards-prompt';
import { PokemonCard } from '../../../game/store/card/pokemon-card';
import { Effect } from '../../../game/store/effects/effect';
import { ShowCardsPrompt, State, StoreLike } from '../../../game';
export class Noctowl extends PokemonCard {
  public stage: Stage = Stage.STAGE_1;
  public evolvesFrom: string = 'Hoothoot';
  public cardType: CardType[] = [C];
  public hp: number = 90;
  public weakness = [{ type: L }];
  public resistance = [{ type: F, value: -20 }];
  public retreat = [C];

  public attacks = [
    {
      name: 'Hypnoblast',
      cost: [C],
      damage: 30,
      text: 'Your opponent\'s Active Pokémon is now Asleep.'
    },
    {
      name: 'Night Raid',
      cost: [C, C, C],
      damage: 70,
      text: 'Your opponent reveals their hand. Discard a Pokémon from it.'
    }
  ];

  public set: string = 'BUS';
  public setNumber: string = '107';
  public cardImage: string = 'assets/cardback.png';
  public name: string = 'Noctowl';
  public fullName: string = 'Noctowl BUS';

  public reduceEffect(store: StoreLike, state: State, effect: Effect): State {
    // Attack 1: Hypnoblast
    // Ref: set-guardians-rising/helioptile.ts (special condition)
    if (AFTER_ATTACK(effect, 0, this)) {
      ADD_SLEEP_TO_PLAYER_ACTIVE(store, state, effect.opponent, this);
    }

    // Attack 2: Night Raid
    // Ref: set-surging-sparks/rotom.ts (Crushing Pulse - reveal hand + discard)
    if (WAS_ATTACK_USED(effect, 1, this)) {
      const player = effect.player;
      const opponent = StateUtils.getOpponent(state, player);

      const pokemonInHand = opponent.hand.cards.filter(c =>
        c instanceof PokemonCard
      );

      if (pokemonInHand.length === 0) {
        // Show hand even if no Pokemon
        store.prompt(state, new ShowCardsPrompt(
          player.id,
          GameMessage.CARDS_SHOWED_BY_THE_OPPONENT,
          opponent.hand.cards
        ), () => { });
        return state;
      }

      store.prompt(state, new ShowCardsPrompt(
        player.id,
        GameMessage.CARDS_SHOWED_BY_THE_OPPONENT,
        opponent.hand.cards
      ), () => {
        store.prompt(state, new ChooseCardsPrompt(
          player,
          GameMessage.CHOOSE_CARD_TO_DISCARD,
          opponent.hand,
          { superType: SuperType.POKEMON },
          { min: 1, max: 1, allowCancel: false }
        ), selected => {
          const cards = selected || [];
          cards.forEach(card => {
            MOVE_CARDS(store, state, opponent.hand, opponent.discard, { cards: [card], sourceCard: this });
          });
        });
      });
    }

    return state;
  }
}
