// This file was auto-generated by the card stub generator.
// Card effects were implemented by an agent.
// If you have any questions or feedback, reach out to @C4 in the discord.

import { TrainerCard } from '../../game/store/card/trainer-card';
import { CardType, EnergyType, SuperType, TrainerType } from '../../game/store/card/card-types';
import {
  StoreLike,
  State,
  GameError,
  GameMessage,
  PlayerType,
  SlotType,
  StateUtils,
  EnergyCard,
  CardTarget,
} from '../../game';
import { Effect } from '../../game/store/effects/effect';
import { TrainerEffect } from '../../game/store/effects/play-card-effects';
import { AttachEnergyPrompt } from '../../game/store/prompts/attach-energy-prompt';
import { CheckPokemonTypeEffect } from '../../game/store/effects/check-effects';
import { KnockOutEffect } from '../../game/store/effects/game-effects';
import { GamePhase } from '../../game/store/state/state';
import {
  REMOVE_OPPONENT_LAST_TURN_MARKER_AT_END_OF_TURN,
  MOVE_CARDS,
} from '../../game/store/prefabs/prefabs';

function* playCard(
  next: Function,
  store: StoreLike,
  state: State,
  self: Zinnia,
  effect: TrainerEffect,
): IterableIterator<State> {
  const player = effect.player;

  // Check if KO marker is set
  if (!player.marker.hasMarker(self.ZINNIA_MARKER)) {
    throw new GameError(GameMessage.CANNOT_PLAY_THIS_CARD);
  }

  // Check if there are basic energy in hand (other than this card)
  const hasBasicEnergy = player.hand.cards.some(
    (c) => c instanceof EnergyCard && c.energyType === EnergyType.BASIC && c !== (self as any),
  );

  // Check if there is a Dragon Pokemon in play
  let hasDragon = false;
  player.forEachPokemon(PlayerType.BOTTOM_PLAYER, (cardList) => {
    const checkType = new CheckPokemonTypeEffect(cardList);
    store.reduceEffect(state, checkType);
    if (checkType.cardTypes.includes(CardType.DRAGON)) {
      hasDragon = true;
    }
  });

  if (!hasBasicEnergy || !hasDragon) {
    throw new GameError(GameMessage.CANNOT_PLAY_THIS_CARD);
  }

  // Move to supporter zone
  MOVE_CARDS(store, state, player.hand, player.supporter, {
    cards: [effect.trainerCard],
    sourceCard: self,
  });
  effect.preventDefault = true;

  // Filter slots that don't have Dragon Pokemon
  const blockedTo: CardTarget[] = [];
  player.forEachPokemon(PlayerType.BOTTOM_PLAYER, (cardList, card, target) => {
    const checkType = new CheckPokemonTypeEffect(cardList);
    store.reduceEffect(state, checkType);
    if (!checkType.cardTypes.includes(CardType.DRAGON)) {
      blockedTo.push(target);
    }
  });

  yield store.prompt(
    state,
    new AttachEnergyPrompt(
      player.id,
      GameMessage.ATTACH_ENERGY_CARDS,
      player.hand,
      PlayerType.BOTTOM_PLAYER,
      [SlotType.ACTIVE, SlotType.BENCH],
      { superType: SuperType.ENERGY, energyType: EnergyType.BASIC },
      { allowCancel: false, min: 0, max: 2, sameTarget: true, blockedTo },
    ),
    (transfers) => {
      transfers = transfers || [];
      for (const transfer of transfers) {
        const target = StateUtils.getTarget(state, player, transfer.to);
        MOVE_CARDS(store, state, player.hand, target, { cards: [transfer.card], sourceCard: self });
      }
      next();
    },
  );

  return state;
}

export class Zinnia extends TrainerCard {
  protected _trainerType: TrainerType = TrainerType.SUPPORTER;
  public set: string = 'DRM';
  public setNumber: string = '64';
  public cardImage: string = 'assets/cardback.png';
  public name: string = 'Zinnia';
  public fullName: string = 'Zinnia DRM';
  public text: string =
    "You can play this card only if 1 of your Pokémon was Knocked Out during your opponent's last turn.\n\nAttach up to 2 basic Energy cards from your hand to 1 of your Dragon Pokémon.";

  public readonly ZINNIA_MARKER = 'ZINNIA_MARKER';

  public reduceEffect(store: StoreLike, state: State, effect: Effect): State {
    // Ref: set-twilight-masquerade/hassel.ts (KnockOutEffect marker + Supporter pattern)
    if (effect instanceof TrainerEffect && effect.trainerCard === this) {
      const generator = playCard(() => generator.next(), store, state, this, effect);
      return generator.next().value;
    }

    if (effect instanceof KnockOutEffect) {
      const player = effect.player;
      const opponent = StateUtils.getOpponent(state, player);
      const duringTurn = [GamePhase.PLAYER_TURN, GamePhase.ATTACK].includes(state.phase);

      // Do not activate between turns, or when it's not opponent's turn.
      if (!duringTurn || state.players[state.activePlayer] !== opponent) {
        return state;
      }

      const cardList = StateUtils.findCardList(state, this);
      const owner = StateUtils.findOwner(state, cardList);
      if (owner === player) {
        effect.player.marker.addMarker(this.ZINNIA_MARKER, this);
      }
      return state;
    }

    REMOVE_OPPONENT_LAST_TURN_MARKER_AT_END_OF_TURN(effect, this.ZINNIA_MARKER, this);

    return state;
  }
}
