// This file was auto-generated by the card stub generator.
// Card effects were implemented by an agent.
// If you have any questions or feedback, reach out to @C4 in the discord.

import { TrainerCard } from '../../../game/store/card/trainer-card';
import { TrainerType } from '../../../game/store/card/card-types';
import { StoreLike, State, StateUtils } from '../../../game';
import { Effect } from '../../../game/store/effects/effect';
import { GameError } from '../../../game/game-error';
import { GameMessage } from '../../../game/game-message';
import { TrainerEffect } from '../../../game/store/effects/play-card-effects';
import { DRAW_CARDS } from '../../../game/store/prefabs/prefabs';

export class Brandon extends TrainerCard {
  protected _trainerType: TrainerType = TrainerType.SUPPORTER;
  public regulationMark: string = 'F';
  public set: string = 'SIT';
  public setNumber: string = '151';
  public cardImage: string = 'assets/cardback.png';
  public name: string = 'Brandon';
  public fullName: string = 'Brandon SIT 151';
  public text: string =
    "You can use this card only when it is the last card in your hand. Draw a card for each Benched Pokémon (both yours and your opponent's). You may play only 1 Supporter card during your turn.";

  public reduceEffect(store: StoreLike, state: State, effect: Effect): State {
    // Ref: set-primal-clash/archies-ace-in-the-hole.ts (last card in hand check + draw cards)
    if (effect instanceof TrainerEffect && effect.trainerCard === this) {
      const player = effect.player;
      const opponent = StateUtils.getOpponent(state, player);

      // Check if this is the last card in hand
      const otherCards = player.hand.cards.filter((c) => c !== this);
      if (otherCards.length !== 0) {
        throw new GameError(GameMessage.CANNOT_PLAY_THIS_CARD);
      }

      // Count benched Pokemon for both players
      const playerBenched = player.bench.filter((b) => b.cards.length > 0).length;
      const opponentBenched = opponent.bench.filter((b) => b.cards.length > 0).length;
      const totalBenched = playerBenched + opponentBenched;

      if (totalBenched > 0) {
        DRAW_CARDS(store, state, player, totalBenched);
      }
    }

    return state;
  }
}
