// This file was auto-generated by the card stub generator.
// Card effects were implemented by an agent.
// If you have any questions or feedback, reach out to @C4 in the discord.

import { PokemonCard } from '../../../game/store/card/pokemon-card';
import { Stage, CardType, CardTag } from '../../../game/store/card/card-types';
import {
  PowerType,
  StoreLike,
  State,
  StateUtils,
  GameError,
  GameMessage,
  PlayerType,
  SlotType,
  CardTarget,
} from '../../../game';
import { Effect } from '../../../game/store/effects/effect';
import { MoveEnergyPrompt } from '../../../game/store/prompts/move-energy-prompt';
import {WAS_ATTACK_USED,
  WAS_POWER_USED,
  IS_ABILITY_BLOCKED, MOVE_CARDS } from '../../../game/store/prefabs/prefabs';
import { EnergyCard } from '../../../game/store/card/energy-card';

export class HisuianArcanineV extends PokemonCard {
  protected _tags = [CardTag.POKEMON_V];
  public stage: Stage = Stage.BASIC;
  public cardType: CardType[] = [F];
  public hp: number = 230;
  public weakness = [{ type: G }];
  public retreat = [C, C, C];

  public powers = [
    {
      name: 'Irresistible Force',
      useWhenInPlay: true,
      powerType: PowerType.ABILITY,
      text: 'As often as you like during your turn, you may move a [F] Energy from 1 of your other Pokémon to this Pokémon.',
    },
  ];

  public attacks = [
    {
      name: 'Rock Bullet',
      cost: [C, C, C, C],
      damage: 90,
      damageCalculation: '+',
      text: 'This attack does 30 more damage for each [F] Energy attached to this Pokémon.',
    },
  ];

  public regulationMark: string = 'F';
  public set: string = 'SIT';
  public setNumber: string = '90';
  public cardImage: string = 'assets/cardback.png';
  public name: string = 'Hisuian Arcanine V';
  public fullName: string = 'Hisuian Arcanine V SIT 90';

  public reduceEffect(store: StoreLike, state: State, effect: Effect): State {
    // Ability: Irresistible Force
    // Ref: set-brilliant-stars/dusknoir.ts (Special Transfer - MoveEnergyPrompt from other Pokemon)
    if (WAS_POWER_USED(effect, 0, this)) {
      const player = effect.player;

      if (IS_ABILITY_BLOCKED(store, state, player, this)) {
        throw new GameError(GameMessage.BLOCKED_BY_EFFECT);
      }

      // Find this Pokemon's position to block it as a source
      const thisTarget: CardTarget[] = [];
      player.forEachPokemon(PlayerType.BOTTOM_PLAYER, (cardList, card, target) => {
        if (card === this) {
          thisTarget.push(target);
        }
      });

      // Build blocked map: only allow moving Fighting Energy from other Pokemon
      const blockedMap: { source: CardTarget; blocked: number[] }[] = [];
      player.forEachPokemon(PlayerType.BOTTOM_PLAYER, (cardList, card, target) => {
        // Block 'this' as a source (move from other Pokemon only)
        if (card === this) {
          return;
        }

        const blocked: number[] = [];
        cardList.cards.forEach((c, index) => {
          const isFightingEnergy =
            c instanceof EnergyCard && c.provides.includes(CardType.FIGHTING);
          if (!isFightingEnergy) {
            blocked.push(index);
          }
        });

        // Only include if there are F energy to move
        if (blocked.length !== cardList.cards.length) {
          blockedMap.push({ source: target, blocked });
        }
      });

      if (blockedMap.length === 0) {
        throw new GameError(GameMessage.CANNOT_USE_POWER);
      }

      // Block all targets except this Pokemon
      const blockedTo: CardTarget[] = [];
      player.forEachPokemon(PlayerType.BOTTOM_PLAYER, (cardList, card, target) => {
        if (card !== this) {
          blockedTo.push(target);
        }
      });

      return store.prompt(
        state,
        new MoveEnergyPrompt(
          player.id,
          GameMessage.MOVE_ENERGY_CARDS,
          PlayerType.BOTTOM_PLAYER,
          [SlotType.BENCH, SlotType.ACTIVE],
          {},
          { allowCancel: true, blockedMap, blockedTo, min: 1, max: 1 },
        ),
        (transfers) => {
          if (transfers === null || transfers.length === 0) {
            return;
          }

          for (const transfer of transfers) {
            const source = StateUtils.getTarget(state, player, transfer.from);
            const target = StateUtils.getTarget(state, player, transfer.to);
            MOVE_CARDS(store, state, source, target, { cards: [transfer.card], sourceCard: this });
          }
        },
      );
    }

    // Attack 1: Rock Bullet
    // Ref: set-astral-radiance/regigigas.ts (count energy attached to determine damage bonus)
    if (WAS_ATTACK_USED(effect, 0, this)) {
      const player = effect.player;

      // Count [F] Energy attached to this Pokemon (includes CardType.ANY for Rainbow Energy)
      let fightingCount = 0;
      player.forEachPokemon(PlayerType.BOTTOM_PLAYER, (cardList, card) => {
        if (card === this) {
          fightingCount = cardList.cards.filter(
            (c) =>
              c instanceof EnergyCard &&
              (c.provides.includes(CardType.FIGHTING) || c.provides.includes(CardType.ANY)),
          ).length;
        }
      });

      effect.damage += 30 * fightingCount;
    }

    return state;
  }
}
