// This file was auto-generated by the card stub generator.
// Card effects were implemented by an agent.
// If you have any questions or feedback, reach out to @C4 in the discord.

import { TrainerCard } from '../../../game/store/card/trainer-card';
import { TrainerType, SuperType } from '../../../game/store/card/card-types';
import { StoreLike, State, GameError, GameMessage } from '../../../game';
import { Effect } from '../../../game/store/effects/effect';
import { WAS_TRAINER_USED } from '../../../game/store/prefabs/trainer-prefabs';
import { PokemonCard } from '../../../game/store/card/pokemon-card';
import { ChooseCardsPrompt } from '../../../game/store/prompts/choose-cards-prompt';
import { MOVE_CARDS } from '../../../game/store/prefabs/prefabs';

export class ProfessorLaventon extends TrainerCard {
  protected _trainerType: TrainerType = TrainerType.SUPPORTER;
  public regulationMark: string = 'F';
  public set: string = 'SIT';
  public setNumber: string = '162';
  public cardImage: string = 'assets/cardback.png';
  public name: string = 'Professor Laventon';
  public fullName: string = 'Professor Laventon SIT 162';
  public text: string =
    'Put up to 3 Pokémon that have "Hisuian" in their names from your discard pile into your hand. You may play only 1 Supporter card during your turn.';

  public reduceEffect(store: StoreLike, state: State, effect: Effect): State {
    // Ref: set-silver-tempest/brandon.ts (WAS_TRAINER_USED Supporter pattern)
    // Ref: set-fusion-strike/virizion.ts (SEARCH_DISCARD_PILE_FOR_CARDS_TO_HAND with filter)
    if (WAS_TRAINER_USED(effect, this)) {
      const player = effect.player;

      if (player.supporterTurn > 0) {
        throw new GameError(GameMessage.SUPPORTER_ALREADY_PLAYED);
      }

      MOVE_CARDS(store, state, player.hand, player.supporter, { cards: [effect.trainerCard], sourceCard: this });

      // Find Hisuian Pokemon in discard
      const hisuianInDiscard = player.discard.cards.filter(
        (c) => c instanceof PokemonCard && c.name.includes('Hisuian'),
      );

      if (hisuianInDiscard.length === 0) {
        return state;
      }

      const maxPick = Math.min(3, hisuianInDiscard.length);

      // Build blocked array for non-Hisuian Pokemon
      const blocked: number[] = [];
      player.discard.cards.forEach((c, index) => {
        const isHisuian = c instanceof PokemonCard && c.name.includes('Hisuian');
        if (!isHisuian) {
          blocked.push(index);
        }
      });

      return store.prompt(
        state,
        new ChooseCardsPrompt(
          player,
          GameMessage.CHOOSE_CARD_TO_HAND,
          player.discard,
          { superType: SuperType.POKEMON },
          { min: 0, max: maxPick, allowCancel: false, blocked },
        ),
        (selected) => {
          const cards = selected || [];
          if (cards.length > 0) {
            MOVE_CARDS(store, state, player.discard, player.hand, { cards, sourceCard: this });
          }
        },
      );
    }

    return state;
  }
}
