// This file was auto-generated by the card stub generator.
// Card effects were implemented by an agent.
// If you have any questions or feedback, reach out to @C4 in the discord.

import {ADD_SLEEP_TO_PLAYER_ACTIVE, AFTER_ATTACK, SHUFFLE_DECK, WAS_ATTACK_USED, MOVE_CARDS } from '../../../game/store/prefabs/prefabs';
import { CardType, Stage } from '../../../game/store/card/card-types';
import { StateUtils } from '../../../game/store/state-utils';
import { GameError } from '../../../game/game-error';
import { GameMessage } from '../../../game/game-message';
import { ChoosePokemonPrompt } from '../../../game/store/prompts/choose-pokemon-prompt';
import { PokemonCard } from '../../../game/store/card/pokemon-card';
import { Effect } from '../../../game/store/effects/effect';
import { PlayerType, SlotType, State, StoreLike } from '../../../game';
export class Azelf extends PokemonCard {
  public stage: Stage = Stage.BASIC;
  public cardType: CardType[] = [P];
  public hp: number = 60;
  public weakness = [{ type: P }];
  public retreat = [C];

  public attacks = [
    {
      name: 'Psychic Abduction',
      cost: [C],
      damage: 0,
      text: 'You can use this attack only if you go second, and only on your first turn. Shuffle 1 of your opponent\'s Benched Pokémon and all cards attached to it into their deck.'
    },
    {
      name: 'Hypnoblast',
      cost: [C],
      damage: 10,
      text: 'Your opponent\'s Active Pokémon is now Asleep.'
    }
  ];

  public set: string = 'FLI';
  public setNumber: string = '43';
  public cardImage: string = 'assets/cardback.png';
  public name: string = 'Azelf';
  public fullName: string = 'Azelf FLI';

  public reduceEffect(store: StoreLike, state: State, effect: Effect): State {
    // Attack 1: Psychic Abduction
    // Refs: set-crimson-invasion/milotic.ts (TLC - shuffle benched Pokemon into deck), set-burning-shadows/wimpod.ts (first turn check)
    if (WAS_ATTACK_USED(effect, 0, this)) {
      const player = effect.player;
      const opponent = StateUtils.getOpponent(state, player);

      // Must go second and be on first turn (turn 2 = second player's first turn)
      if (state.turn !== 2) {
        throw new GameError(GameMessage.CANNOT_USE_ATTACK);
      }

      // Check if opponent has benched Pokemon
      const hasBench = opponent.bench.some(b => b.cards.length > 0);
      if (!hasBench) {
        return state;
      }

      store.prompt(state, new ChoosePokemonPrompt(
        player.id,
        GameMessage.CHOOSE_POKEMON,
        PlayerType.TOP_PLAYER,
        [SlotType.BENCH],
        { min: 1, max: 1, allowCancel: false }
      ), selected => {
        if (selected && selected.length > 0) {
          const target = selected[0];

          // Move tools first
          const tools = target.tools.slice();
          tools.forEach(tool => {
            MOVE_CARDS(store, state, target, opponent.deck, { cards: [tool], sourceCard: this });
          });

          // Move all cards (Pokemon + energy)
          const cards = target.cards.slice();
          cards.forEach(card => {
            MOVE_CARDS(store, state, target, opponent.deck, { cards: [card], sourceCard: this });
          });

          // Clear any effects/damage/conditions on the slot
          target.damage = 0;
          target.specialConditions = [];
          target.marker.markers = [];

          SHUFFLE_DECK(store, state, opponent);
        }
      });
    }

    // Attack 2: Hypnoblast
    // Ref: set-ultra-prism/bronzor.ts (Hypnosis)
    if (AFTER_ATTACK(effect, 1, this)) {
      ADD_SLEEP_TO_PLAYER_ACTIVE(store, state, effect.opponent, this);
    }

    return state;
  }
}
