// This file was auto-generated by the card stub generator.
// Card effects were implemented by an agent.
// If you have any questions or feedback, reach out to @C4 in the discord.

import { PokemonCard } from '../../../game/store/card/pokemon-card';
import { Stage, CardType } from '../../../game/store/card/card-types';
import { ChoosePokemonPrompt, GameMessage, PlayerType, SlotType, StoreLike, State } from '../../../game';
import { CardTarget } from '../../../game/store/actions/play-card-action';
import { Effect } from '../../../game/store/effects/effect';
import {WAS_ATTACK_USED, MOVE_CARDS } from '../../../game/store/prefabs/prefabs';

export class Cramorant extends PokemonCard {
  public stage: Stage = Stage.BASIC;
  public cardType: CardType[] = [W];
  public hp: number = 110;
  public weakness = [{ type: L }];
  public resistance = [{ type: F, value: -30 }];
  public retreat = [C];

  public attacks = [
    {
      name: 'Continuous Gulp Missile',
      cost: [C, C],
      damage: 60,
      damageCalculation: 'x',
      text: 'Discard any number of Arrokuda from your Bench. This attack does 60 damage for each Arrokuda you discarded in this way.'
    }
  ];

  public regulationMark: string = 'D';
  public set: string = 'VIV';
  public setNumber: string = '40';
  public cardImage: string = 'assets/cardback.png';
  public name: string = 'Cramorant';
  public fullName: string = 'Cramorant VIV';

  public reduceEffect(store: StoreLike, state: State, effect: Effect): State {
    // Attack 1: Continuous Gulp Missile
    // Ref: set-rebel-clash/inteleon.ts (ChoosePokemonPrompt to choose bench cards, then discard)
    if (WAS_ATTACK_USED(effect, 0, this)) {
      const player = effect.player;

      // Find Arrokuda on bench
      const arrokudaSlots = player.bench.filter(b => {
        const pokemon = b.getPokemonCard();
        return pokemon && pokemon.name === 'Arrokuda';
      });

      if (arrokudaSlots.length === 0) {
        effect.damage = 0;
        return state;
      }

      // Block non-Arrokuda bench slots
      const blocked: CardTarget[] = [];
      player.bench.forEach((b, index) => {
        const pokemon = b.getPokemonCard();
        if (!pokemon || pokemon.name !== 'Arrokuda') {
          blocked.push({ player: PlayerType.BOTTOM_PLAYER, slot: SlotType.BENCH, index });
        }
      });

      store.prompt(state, new ChoosePokemonPrompt(
        player.id,
        GameMessage.CHOOSE_POKEMON_TO_DISCARD,
        PlayerType.BOTTOM_PLAYER,
        [SlotType.BENCH],
        { allowCancel: false, min: 0, max: arrokudaSlots.length, blocked }
      ), targets => {
        const discarded = targets || [];
        effect.damage = 60 * discarded.length;

        // Discard the selected Arrokuda
        discarded.forEach(target => {
          const cards = target.cards.slice();
          cards.forEach(card => MOVE_CARDS(store, state, target, player.discard, { cards: [card], sourceCard: this }));
        });
      });
    }

    return state;
  }
}
