// This file was auto-generated by the card stub generator.
// Card effects were implemented by an agent.
// If you have any questions or feedback, reach out to @C4 in the discord.

import {ADD_POISON_TO_PLAYER_ACTIVE, AFTER_ATTACK, SHUFFLE_DECK, WAS_ATTACK_USED, MOVE_CARDS } from '../../../game/store/prefabs/prefabs';
import { CardType, Stage, SuperType } from '../../../game/store/card/card-types';
import { PokemonCard } from '../../../game/store/card/pokemon-card';
import { Effect } from '../../../game/store/effects/effect';
import { State, StoreLike, TrainerCard, TrainerType } from '../../../game';
export class Garbodor extends PokemonCard {
  public stage: Stage = Stage.STAGE_1;
  public evolvesFrom: string = 'Trubbish';
  public cardType: CardType[] = [D];
  public hp: number = 120;
  public weakness = [{ type: F }];
  public retreat = [C, C, C];

  public attacks = [
    {
      name: 'Trash Cyclone',
      cost: [C, C],
      damage: 30,
      damageCalculation: 'x',
      text: 'This attack does 30 damage for each Pokémon Tool card in your discard pile. Then, shuffle those cards into your deck.'
    },
    {
      name: 'Poison Spray',
      cost: [D, C, C],
      damage: 80,
      text: 'Your opponent\'s Active Pokémon is now Poisoned.'
    }
  ];

  public regulationMark: string = 'D';
  public set: string = 'VIV';
  public setNumber: string = '111';
  public cardImage: string = 'assets/cardback.png';
  public name: string = 'Garbodor';
  public fullName: string = 'Garbodor VIV';

  public reduceEffect(store: StoreLike, state: State, effect: Effect): State {
    // Attack 1: Trash Cyclone
    // Ref: set-plasma-freeze/kingdra.ts (Dragon Vortex - count cards in discard, deal x damage, shuffle back)
    if (WAS_ATTACK_USED(effect, 0, this)) {
      const player = effect.player;

      const toolCards = player.discard.cards.filter(c =>
        c.superType === SuperType.TRAINER &&
        (c as TrainerCard).trainerType === TrainerType.TOOL
      );

      effect.damage = 30 * toolCards.length;

      if (toolCards.length > 0) {
        toolCards.forEach(card => {
          MOVE_CARDS(store, state, player.discard, player.deck, { cards: [card], sourceCard: this });
        });
        SHUFFLE_DECK(store, state, player);
      }
    }

    // Attack 2: Poison Spray
    // Ref: set-vivid-voltage/dusclops.ts (YOUR_OPPPONENTS_ACTIVE_POKEMON_IS_NOW_POISIONED)
    if (AFTER_ATTACK(effect, 1, this)) {
      ADD_POISON_TO_PLAYER_ACTIVE(store, state, effect.opponent, this);
    }

    return state;
  }
}
