// This file was auto-generated by the card stub generator.
// Card effects were implemented by an agent.
// If you have any questions or feedback, reach out to @C4 in the discord.

import { PokemonCard } from '../../../game/store/card/pokemon-card';
import { Stage, CardType } from '../../../game/store/card/card-types';
import { ConfirmPrompt, GameMessage, SlotType, StoreLike, State, StateUtils } from '../../../game';
import { Effect } from '../../../game/store/effects/effect';
import {WAS_ATTACK_USED, DRAW_CARDS, SHUFFLE_DECK, MOVE_CARDS } from '../../../game/store/prefabs/prefabs';
import { PUT_X_DAMAGE_COUNTERS_IN_ANY_WAY_YOU_LIKE } from '../../../game/store/prefabs/attack-effects';

export class Girafarig extends PokemonCard {
  public stage: Stage = Stage.BASIC;
  public cardType: CardType[] = [P];
  public hp: number = 90;
  public weakness = [{ type: D }];
  public resistance = [{ type: F, value: -30 }];
  public retreat = [C];

  public attacks = [
    {
      name: 'Psypower',
      cost: [P],
      damage: 0,
      text: 'Put 2 damage counters on your opponent\'s Pokémon in any way you like.'
    },
    {
      name: 'Commanding Tail',
      cost: [P, C],
      damage: 30,
      text: 'You may have your opponent shuffle their hand into their deck. If you do, your opponent draws 4 cards.'
    }
  ];

  public regulationMark: string = 'D';
  public set: string = 'VIV';
  public setNumber: string = '65';
  public cardImage: string = 'assets/cardback.png';
  public name: string = 'Girafarig';
  public fullName: string = 'Girafarig VIV';

  public reduceEffect(store: StoreLike, state: State, effect: Effect): State {
    // Attack 1: Psypower
    // Ref: set-champions-path/galarian-cursola-v.ts (PUT_X_DAMAGE_COUNTERS_IN_ANY_WAY_YOU_LIKE on opponent's Pokemon)
    if (WAS_ATTACK_USED(effect, 0, this)) {
      return PUT_X_DAMAGE_COUNTERS_IN_ANY_WAY_YOU_LIKE(2, store, state, effect, [SlotType.ACTIVE, SlotType.BENCH]);
    }

    // Attack 2: Commanding Tail
    // Ref: set-sword-and-shield/nickit.ts (opponent shuffles hand into deck + draw cards)
    if (WAS_ATTACK_USED(effect, 1, this)) {
      const player = effect.player;
      const opponent = StateUtils.getOpponent(state, player);

      store.prompt(state, new ConfirmPrompt(player.id, GameMessage.WANT_TO_USE_ABILITY), wantTo => {
        if (wantTo) {
          // Shuffle opponent's hand into their deck
          MOVE_CARDS(store, state, opponent.hand, opponent.deck, { sourceCard: this });
          SHUFFLE_DECK(store, state, opponent);
          // Opponent draws 4 cards
          DRAW_CARDS(store, state, opponent, 4);
        }
      });
    }

    return state;
  }
}
