// This file was auto-generated by the card stub generator.
// Card effects were implemented by an agent.
// If you have any questions or feedback, reach out to @C4 in the discord.

import { TrainerCard } from '../../../game/store/card/trainer-card';
import { TrainerType, CardTag } from '../../../game/store/card/card-types';
import { GameError, GameMessage, StoreLike, State, StateUtils, GamePhase } from '../../../game';
import { CheckHpEffect } from '../../../game/store/effects/check-effects';
import { Effect } from '../../../game/store/effects/effect';
import { KnockOutEffect } from '../../../game/store/effects/game-effects';
import { AttachPokemonToolEffect, ToolEffect } from '../../../game/store/effects/play-card-effects';

export class HerosMedal extends TrainerCard {
  protected _trainerType: TrainerType = TrainerType.TOOL;
  public regulationMark: string = 'D';
  public set: string = 'VIV';
  public setNumber: string = '152';
  public cardImage: string = 'assets/cardback.png';
  public name: string = "Hero's Medal";
  public fullName: string = "Hero's Medal VIV";
  public text: string =
    "Attach a Pokémon Tool to 1 of your Pokémon that doesn't already have a Pokémon Tool attached. The Pokémon VMAX this card is attached to gets -100 HP, and if it is Knocked Out by damage from an attack from your opponent's Pokémon, that player takes 1 fewer Prize card. You can't attach this card to a Pokémon VMAX that has 100 HP or less remaining. You may play any number of Item cards during your turn.";

  public reduceEffect(store: StoreLike, state: State, effect: Effect): State {
    // Check for attachment restrictions
    // Ref: set-unified-minds/u-turn-board.ts (AttachPokemonToolEffect interception pattern)
    if (effect instanceof AttachPokemonToolEffect && effect.trainerCard === this) {
      const sourceCard = effect.target.getPokemonCard();

      if (!sourceCard) {
        throw new GameError(GameMessage.CANNOT_PLAY_THIS_CARD);
      }

      // Can only attach to Pokemon VMAX
      if (!sourceCard.hasTag(CardTag.POKEMON_VMAX)) {
        throw new GameError(GameMessage.CANNOT_PLAY_THIS_CARD);
      }

      // Can't attach if the VMAX has 100 HP or less remaining
      const checkHp = new CheckHpEffect(effect.player, effect.target);
      store.reduceEffect(state, checkHp);
      const remainingHp = checkHp.hp - effect.target.damage;
      if (remainingHp <= 100) {
        throw new GameError(GameMessage.CANNOT_PLAY_THIS_CARD);
      }
    }

    // HP reduction for VMAX Pokemon
    // Ref: set-cosmic-eclipse/island-challenge-amulet.ts (CheckHpEffect tool pattern)
    if (effect instanceof CheckHpEffect && effect.target.tools.includes(this)) {
      const sourceCard = effect.target.getPokemonCard();

      try {
        const toolEffect = new ToolEffect(effect.player, this);
        store.reduceEffect(state, toolEffect);
      } catch {
        return state;
      }

      if (!sourceCard) {
        return state;
      }

      // Only applies to VMAX Pokemon
      if (!sourceCard.hasTag(CardTag.POKEMON_VMAX)) {
        return state;
      }

      effect.hp -= 100;
    }

    // Prize reduction when KO'd by opponent's attack
    // Ref: set-cosmic-eclipse/island-challenge-amulet.ts (KnockOutEffect prize reduction)
    if (effect instanceof KnockOutEffect && effect.target.tools.includes(this)) {
      const player = effect.player;
      const opponent = StateUtils.getOpponent(state, player);
      const sourceCard = effect.target.getPokemonCard();

      if (state.phase !== GamePhase.ATTACK || state.players[state.activePlayer] !== opponent) {
        return state;
      }

      if (!sourceCard) {
        return state;
      }

      // Only applies to VMAX Pokemon
      if (!sourceCard.hasTag(CardTag.POKEMON_VMAX)) {
        return state;
      }

      try {
        const toolEffect = new ToolEffect(player, this);
        store.reduceEffect(state, toolEffect);
      } catch {
        return state;
      }

      effect.prizeCount = Math.max(0, effect.prizeCount - 1);
    }

    return state;
  }
}
