// This file was auto-generated by the card stub generator.
// Card effects were implemented by an agent.
// If you have any questions or feedback, reach out to @C4 in the discord.

import { PokemonCard } from '../../../game/store/card/pokemon-card';
import { Stage, CardType, TrainerType } from '../../../game/store/card/card-types';
import { ChooseCardsPrompt, GameMessage, StoreLike, State } from '../../../game';
import { TrainerCard } from '../../../game/store/card/trainer-card';
import { Effect } from '../../../game/store/effects/effect';
import {WAS_ATTACK_USED, DRAW_CARDS, MOVE_CARDS } from '../../../game/store/prefabs/prefabs';
import { TrainerEffect } from '../../../game/store/effects/play-card-effects';
import { EndTurnEffect } from '../../../game/store/effects/game-phase-effects';
import { Bea } from './bea';

export class Hitmontop extends PokemonCard {
  public stage: Stage = Stage.BASIC;
  public cardType: CardType[] = [F];
  public hp: number = 90;
  public weakness = [{ type: P }];
  public retreat = [C];

  public attacks = [
    {
      name: 'Cycle Draw',
      cost: [C],
      damage: 0,
      text: 'Discard a card from your hand. If you do, draw 3 cards.'
    },
    {
      name: 'Tornado Kick',
      cost: [F, C, C],
      damage: 50,
      damageCalculation: '+',
      text: 'If you played Bea from your hand during this turn, this attack does 80 more damage.'
    }
  ];

  public regulationMark: string = 'D';
  public set: string = 'VIV';
  public setNumber: string = '88';
  public cardImage: string = 'assets/cardback.png';
  public name: string = 'Hitmontop';
  public fullName: string = 'Hitmontop VIV';

  public readonly BEA_PLAYED_MARKER = 'HITMONTOP_VIV_BEA_PLAYED_MARKER';

  public reduceEffect(store: StoreLike, state: State, effect: Effect): State {
    // Track when Bea is played from hand
    // Ref: set-champions-path/scrafty.ts (Piers played marker pattern)
    if (effect instanceof TrainerEffect
      && effect.trainerCard instanceof TrainerCard
      && effect.trainerCard.trainerType === TrainerType.SUPPORTER
      && effect.trainerCard instanceof Bea) {
      effect.player.marker.addMarker(this.BEA_PLAYED_MARKER, this);
    }

    // Attack 1: Cycle Draw
    // Ref: AGENTS-patterns.md (discard a card from hand, then draw)
    if (WAS_ATTACK_USED(effect, 0, this)) {
      const player = effect.player;

      if (player.hand.cards.length === 0) {
        return state;
      }

      store.prompt(state, new ChooseCardsPrompt(
        player,
        GameMessage.CHOOSE_CARD_TO_DISCARD,
        player.hand,
        {},
        { min: 1, max: 1, allowCancel: false }
      ), selected => {
        const cards = selected || [];
        cards.forEach(card => MOVE_CARDS(store, state, player.hand, player.discard, { cards: [card], sourceCard: this }));

        if (cards.length > 0) {
          DRAW_CARDS(store, state, player, 3);
        }
      });
    }

    // Attack 2: Tornado Kick
    // Ref: set-champions-path/scrafty.ts (conditional damage based on supporter played marker)
    if (WAS_ATTACK_USED(effect, 1, this)) {
      const player = effect.player;
      if (player.marker.hasMarker(this.BEA_PLAYED_MARKER, this)) {
        effect.damage += 80;
      }
    }

    // Clean up Bea played marker at end of turn
    if (effect instanceof EndTurnEffect) {
      effect.player.marker.removeMarker(this.BEA_PLAYED_MARKER, this);
    }

    return state;
  }
}
