// This file was auto-generated by the card stub generator.
// Card effects were implemented by an agent.
// If you have any questions or feedback, reach out to @C4 in the discord.

import { TrainerCard } from '../../../game/store/card/trainer-card';
import { TrainerType } from '../../../game/store/card/card-types';
import { StoreLike, State } from '../../../game';
import { Effect } from '../../../game/store/effects/effect';
import { TrainerEffect } from '../../../game/store/effects/play-card-effects';
import {
  MULTIPLE_COIN_FLIPS_PROMPT,
  SEARCH_DECK_FOR_CARDS_TO_HAND,
  MOVE_CARDS,
} from '../../../game/store/prefabs/prefabs';

export class Opal extends TrainerCard {
  protected _trainerType: TrainerType = TrainerType.SUPPORTER;

  public regulationMark: string = 'D';

  public set: string = 'VIV';
  public setNumber: string = '158';
  public cardImage: string = 'assets/cardback.png';
  public name: string = 'Opal';
  public fullName: string = 'Opal VIV';

  public text: string =
    'Flip 2 coins. Search your deck for a number of cards up to the number of heads, put them into your hand, and shuffle your deck. You may play only 1 Supporter card during your turn.';

  public reduceEffect(store: StoreLike, state: State, effect: Effect): State {
    // Ref: set-darkness-ablaze/hippopotas.ts (MULTIPLE_COIN_FLIPS_PROMPT),
    //      set-vivid-voltage/leon.ts (WAS_TRAINER_USED + SEARCH_DECK_FOR_CARDS_TO_HAND)
    if (effect instanceof TrainerEffect && effect.trainerCard === this) {
      const player = effect.player;

      MOVE_CARDS(store, state, player.hand, player.supporter, {
        cards: [effect.trainerCard],
        sourceCard: this,
      });
      effect.preventDefault = true;

      MULTIPLE_COIN_FLIPS_PROMPT(store, state, player, 2, (results) => {
        const heads = results.filter((r) => r).length;
        if (heads > 0 && player.deck.cards.length > 0) {
          SEARCH_DECK_FOR_CARDS_TO_HAND(
            store,
            state,
            player,
            this,
            {},
            { min: 0, max: heads, allowCancel: false },
          );
        }
      });
    }

    return state;
  }
}
