// This file was auto-generated by the card stub generator.
// Card effects were implemented by an agent.
// If you have any questions or feedback, reach out to @C4 in the discord.

import { PokemonCard } from '../../../game/store/card/pokemon-card';
import {
  Stage,
  CardType,
  CardTag,
  SuperType,
  EnergyType,
} from '../../../game/store/card/card-types';
import {
  AttachEnergyPrompt,
  GameMessage,
  PlayerType,
  SlotType,
  StoreLike,
  State,
  StateUtils,
} from '../../../game';
import { CardTarget } from '../../../game/store/actions/play-card-action';
import { Effect } from '../../../game/store/effects/effect';
import {WAS_ATTACK_USED, MOVE_CARDS } from '../../../game/store/prefabs/prefabs';
import { BLOCK_RETREAT } from '../../../game/store/prefabs/effect-of-attack-prefabs';
import { EnergyCard } from '../../../game/store/card/energy-card';
import { HealEffect } from '../../../game/store/effects/game-effects';

export class ZarudeV extends PokemonCard {
  protected _tags = [CardTag.POKEMON_V];
  public stage: Stage = Stage.BASIC;
  public cardType: CardType[] = [G];
  public hp: number = 210;
  public weakness = [{ type: R }];
  public retreat = [C];

  public attacks = [
    {
      name: 'Bind Down',
      cost: [C, C],
      damage: 50,
      text: "During your opponent's next turn, the Defending Pokémon can't retreat.",
    },
    {
      name: 'Jungle Rising',
      cost: [G, G],
      damage: 100,
      text: 'You may attach up to 2 basic Energy cards from your hand to your Benched Pokémon in any way you like. If you attached Energy to a Pokémon in this way, heal all damage from that Pokémon.',
    },
  ];

  public regulationMark: string = 'D';
  public set: string = 'VIV';
  public setNumber: string = '22';
  public cardImage: string = 'assets/cardback.png';
  public name: string = 'Zarude V';
  public fullName: string = 'Zarude V VIV';

  public reduceEffect(store: StoreLike, state: State, effect: Effect): State {
    // Attack 1: Bind Down
    // Ref: set-darkness-ablaze/talonflame.ts (BLOCK_RETREAT 3-call pattern)
    if (WAS_ATTACK_USED(effect, 0, this)) {
      return BLOCK_RETREAT(store, state, effect, this);
    }
    // Attack 2: Jungle Rising
    // Ref: set-darkness-ablaze/rose.ts (AttachEnergyPrompt from source to bench)
    if (WAS_ATTACK_USED(effect, 1, this)) {
      const player = effect.player;

      const hasBasicEnergyInHand = player.hand.cards.some(
        (c) => c instanceof EnergyCard && c.energyType === EnergyType.BASIC,
      );
      if (!hasBasicEnergyInHand) {
        return state;
      }

      const hasBench = player.bench.some((b) => b.cards.length > 0);
      if (!hasBench) {
        return state;
      }

      // Block active Pokemon (can only attach to bench)
      const blockedTo: CardTarget[] = [];
      player.forEachPokemon(PlayerType.BOTTOM_PLAYER, (cardList, card, target) => {
        if (cardList === player.active) {
          blockedTo.push(target);
        }
      });

      store.prompt(
        state,
        new AttachEnergyPrompt(
          player.id,
          GameMessage.ATTACH_ENERGY_CARDS,
          player.hand,
          PlayerType.BOTTOM_PLAYER,
          [SlotType.BENCH],
          { superType: SuperType.ENERGY, energyType: EnergyType.BASIC },
          { allowCancel: true, min: 0, max: 2, blockedTo },
        ),
        (transfers) => {
          transfers = transfers || [];
          if (transfers.length === 0) {
            return;
          }

          // Track which targets received energy
          const healTargets = new Set<string>();
          for (const transfer of transfers) {
            const target = StateUtils.getTarget(state, player, transfer.to);
            MOVE_CARDS(store, state, player.hand, target, { cards: [transfer.card], sourceCard: this });
            healTargets.add(`${transfer.to.player}-${transfer.to.slot}-${transfer.to.index}`);
          }

          // Heal all damage from Pokemon that received energy
          for (const transfer of transfers) {
            const target = StateUtils.getTarget(state, player, transfer.to);
            if (target.damage > 0) {
              const healEffect = new HealEffect(player, target, target.damage);
              store.reduceEffect(state, healEffect);
            }
          }
        },
      );
    }

    return state;
  }
}
