// This file was auto-generated by the card stub generator.
// Card effects were implemented by an agent.
// If you have any questions or feedback, reach out to @C4 in the discord.

import { PokemonCard } from '../../../game/store/card/pokemon-card';
import {
  Stage,
  CardType,
  CardTag,
  EnergyType,
  SuperType,
} from '../../../game/store/card/card-types';
import { Card, ChooseEnergyPrompt, GameMessage, StoreLike, State, StateUtils } from '../../../game';
import { EnergyCard } from '../../../game/store/card/energy-card';
import { Effect } from '../../../game/store/effects/effect';
import { AfterAttackEffect, EndTurnEffect } from '../../../game/store/effects/game-phase-effects';
import {WAS_ATTACK_USED, SWITCH_ACTIVE_WITH_BENCHED, MOVE_CARDS } from '../../../game/store/prefabs/prefabs';
import { ChooseCardsPrompt } from '../../../game/store/prompts/choose-cards-prompt';
import { CheckProvidedEnergyEffect } from '../../../game/store/effects/check-effects';

export class LaprasV extends PokemonCard {
  protected _tags = [CardTag.POKEMON_V];
  public stage: Stage = Stage.BASIC;
  public cardType: CardType[] = [W];
  public hp: number = 210;
  public weakness = [{ type: L }];
  public retreat = [C, C];

  public attacks = [
    {
      name: 'Body Surf',
      cost: [C],
      damage: 0,
      text: 'Attach a [W] Energy card from your hand to this Pokémon. If you do, switch it with 1 of your Benched Pokémon.',
    },
    {
      name: 'Ocean Loop',
      cost: [W, W, W, C],
      damage: 210,
      text: 'Put 2 [W] Energy attached to this Pokémon into your hand.',
    },
  ];

  public regulationMark: string = 'D';
  public set: string = 'SSH';
  public setNumber: string = '49';
  public cardImage: string = 'assets/cardback.png';
  public name: string = 'Lapras V';
  public fullName: string = 'Lapras V SSH';

  public bodySurfAttached = false;

  public reduceEffect(store: StoreLike, state: State, effect: Effect): State {
    // Attack 1: Body Surf
    // Ref: set-dragons-majesty/reshiram-gx.ts (ChooseCardsPrompt from hand + attach to self)
    // Ref: AGENTS.md (AfterAttackEffect pattern for switching after energy attach)
    if (WAS_ATTACK_USED(effect, 0, this)) {
      const player = effect.player;

      const hasWaterInHand = player.hand.cards.some(
        (c) =>
          c instanceof EnergyCard &&
          c.energyType === EnergyType.BASIC &&
          c.provides.includes(CardType.WATER),
      );

      if (!hasWaterInHand) {
        return state;
      }

      store.prompt(
        state,
        new ChooseCardsPrompt(
          player,
          GameMessage.CHOOSE_CARD_TO_ATTACH,
          player.hand,
          { superType: SuperType.ENERGY, energyType: EnergyType.BASIC, name: 'Water Energy' },
          { min: 0, max: 1, allowCancel: false },
        ),
        (cards: Card[]) => {
          cards = cards || [];
          if (cards.length > 0) {
            // Attach energy to Lapras V (this)
            const cardList = StateUtils.findCardList(state, this);
            if (cardList) {
              MOVE_CARDS(store, state, player.hand, cardList, { cards: cards, sourceCard: this });
            }
            this.bodySurfAttached = true;
          }
        },
      );
    }

    if (effect instanceof AfterAttackEffect && this.bodySurfAttached) {
      this.bodySurfAttached = false;
      const player = effect.player;
      if (player.bench.some((b) => b.cards.length > 0)) {
        SWITCH_ACTIVE_WITH_BENCHED(store, state, player);
      }
    }

    if (effect instanceof EndTurnEffect) {
      this.bodySurfAttached = false;
    }

    // Attack 2: Ocean Loop
    // Ref: set-hidden-fates/lycanroc-gx-2.ts (ChooseEnergyPrompt + move energy to hand)
    if (WAS_ATTACK_USED(effect, 1, this)) {
      const player = effect.player;

      const checkEnergy = new CheckProvidedEnergyEffect(player, player.active);
      state = store.reduceEffect(state, checkEnergy);

      const waterEnergyMap = checkEnergy.energyMap.filter(
        (em) => em.provides.includes(CardType.WATER) || em.provides.includes(CardType.ANY),
      );

      if (waterEnergyMap.length === 0) {
        return state;
      }

      const count = Math.min(2, waterEnergyMap.length);

      store.prompt(
        state,
        new ChooseEnergyPrompt(
          player.id,
          GameMessage.CHOOSE_ENERGIES_TO_HAND,
          waterEnergyMap,
          [CardType.COLORLESS, CardType.COLORLESS],
          { allowCancel: false },
        ),
        (energy) => {
          const cards: Card[] = (energy || []).slice(0, count).map((e) => e.card);
          if (cards.length > 0) {
            MOVE_CARDS(store, state, player.active, player.hand, { cards: cards, sourceCard: this });
          }
        },
      );
    }

    return state;
  }
}
