// This file was auto-generated by the card stub generator.
// Card effects were implemented by an agent.
// If you have any questions or feedback, reach out to @C4 in the discord.

import { PokemonCard } from '../../../game/store/card/pokemon-card';
import { Stage, CardType } from '../../../game/store/card/card-types';
import { CardList, StoreLike, State, StateUtils } from '../../../game';
import { Effect } from '../../../game/store/effects/effect';
import {WAS_ATTACK_USED, DRAW_CARDS, MOVE_CARDS } from '../../../game/store/prefabs/prefabs';

export class Nickit extends PokemonCard {
  public stage: Stage = Stage.BASIC;
  public cardType: CardType[] = [D];
  public hp: number = 70;
  public weakness = [{ type: G }];
  public retreat = [C];

  public attacks = [
    {
      name: 'Instigate',
      cost: [D],
      damage: 0,
      text: 'Your opponent shuffles their hand and puts it on the bottom of their deck. If they put any cards on the bottom of their deck in this way, they draw 3 cards.'
    }
  ];

  public regulationMark: string = 'D';
  public set: string = 'SSH';
  public setNumber: string = '125';
  public cardImage: string = 'assets/cardback.png';
  public name: string = 'Nickit';
  public fullName: string = 'Nickit SSH';

  public reduceEffect(store: StoreLike, state: State, effect: Effect): State {
    // Attack 1: Instigate
    // Ref: set-sword-and-shield/marnie.ts (shuffle hand to bottom of deck pattern)
    if (WAS_ATTACK_USED(effect, 0, this)) {
      const player = effect.player;
      const opponent = StateUtils.getOpponent(state, player);

      const cardsInHand = opponent.hand.cards.length;
      if (cardsInHand > 0) {
        // Shuffle opponent's hand to bottom of deck
        const deckBottom = new CardList();
        MOVE_CARDS(store, state, opponent.hand, deckBottom, { sourceCard: this });
        MOVE_CARDS(store, state, deckBottom, opponent.deck, { sourceCard: this });
        // Draw 3 cards
        DRAW_CARDS(store, state, opponent, Math.min(3, opponent.deck.cards.length));
      }
    }

    return state;
  }
}
