// This file was auto-generated by the card stub generator.
// Card effects were implemented by an agent.
// If you have any questions or feedback, reach out to @C4 in the discord.

import { PokemonCard } from '../../../game/store/card/pokemon-card';
import { Stage, CardType, EnergyType, SuperType } from '../../../game/store/card/card-types';
import { Card, GameMessage, StoreLike, State, StateUtils } from '../../../game';
import { Effect } from '../../../game/store/effects/effect';
import {WAS_ATTACK_USED, SHUFFLE_DECK, MOVE_CARDS } from '../../../game/store/prefabs/prefabs';
import { ChooseCardsPrompt } from '../../../game/store/prompts/choose-cards-prompt';

export class Pikachu extends PokemonCard {
  public stage: Stage = Stage.BASIC;
  public cardType: CardType[] = [L];
  public hp: number = 60;
  public weakness = [{ type: F }];
  public retreat = [C];

  public attacks = [
    {
      name: 'Charge',
      cost: [C],
      damage: 0,
      text: 'Search your deck for a [L] Energy card and attach it to this Pokémon. Then, shuffle your deck.'
    },
    {
      name: 'Electro Ball',
      cost: [L, C],
      damage: 20,
      text: ''
    }
  ];

  public regulationMark: string = 'D';
  public set: string = 'SSH';
  public setNumber: string = '65';
  public cardImage: string = 'assets/cardback.png';
  public name: string = 'Pikachu';
  public fullName: string = 'Pikachu SSH';

  public reduceEffect(store: StoreLike, state: State, effect: Effect): State {
    // Attack 1: Charge
    // Ref: set-dragons-majesty/reshiram-gx.ts (ChooseCardsPrompt from deck for energy, attach, shuffle)
    if (WAS_ATTACK_USED(effect, 0, this)) {
      const player = effect.player;

      store.prompt(state, new ChooseCardsPrompt(
        player,
        GameMessage.CHOOSE_CARD_TO_ATTACH,
        player.deck,
        { superType: SuperType.ENERGY, energyType: EnergyType.BASIC, name: 'Lightning Energy' },
        { min: 0, max: 1, allowCancel: false }
      ), (cards: Card[]) => {
        cards = cards || [];
        if (cards.length > 0) {
          const cardList = StateUtils.findCardList(state, this);
          if (cardList) {
            MOVE_CARDS(store, state, player.deck, cardList, { cards: cards, sourceCard: this });
          }
        }
        SHUFFLE_DECK(store, state, player);
      });
    }

    return state;
  }
}
