// This file was auto-generated by the card stub generator.
// Card effects were implemented by an agent.
// If you have any questions or feedback, reach out to @C4 in the discord.

import { TrainerCard } from '../../../game/store/card/trainer-card';
import { TrainerType } from '../../../game/store/card/card-types';
import { StoreLike, State } from '../../../game';
import { Effect } from '../../../game/store/effects/effect';
import { EndTurnEffect } from '../../../game/store/effects/game-phase-effects';
import { WAS_TRAINER_USED } from '../../../game/store/prefabs/trainer-prefabs';
import { DRAW_CARDS_UNTIL_CARDS_IN_HAND, MOVE_CARDS } from '../../../game/store/prefabs/prefabs';

export class RotomBike extends TrainerCard {
  protected _trainerType: TrainerType = TrainerType.ITEM;
  public regulationMark: string = 'D';
  public set: string = 'SSH';
  public setNumber: string = '181';
  public cardImage: string = 'assets/cardback.png';
  public name: string = 'Rotom Bike';
  public fullName: string = 'Rotom Bike SSH';
  public text: string =
    'Draw cards until you have 6 cards in your hand. Your turn ends. You may play any number of Item cards during your turn.';

  public reduceEffect(store: StoreLike, state: State, effect: Effect): State {
    // Ref: set-temporal-forces/delivery-box.ts (EndTurnEffect pattern for items)
    // Ref: AGENTS-patterns.md (DRAW_CARDS_UNTIL_CARDS_IN_HAND)
    if (WAS_TRAINER_USED(effect, this)) {
      const player = effect.player;
      MOVE_CARDS(store, state, player.hand, player.discard, { cards: [this], sourceCard: this });
      effect.preventDefault = true;

      DRAW_CARDS_UNTIL_CARDS_IN_HAND(player, 6);

      const endTurnEffect = new EndTurnEffect(player);
      store.reduceEffect(state, endTurnEffect);
    }

    return state;
  }
}
