// This file was auto-generated by the card stub generator.
// Card effects were implemented by an agent.
// If you have any questions or feedback, reach out to @C4 in the discord.

import { PokemonCard } from '../../../game/store/card/pokemon-card';
import {
  Stage,
  CardType,
  CardTag,
  EnergyType,
  SuperType,
} from '../../../game/store/card/card-types';
import { StoreLike, State, StateUtils } from '../../../game';
import { EnergyCard } from '../../../game/store/card/energy-card';
import { CardList } from '../../../game/store/state/card-list';
import { Effect } from '../../../game/store/effects/effect';
import {WAS_ATTACK_USED, MOVE_CARDS } from '../../../game/store/prefabs/prefabs';
import { DISCARD_AN_ENERGY_FROM_OPPONENTS_ACTIVE_POKEMON } from '../../../game/store/prefabs/attack-effects';

export class TorkoalV extends PokemonCard {
  protected _tags = [CardTag.POKEMON_V];
  public stage: Stage = Stage.BASIC;
  public cardType: CardType[] = [R];
  public hp: number = 210;
  public weakness = [{ type: W }];
  public retreat = [C, C, C, C];

  public attacks = [
    {
      name: 'Combustion Pillar',
      cost: [R, R, C],
      damage: 90,
      damageCalculation: '+',
      text: 'Discard the top card of your deck. If that card is a [R] Energy card, this attack does 90 more damage.',
    },
    {
      name: 'Steam Crush',
      cost: [R, R, R, C],
      damage: 120,
      text: "Discard 2 Energy from your opponent's Active Pokémon.",
    },
  ];

  public regulationMark: string = 'D';
  public set: string = 'SSH';
  public setNumber: string = '24';
  public cardImage: string = 'assets/cardback.png';
  public name: string = 'Torkoal V';
  public fullName: string = 'Torkoal V SSH';

  public reduceEffect(store: StoreLike, state: State, effect: Effect): State {
    // Attack 1: Combustion Pillar
    // Ref: set-cosmic-eclipse/ns-resolve.ts (discard top cards, check if energy)
    if (WAS_ATTACK_USED(effect, 0, this)) {
      const player = effect.player;

      if (player.deck.cards.length === 0) {
        return state;
      }

      // Take top card into a temporary list
      const topCard = new CardList();
      MOVE_CARDS(store, state, player.deck, topCard, { count: 1, sourceCard: this });

      // Check if it's a [R] Basic Energy card
      const isFireEnergy =
        topCard.cards.length > 0 &&
        topCard.cards[0] instanceof EnergyCard &&
        (topCard.cards[0] as EnergyCard).energyType === EnergyType.BASIC &&
        (topCard.cards[0] as EnergyCard).provides.includes(CardType.FIRE);

      // Move the card to discard
      MOVE_CARDS(store, state, topCard, player.discard, { sourceCard: this });

      if (isFireEnergy) {
        effect.damage += 90;
      }
    }

    // Attack 2: Steam Crush
    // Ref: set-cosmic-eclipse/absol.ts (DiscardCardsEffect), set-cosmic-eclipse/torkoal.ts (Kindle)
    if (WAS_ATTACK_USED(effect, 1, this)) {
      const opponent = StateUtils.getOpponent(state, effect.player);
      const hasEnergy1 = opponent.active.cards.some((c) => c.superType === SuperType.ENERGY);
      if (hasEnergy1) {
        DISCARD_AN_ENERGY_FROM_OPPONENTS_ACTIVE_POKEMON(store, state, effect);
      }
      const hasEnergy2 = opponent.active.cards.some((c) => c.superType === SuperType.ENERGY);
      if (hasEnergy2) {
        DISCARD_AN_ENERGY_FROM_OPPONENTS_ACTIVE_POKEMON(store, state, effect);
      }
    }

    return state;
  }
}
