// This file was auto-generated by the card stub generator.
// Card effects were implemented by an agent.
// If you have any questions or feedback, reach out to @C4 in the discord.

import { TrainerCard } from '../../../game/store/card/trainer-card';
import { CardTag, TrainerType } from '../../../game/store/card/card-types';
import { StoreLike, State } from '../../../game';
import { Effect } from '../../../game/store/effects/effect';
import { DRAW_CARDS } from '../../../game/store/prefabs/prefabs';
import { WAS_TRAINER_USED } from '../../../game/store/prefabs/trainer-prefabs';

export class CoachTrainer extends TrainerCard {
  protected _trainerType: TrainerType = TrainerType.SUPPORTER;
  public set: string = 'UNM';
  public setNumber: string = '192';
  public cardImage: string = 'assets/cardback.png';
  public name: string = 'Coach Trainer';
  public fullName: string = 'Coach Trainer UNM';
  public text: string =
    'Draw 2 cards. If your Active Pokémon is a TAG TEAM Pokémon, draw 2 more cards. You may play only 1 Supporter card during your turn (before your attack).';

  public reduceEffect(store: StoreLike, state: State, effect: Effect): State {
    // Ref: set-unbroken-bonds/snorlax.ts (TAG_TEAM check pattern)
    if (WAS_TRAINER_USED(effect, this)) {
      const player = effect.player;
      DRAW_CARDS(store, state, player, 2);

      const activePokemon = player.active.getPokemonCard();
      if (activePokemon && activePokemon.hasTag(CardTag.TAG_TEAM)) {
        DRAW_CARDS(store, state, player, 2);
      }
    }

    return state;
  }
}
