// This file was auto-generated by the card stub generator.
// Card effects were implemented by an agent.
// If you have any questions or feedback, reach out to @C4 in the discord.

import { TrainerCard } from '../../../game/store/card/trainer-card';
import { TrainerType, SpecialCondition } from '../../../game/store/card/card-types';
import { StoreLike, State, StateUtils, GamePhase } from '../../../game';
import { AfterDamageEffect } from '../../../game/store/effects/attack-effects';
import { AddSpecialConditionsPowerEffect } from '../../../game/store/effects/check-effects';
import { Effect } from '../../../game/store/effects/effect';
import { ToolEffect } from '../../../game/store/effects/play-card-effects';

export class EarRingingBell extends TrainerCard {
  protected _trainerType: TrainerType = TrainerType.TOOL;
  public set: string = 'UNM';
  public setNumber: string = '194';
  public cardImage: string = 'assets/cardback.png';
  public name: string = 'Ear-Ringing Bell';
  public fullName: string = 'Ear-Ringing Bell UNM';
  public text: string =
    "If the Pokemon this card is attached to is your Active Pokemon and is damaged by an opponent's attack (even if that Pokemon is Knocked Out), the Attacking Pokemon is now Confused.";

  // Ref: set-sun-and-moon/poison-barb.ts (Poison Barb - tool AfterDamageEffect + special condition on attacker)
  public reduceEffect(store: StoreLike, state: State, effect: Effect): State {
    if (effect instanceof AfterDamageEffect && effect.target.tools.includes(this)) {
      const player = effect.player;
      const targetPlayer = StateUtils.findOwner(state, effect.target);

      // Only trigger if: attacked by opponent, target is active, damage > 0
      if (effect.damage <= 0 || player === targetPlayer || targetPlayer.active !== effect.target) {
        return state;
      }

      // Check if tool is blocked
      try {
        const stub = new ToolEffect(effect.player, this);
        store.reduceEffect(state, stub);
      } catch {
        return state;
      }

      if (state.phase === GamePhase.ATTACK) {
        // Apply Confused to the attacking Pokemon
        const confuseEffect = new AddSpecialConditionsPowerEffect(player, this, effect.source, [
          SpecialCondition.CONFUSED,
        ]);
        store.reduceEffect(state, confuseEffect);
      }
    }

    return state;
  }
}
