// This file was auto-generated by the card stub generator.
// Card effects were implemented by an agent.
// If you have any questions or feedback, reach out to @C4 in the discord.

import { PokemonCard } from '../../../game/store/card/pokemon-card';
import { Stage, CardType, SuperType } from '../../../game/store/card/card-types';
import { Card, ChooseCardsPrompt, ChoosePokemonPrompt, EnergyCard, GameMessage, PlayerType, SlotType, StoreLike, State, StateUtils, ConfirmPrompt } from '../../../game';
import { Effect } from '../../../game/store/effects/effect';
import {WAS_ATTACK_USED, MOVE_CARDS } from '../../../game/store/prefabs/prefabs';

export class Lumineon extends PokemonCard {
  public stage: Stage = Stage.STAGE_1;
  public evolvesFrom: string = 'Finneon';
  public cardType: CardType[] = [W];
  public hp: number = 90;
  public weakness = [{ type: G }];
  public retreat = [];

  public attacks = [
    {
      name: 'Neon Trickery',
      cost: [C, C],
      damage: 50,
      text: 'You may move an Energy from your opponent\'s Active Pokémon to 1 of their Benched Pokémon.'
    }
  ];

  public set: string = 'UNM';
  public setNumber: string = '40';
  public cardImage: string = 'assets/cardback.png';
  public name: string = 'Lumineon';
  public fullName: string = 'Lumineon UNM';

  public reduceEffect(store: StoreLike, state: State, effect: Effect): State {
    // Attack 1: Neon Trickery
    // Ref: set-breakpoint/slowking.ts (Royal Flash - move energy from opponent's active to bench)
    if (WAS_ATTACK_USED(effect, 0, this)) {
      const player = effect.player;
      const opponent = StateUtils.getOpponent(state, player);

      const hasEnergy = opponent.active.cards.some(c => c instanceof EnergyCard);
      const hasBenched = opponent.bench.some(b => b.cards.length > 0);

      if (!hasEnergy || !hasBenched) {
        return state;
      }

      // "You may" - optional
      store.prompt(state, new ConfirmPrompt(
        player.id,
        GameMessage.WANT_TO_USE_ABILITY
      ), wantToUse => {
        if (wantToUse) {
          // Choose an energy from opponent's active
          store.prompt(state, new ChooseCardsPrompt(
            player,
            GameMessage.CHOOSE_CARD_TO_ATTACH,
            opponent.active,
            { superType: SuperType.ENERGY },
            { min: 1, max: 1, allowCancel: false }
          ), selected => {
            const cards: Card[] = selected || [];
            if (cards.length === 0) {
              return;
            }

            // Choose a benched Pokemon to move the energy to
            store.prompt(state, new ChoosePokemonPrompt(
              player.id,
              GameMessage.CHOOSE_POKEMON_TO_ATTACH_CARDS,
              PlayerType.TOP_PLAYER,
              [SlotType.BENCH],
              { min: 1, max: 1, allowCancel: false }
            ), targets => {
              if (targets && targets.length > 0) {
                MOVE_CARDS(store, state, opponent.active, targets[0], { cards: [cards[0]], sourceCard: this });
              }
            });
          });
        }
      });
    }

    return state;
  }
}
