// This file was auto-generated by the card stub generator.
// Card effects were implemented by an agent.
// If you have any questions or feedback, reach out to @C4 in the discord.

import {ADD_SLEEP_TO_PLAYER_ACTIVE, AFTER_ATTACK, DRAW_CARDS, WAS_ATTACK_USED, MOVE_CARDS } from '../../../game/store/prefabs/prefabs';
import { CardType, Stage } from '../../../game/store/card/card-types';
import { StateUtils } from '../../../game/store/state-utils';
import { ShuffleDeckPrompt } from '../../../game/store/prompts/shuffle-prompt';
import { PokemonCard } from '../../../game/store/card/pokemon-card';
import { Effect } from '../../../game/store/effects/effect';
import { State, StoreLike } from '../../../game';
export class Altaria extends PokemonCard {
  public stage: Stage = Stage.STAGE_1;
  public evolvesFrom: string = 'Swablu';
  public cardType: CardType[] = [N];
  public hp: number = 80;
  public weakness = [{ type: Y }];
  public retreat = [C];

  public attacks = [
    {
      name: 'Song of Echoes',
      cost: [C],
      damage: 0,
      text: 'Shuffle your hand into your deck. Then, draw a number of cards equal to the number of Benched Pok\u00e9mon (both yours and your opponent\'s).'
    },
    {
      name: 'Midnight Eyes',
      cost: [W, M],
      damage: 30,
      text: 'Your opponent\'s Active Pok\u00e9mon is now Asleep.'
    }
  ];

  public set: string = 'ROS';
  public setNumber: string = '53';
  public cardImage: string = 'assets/cardback.png';
  public name: string = 'Altaria';
  public fullName: string = 'Altaria ROS';

  public reduceEffect(store: StoreLike, state: State, effect: Effect): State {
    // Attack 1: Song of Echoes
    // Ref: set-primal-clash/manaphy.ts (Deep Sea Swirl - shuffle hand into deck + draw)
    if (WAS_ATTACK_USED(effect, 0, this)) {
      const player = effect.player;
      const opponent = StateUtils.getOpponent(state, player);

      // Count benched Pokemon for both players
      let benchCount = 0;
      player.bench.forEach(b => { if (b.cards.length > 0) benchCount++; });
      opponent.bench.forEach(b => { if (b.cards.length > 0) benchCount++; });

      // Shuffle hand into deck
      const cardsToShuffle = player.hand.cards.slice();
      MOVE_CARDS(store, state, player.hand, player.deck, { cards: cardsToShuffle, sourceCard: this });

      return store.prompt(state, new ShuffleDeckPrompt(player.id), order => {
        player.deck.applyOrder(order);
        if (benchCount > 0) {
          DRAW_CARDS(store, state, player, benchCount);
        }
      });
    }

    // Attack 2: Midnight Eyes
    // Ref: AGENTS-patterns.md (opponent's active is now Asleep)
    if (AFTER_ATTACK(effect, 1, this)) {
      ADD_SLEEP_TO_PLAYER_ACTIVE(store, state, effect.opponent, this);
    }

    return state;
  }
}
