// This file was auto-generated by the card stub generator.
// Card effects were implemented by an agent.
// If you have any questions or feedback, reach out to @C4 in the discord.

import { PokemonCard } from '../../../game/store/card/pokemon-card';
import { Stage, CardType } from '../../../game/store/card/card-types';
import { Card, ChooseCardsPrompt, GameError, GameMessage, PowerType, StoreLike, State, StateUtils } from '../../../game';
import { Effect } from '../../../game/store/effects/effect';
import {WAS_ATTACK_USED, WAS_POWER_USED, USE_ABILITY_ONCE_PER_TURN, ABILITY_USED,
  REMOVE_MARKER_AT_END_OF_TURN, IS_ABILITY_BLOCKED, SEARCH_YOUR_DECK_FOR_POKEMON_AND_PUT_ONTO_BENCH, MOVE_CARDS } from '../../../game/store/prefabs/prefabs';

export class Ninjask extends PokemonCard {
  public stage: Stage = Stage.STAGE_1;
  public evolvesFrom: string = 'Nincada';
  public cardType: CardType[] = [G];
  public hp: number = 70;
  public weakness = [{ type: R }];
  public retreat = [];

  public readonly WING_BUZZ_MARKER = 'NINJASK_ROS_WING_BUZZ_MARKER';

  public powers = [{
    name: 'Wing Buzz',
    useWhenInPlay: true,
    powerType: PowerType.ABILITY,
    text: 'Once during your turn (before your attack), if this Pok\u00e9mon is your Active Pok\u00e9mon, you may discard a card from your hand. If you do, discard the top card of your opponent\'s deck.'
  }];

  public attacks = [
    {
      name: 'Afterimage Assault',
      cost: [G, C],
      damage: 30,
      text: 'Search your deck for up to 2 Ninjask and put them onto your Bench. Shuffle your deck afterward.'
    }
  ];

  public set: string = 'ROS';
  public setNumber: string = '10';
  public cardImage: string = 'assets/cardback.png';
  public name: string = 'Ninjask';
  public fullName: string = 'Ninjask ROS';

  public reduceEffect(store: StoreLike, state: State, effect: Effect): State {
    // Ability: Wing Buzz
    // Refs: set-furious-fists/victreebel.ts (ability discard pattern), AGENTS-patterns.md
    if (WAS_POWER_USED(effect, 0, this)) {
      const player = effect.player;

      if (IS_ABILITY_BLOCKED(store, state, player, this)) {
        throw new GameError(GameMessage.BLOCKED_BY_EFFECT);
      }

      // Must be active
      if (player.active.getPokemonCard() !== this) {
        throw new GameError(GameMessage.CANNOT_USE_POWER);
      }

      // Must have cards in hand to discard
      if (player.hand.cards.length === 0) {
        throw new GameError(GameMessage.CANNOT_USE_POWER);
      }

      const opponent = StateUtils.getOpponent(state, player);

      // Must have cards in opponent's deck to discard
      if (opponent.deck.cards.length === 0) {
        throw new GameError(GameMessage.CANNOT_USE_POWER);
      }

      USE_ABILITY_ONCE_PER_TURN(player, this.WING_BUZZ_MARKER, this);
      ABILITY_USED(player, this);

      // Discard a card from hand
      return store.prompt(state, new ChooseCardsPrompt(
        player,
        GameMessage.CHOOSE_CARD_TO_DISCARD,
        player.hand,
        {},
        { min: 1, max: 1, allowCancel: false }
      ), (selected: Card[]) => {
        const cards = selected || [];
        if (cards.length > 0) {
          MOVE_CARDS(store, state, player.hand, player.discard, { cards: cards, sourceCard: this });
          // Discard the top card of opponent's deck
          if (opponent.deck.cards.length > 0) {
            const topCard = opponent.deck.cards[0];
            MOVE_CARDS(store, state, opponent.deck, opponent.discard, { cards: [topCard], sourceCard: this });
          }
        }
      });
    }

    REMOVE_MARKER_AT_END_OF_TURN(effect, this.WING_BUZZ_MARKER, this);

    // Attack 1: Afterimage Assault
    // Ref: AGENTS-patterns.md (Search deck for Pokemon to bench)
    if (WAS_ATTACK_USED(effect, 0, this)) {
      const player = effect.player;

      SEARCH_YOUR_DECK_FOR_POKEMON_AND_PUT_ONTO_BENCH(store, state, player,
        { name: 'Ninjask' },
        { max: 2 }
      );
    }

    return state;
  }
}
