// This file was auto-generated by the card stub generator.
// Card effects were implemented by an agent.
// If you have any questions or feedback, reach out to @C4 in the discord.

import { PokemonCard } from '../../../game/store/card/pokemon-card';
import { Stage, CardType } from '../../../game/store/card/card-types';
import { PlayerType, StoreLike, State, StateUtils } from '../../../game';
import { Effect } from '../../../game/store/effects/effect';
import {WAS_ATTACK_USED, SHUFFLE_DECK, MOVE_CARDS } from '../../../game/store/prefabs/prefabs';
import { FLIP_A_COIN_IF_HEADS_DEAL_MORE_DAMAGE } from '../../../game/store/prefabs/attack-effects';

export class Unfezant extends PokemonCard {
  public stage: Stage = Stage.STAGE_2;
  public evolvesFrom: string = 'Tranquill';
  public cardType: CardType[] = [C];
  public hp: number = 130;
  public weakness = [{ type: L }];
  public resistance = [{ type: F, value: -20 }];
  public retreat = [C];

  public attacks = [
    {
      name: 'Quick Attack',
      cost: [C],
      damage: 30,
      damageCalculation: '+',
      text: 'Flip a coin. If heads, this attack does 30 more damage.'
    },
    {
      name: 'Strong Winds',
      cost: [C, C, C],
      damage: 0,
      text: 'Shuffle all cards attached to each player\'s Pok\u00e9mon into that player\'s deck.'
    }
  ];

  public set: string = 'ROS';
  public setNumber: string = '80';
  public cardImage: string = 'assets/cardback.png';
  public name: string = 'Unfezant';
  public fullName: string = 'Unfezant ROS';

  public reduceEffect(store: StoreLike, state: State, effect: Effect): State {
    // Attack 1: Quick Attack
    // Ref: set-primal-clash/rhyperior.ts (Stone Edge)
    if (WAS_ATTACK_USED(effect, 0, this)) {
      FLIP_A_COIN_IF_HEADS_DEAL_MORE_DAMAGE(store, state, effect, 30);
    }

    // Attack 2: Strong Winds
    // Ref: AGENTS-patterns.md (shuffle attached cards into deck)
    if (WAS_ATTACK_USED(effect, 1, this)) {
      const player = effect.player;
      const opponent = StateUtils.getOpponent(state, player);

      // Shuffle all attached cards (not the Pokemon themselves) from player's Pokemon into player's deck
      player.forEachPokemon(PlayerType.BOTTOM_PLAYER, (cardList) => {
        const pokemons = cardList.getPokemons();
        const cardsToShuffle = cardList.cards.filter(c => !pokemons.includes(c as PokemonCard));
        cardsToShuffle.forEach(c => {
          MOVE_CARDS(store, state, cardList, player.deck, { cards: [c], sourceCard: this });
        });
        // Also move tools
        const toolsToShuffle = cardList.tools.slice();
        toolsToShuffle.forEach(t => {
          MOVE_CARDS(store, state, cardList, player.deck, { cards: [t], sourceCard: this });
        });
      });

      // Shuffle all attached cards from opponent's Pokemon into opponent's deck
      opponent.forEachPokemon(PlayerType.BOTTOM_PLAYER, (cardList) => {
        const pokemons = cardList.getPokemons();
        const cardsToShuffle = cardList.cards.filter(c => !pokemons.includes(c as PokemonCard));
        cardsToShuffle.forEach(c => {
          MOVE_CARDS(store, state, cardList, opponent.deck, { cards: [c], sourceCard: this });
        });
        // Also move tools
        const toolsToShuffle = cardList.tools.slice();
        toolsToShuffle.forEach(t => {
          MOVE_CARDS(store, state, cardList, opponent.deck, { cards: [t], sourceCard: this });
        });
      });

      SHUFFLE_DECK(store, state, player);
      SHUFFLE_DECK(store, state, opponent);
    }

    return state;
  }
}
