// This file was auto-generated by the card stub generator.
// Card effects were implemented by an agent.
// If you have any questions or feedback, reach out to @C4 in the discord.

import { PokemonCard } from '../../game/store/card/pokemon-card';
import { Stage, CardType, SuperType } from '../../game/store/card/card-types';
import { ChooseCardsPrompt, GameError, GameMessage, PowerType, StoreLike, State, StateUtils, PokemonCardList, CardList } from '../../game';
import { Effect } from '../../game/store/effects/effect';
import {WAS_POWER_USED, IS_ABILITY_BLOCKED, USE_ABILITY_ONCE_PER_TURN, ABILITY_USED, REMOVE_MARKER_AT_END_OF_TURN, SHUFFLE_DECK, SHOW_CARDS_TO_PLAYER, MOVE_CARDS } from '../../game/store/prefabs/prefabs';

export class Manaphy extends PokemonCard {
  public stage: Stage = Stage.BASIC;
  public cardType: CardType[] = [W];
  public hp: number = 70;
  public weakness = [{ type: L }];
  public retreat = [C];

  public powers = [  {
    name: 'Ocean Search',
    useWhenInPlay: true,
    powerType: PowerType.ABILITY,
    text: 'Once during your turn, if this Pokémon is in the Active Spot, you may look at the top 6 cards of your deck, reveal a Pokémon you find there, and put it into your hand. Shuffle the other cards back into your deck.'
  }];

  public attacks = [
    {
      name: 'Wave Splash',
      cost: [W, C],
      damage: 30,
      text: ''
    }
  ];

  public regulationMark: string = 'E';
  public set: string = 'SHF';
  public setNumber: string = '24';
  public cardImage: string = 'assets/cardback.png';
  public name: string = 'Manaphy';
  public fullName: string = 'Manaphy SHF';

  public readonly OCEAN_SEARCH_MARKER = 'MANAPHY_SHF_OCEAN_SEARCH_MARKER';

  public reduceEffect(store: StoreLike, state: State, effect: Effect): State {
    // Ability: Ocean Search
    // Ref: set-unbroken-bonds/sharpedo.ts (Greedy Evolution - top 6 cards look pattern),
    //      set-sword-and-shield/orbeetle.ts (Bug's Radar - once per turn, CardList moveTo)
    if (WAS_POWER_USED(effect, 0, this)) {
      const player = effect.player;

      if (IS_ABILITY_BLOCKED(store, state, player, this)) {
        throw new GameError(GameMessage.BLOCKED_BY_EFFECT);
      }

      // Check if this Pokemon is in the Active Spot
      const cardList = StateUtils.findCardList(state, this) as PokemonCardList;
      if (cardList !== player.active) {
        throw new GameError(GameMessage.CANNOT_USE_POWER);
      }

      if (player.deck.cards.length === 0) {
        throw new GameError(GameMessage.CANNOT_USE_POWER);
      }

      USE_ABILITY_ONCE_PER_TURN(player, this.OCEAN_SEARCH_MARKER, this);
      ABILITY_USED(player, this);

      // Look at top 6 cards
      const topCards = new CardList();
      const count = Math.min(6, player.deck.cards.length);
      MOVE_CARDS(store, state, player.deck, topCards, { count: count, sourceCard: this });

      const opponent = StateUtils.getOpponent(state, player);

      // Player chooses 1 Pokemon from top cards (optional)
      return store.prompt(state, new ChooseCardsPrompt(
        player,
        GameMessage.CHOOSE_CARD_TO_HAND,
        topCards,
        { superType: SuperType.POKEMON },
        { min: 0, max: 1, allowCancel: false }
      ), selected => {
        const cards = selected || [];

        if (cards.length > 0) {
          // Reveal the chosen Pokemon to the opponent
          SHOW_CARDS_TO_PLAYER(store, state, opponent, cards);
          // Put chosen Pokemon into hand
          MOVE_CARDS(store, state, topCards, player.hand, { cards: cards, sourceCard: this });
        }

        // Shuffle remaining cards back into deck
        MOVE_CARDS(store, state, topCards, player.deck, { sourceCard: this });
        SHUFFLE_DECK(store, state, player);
      });
    }

    REMOVE_MARKER_AT_END_OF_TURN(effect, this.OCEAN_SEARCH_MARKER, this);

    return state;
  }
}
