// This file was auto-generated by the card stub generator.
// Card effects were implemented by an agent.
// If you have any questions or feedback, reach out to @C4 in the discord.

import { PokemonCard } from '../../../game/store/card/pokemon-card';
import { Stage, CardType, CardTag, SuperType } from '../../../game/store/card/card-types';
import { StoreLike, State, GameMessage, ShuffleDeckPrompt } from '../../../game';
import { Effect } from '../../../game/store/effects/effect';
import {WAS_ATTACK_USED, MOVE_CARDS } from '../../../game/store/prefabs/prefabs';
import { DISCARD_A_STADIUM_CARD_IN_PLAY } from '../../../game/store/prefabs/attack-effects';
import { EvolveEffect } from '../../../game/store/effects/game-effects';
import { ChooseCardsPrompt } from '../../../game/store/prompts/choose-cards-prompt';

export class GlaceonV extends PokemonCard {
  protected _tags = [CardTag.POKEMON_V];
  public stage: Stage = Stage.BASIC;
  public cardType: CardType[] = [W];
  public hp: number = 210;
  public weakness = [{ type: M }];
  public retreat = [C, C];

  public attacks = [
    {
      name: 'Frozen Awakening',
      cost: [W],
      damage: 0,
      text: 'Search your deck for a card that evolves from this Pokémon and put it onto this Pokémon to evolve it. Then, shuffle your deck.',
    },
    {
      name: 'Heavy Snow',
      cost: [W, C, C],
      damage: 120,
      text: 'Discard a Stadium in play.',
    },
  ];

  public regulationMark: string = 'E';
  public set: string = 'EVS';
  public setNumber: string = '40';
  public cardImage: string = 'assets/cardback.png';
  public name: string = 'Glaceon V';
  public fullName: string = 'Glaceon V EVS';

  public reduceEffect(store: StoreLike, state: State, effect: Effect): State {
    // Attack 1: Frozen Awakening
    // Ref: set-sun-and-moon/rare-candy.ts (EvolveEffect), set-sword-and-shield/drizzile.ts (deck search + evolve)
    if (WAS_ATTACK_USED(effect, 0, this)) {
      const player = effect.player;

      // Block cards in deck that don't evolve from Glaceon V
      const blocked: number[] = [];
      player.deck.cards.forEach((card, index) => {
        if (card.superType !== SuperType.POKEMON) {
          blocked.push(index);
          return;
        }
        const pokemonCard = card as PokemonCard;
        if (pokemonCard.evolvesFrom !== 'Glaceon V') {
          blocked.push(index);
        }
      });

      const hasEvolution = player.deck.cards.some((card, index) => !blocked.includes(index));
      if (!hasEvolution) {
        return state;
      }

      return store.prompt(
        state,
        new ChooseCardsPrompt(
          player,
          GameMessage.CHOOSE_CARD_TO_HAND,
          player.deck,
          { superType: SuperType.POKEMON },
          { min: 1, max: 1, allowCancel: true, blocked },
        ),
        (selected) => {
          const cards = selected || [];
          if (cards.length === 0) {
            return;
          }

          const pokemonCard = cards[0] as PokemonCard;

          // Move card to hand temporarily for EvolveEffect
          MOVE_CARDS(store, state, player.deck, player.hand, { cards: [pokemonCard], sourceCard: this });

          // Evolve this Pokemon using EvolveEffect
          const evolveEffect = new EvolveEffect(player, player.active, pokemonCard);
          store.reduceEffect(state, evolveEffect);

          // Shuffle deck
          return store.prompt(state, new ShuffleDeckPrompt(player.id), (order) => {
            player.deck.applyOrder(order);
          });
        },
      );
    }

    // Attack 2: Heavy Snow
    // Ref: attack-effects.ts (DISCARD_A_STADIUM_CARD_IN_PLAY)
    if (WAS_ATTACK_USED(effect, 1, this)) {
      DISCARD_A_STADIUM_CARD_IN_PLAY(state);
    }

    return state;
  }
}
