// This file was auto-generated by the card stub generator.
// Card effects were implemented by an agent.
// If you have any questions or feedback, reach out to @C4 in the discord.

import { PokemonCard } from '../../../game/store/card/pokemon-card';
import { Stage, CardType } from '../../../game/store/card/card-types';
import { PowerType, StoreLike, State } from '../../../game';
import { Effect } from '../../../game/store/effects/effect';
import { EVOLUTIONARY_ADVANTAGE } from '../../../game/store/prefabs/prefabs';

export class Clamperl extends PokemonCard {
  public stage: Stage = Stage.BASIC;
  public cardType: CardType[] = [W];
  public hp: number = 50;
  public weakness = [{ type: G }];
  public retreat = [C, C, C];

  public powers = [{
    name: 'Evolutionary Advantage',
    powerType: PowerType.ABILITY,
    text: 'If you go second, this Pokémon can evolve during your first turn.'
  }];

  public attacks = [
    {
      name: 'Sparkling Pearl',
      cost: [W],
      damage: 10,
      text: ''
    }
  ];

  public set: string = 'CES';
  public setNumber: string = '41';
  public cardImage: string = 'assets/cardback.png';
  public name: string = 'Clamperl';
  public fullName: string = 'Clamperl CES';

  public reduceEffect(store: StoreLike, state: State, effect: Effect): State {
    return EVOLUTIONARY_ADVANTAGE(store, state, effect, this);
  }
}
