// This file was auto-generated by the card stub generator.
// Card effects were implemented by an agent.
// If you have any questions or feedback, reach out to @C4 in the discord.

import { PokemonCard } from '../../../game/store/card/pokemon-card';
import { Stage, CardType, SuperType } from '../../../game/store/card/card-types';
import { PowerType, StoreLike, State, StateUtils, SpecialCondition, GameMessage, ChooseCardsPrompt, PokemonCardList } from '../../../game';
import { Effect } from '../../../game/store/effects/effect';
import {WAS_ATTACK_USED, WAS_POWER_USED, IS_ABILITY_BLOCKED, ABILITY_USED, USE_ABILITY_ONCE_PER_TURN, REMOVE_MARKER_AT_END_OF_TURN, SHUFFLE_DECK, ADD_CONFUSION_TO_PLAYER_ACTIVE, MOVE_CARDS } from '../../../game/store/prefabs/prefabs';
import { YOUR_OPPPONENTS_ACTIVE_POKEMON_IS_NOW_CONFUSED } from '../../../game/store/prefabs/attack-effects';

export class Inkay extends PokemonCard {
  public readonly UPSIDE_DOWN_EVOLUTION_MARKER = 'INKAY_UPSIDE_DOWN_EVOLUTION_MARKER';
  public stage: Stage = Stage.BASIC;
  public cardType: CardType[] = [D];
  public hp: number = 60;
  public weakness = [{ type: F }];
  public resistance = [{ type: P, value: -20 }];
  public retreat = [C];

  public powers = [{
    name: 'Upside-Down Evolution',
    useWhenInPlay: true,
    powerType: PowerType.ABILITY,
    text: 'Once during your turn, (before your attack), if this Pokémon is Confused, you may search your deck for a card that evolves from this Pokémon and put it onto this Pokémon. (This counts as evolving this Pokémon.) Shuffle your deck afterward.'
  }];

  public attacks = [
    {
      name: 'Confusion Wave',
      cost: [D],
      damage: 0,
      text: 'Both Active Pokémon are now Confused.'
    }
  ];

  public set: string = 'XY';
  public setNumber: string = '74';
  public cardImage: string = 'assets/cardback.png';
  public name: string = 'Inkay';
  public fullName: string = 'Inkay XY';

  public reduceEffect(store: StoreLike, state: State, effect: Effect): State {
    // Ability: Upside-Down Evolution
    // Ref: CLAUDE-effects.md (Conditional Evolution Search pattern)
    if (WAS_POWER_USED(effect, 0, this)) {
      const player = effect.player;

      if (IS_ABILITY_BLOCKED(store, state, player, this)) {
        return state;
      }

      // This ability can only be used if this Pokemon is Confused (must be Active)
      const cardList = StateUtils.findCardList(state, this) as PokemonCardList;
      if (cardList !== player.active) {
        return state;
      }

      if (!player.active.specialConditions.includes(SpecialCondition.CONFUSED)) {
        return state;
      }

      USE_ABILITY_ONCE_PER_TURN(player, this.UPSIDE_DOWN_EVOLUTION_MARKER, this);
      ABILITY_USED(player, this);

      // Search deck for a card that evolves from Inkay
      const blocked: number[] = [];
      player.deck.cards.forEach((card, index) => {
        if (!(card instanceof PokemonCard) || card.evolvesFrom !== 'Inkay') {
          blocked.push(index);
        }
      });

      return store.prompt(state, new ChooseCardsPrompt(
        player,
        GameMessage.CHOOSE_CARD_TO_EVOLVE,
        player.deck,
        { superType: SuperType.POKEMON },
        { min: 0, max: 1, allowCancel: true, blocked }
      ), cards => {
        if (cards && cards.length > 0) {
          const evolutionCard = cards[0] as PokemonCard;
          MOVE_CARDS(store, state, player.deck, cardList, { cards: [evolutionCard], sourceCard: this });
          cardList.clearEffects();
          cardList.pokemonPlayedTurn = state.turn;
        }
        SHUFFLE_DECK(store, state, player);
      });
    }

    REMOVE_MARKER_AT_END_OF_TURN(effect, this.UPSIDE_DOWN_EVOLUTION_MARKER, this);

    // Attack 1: Confusion Wave
    // Ref: set-dragons-exalted/stunky.ts (condition application)
    if (WAS_ATTACK_USED(effect, 0, this)) {
      const player = effect.player;
      YOUR_OPPPONENTS_ACTIVE_POKEMON_IS_NOW_CONFUSED(store, state, effect);
      ADD_CONFUSION_TO_PLAYER_ACTIVE(store, state, player, this);
    }

    return state;
  }
}
