// This file was auto-generated by the card stub generator.
// Card effects were implemented by an agent.
// If you have any questions or feedback, reach out to @C4 in the discord.

import { PokemonCard } from '../../../game/store/card/pokemon-card';
import { Stage, CardType } from '../../../game/store/card/card-types';
import { StoreLike, State, StateUtils } from '../../../game';
import { CheckProvidedEnergyEffect } from '../../../game/store/effects/check-effects';
import { Effect } from '../../../game/store/effects/effect';
import {WAS_ATTACK_USED, MOVE_CARDS } from '../../../game/store/prefabs/prefabs';

export class Jigglypuff extends PokemonCard {
  public stage: Stage = Stage.BASIC;
  public cardType: CardType[] = [Y];
  public hp: number = 60;
  public weakness = [{ type: M }];
  public resistance = [{ type: D, value: -20 }];
  public retreat = [C];

  public attacks = [
    {
      name: 'Rollout',
      cost: [C],
      damage: 10,
      text: ''
    },
    {
      name: 'Heartfelt Song',
      cost: [Y],
      damage: 0,
      text: 'Discard a [D] Energy attached to your opponent\'s Active Pokémon.'
    }
  ];

  public set: string = 'XY';
  public setNumber: string = '87';
  public cardImage: string = 'assets/cardback.png';
  public name: string = 'Jigglypuff';
  public fullName: string = 'Jigglypuff XY';

  public reduceEffect(store: StoreLike, state: State, effect: Effect): State {
    // Attack 2: Heartfelt Song
    // Ref: set-boundaries-crossed/psyduck-2.ts (Firefighting)
    if (WAS_ATTACK_USED(effect, 1, this)) {
      const player = effect.player;
      const opponent = StateUtils.getOpponent(state, player);

      const checkProvidedEnergy = new CheckProvidedEnergyEffect(opponent, opponent.active);
      state = store.reduceEffect(state, checkProvidedEnergy);

      const darkEnergyCards = checkProvidedEnergy.energyMap
        .filter(em => em.provides.includes(CardType.DARK) || em.provides.includes(CardType.ANY))
        .map(em => em.card);

      if (darkEnergyCards.length > 0) {
        const cardToDiscard = darkEnergyCards[0];
        if (opponent.active.cards.includes(cardToDiscard)) {
          MOVE_CARDS(store, state, opponent.active, opponent.discard, { cards: [cardToDiscard], sourceCard: this });
        }
      }
    }

    return state;
  }
}
