// This file was auto-generated by the card stub generator.
// Card effects were implemented by an agent.
// If you have any questions or feedback, reach out to @C4 in the discord.

import { PokemonCard } from '../../../game/store/card/pokemon-card';
import { Stage, CardType, EnergyType } from '../../../game/store/card/card-types';
import { StoreLike, State, CardList } from '../../../game';
import { EnergyCard } from '../../../game/store/card/energy-card';
import { Effect } from '../../../game/store/effects/effect';
import {WAS_ATTACK_USED, MOVE_CARDS } from '../../../game/store/prefabs/prefabs';

export class Rhyhorn extends PokemonCard {
  public stage: Stage = Stage.BASIC;
  public cardType: CardType[] = [F];
  public hp: number = 80;
  public weakness = [{ type: G }];
  public retreat = [C, C, C];

  public attacks = [
    {
      name: 'Dig Out',
      cost: [F],
      damage: 10,
      text: 'Discard the top card of your deck. If that card is a [F] Energy, attach it to this Pokémon.'
    },
    {
      name: 'Horn Drill',
      cost: [F, C, C],
      damage: 40,
      text: ''
    }
  ];

  public set: string = 'XY';
  public setNumber: string = '60';
  public cardImage: string = 'assets/cardback.png';
  public name: string = 'Rhyhorn';
  public fullName: string = 'Rhyhorn XY';

  public reduceEffect(store: StoreLike, state: State, effect: Effect): State {
    // Attack 1: Dig Out
    // Ref: set-legendary-treasures/excadrill-ex.ts (Dig Out)
    if (WAS_ATTACK_USED(effect, 0, this)) {
      const player = effect.player;

      if (player.deck.cards.length === 0) {
        return state;
      }

      const topOfDeck = new CardList();
      MOVE_CARDS(store, state, player.deck, topOfDeck, { count: 1, sourceCard: this });
      const topCard = topOfDeck.cards[0];

      if (topCard instanceof EnergyCard && topCard.energyType === EnergyType.BASIC && topCard.provides.includes(CardType.FIGHTING)) {
        MOVE_CARDS(store, state, topOfDeck, player.active, { cards: [topCard], sourceCard: this });
      } else {
        MOVE_CARDS(store, state, topOfDeck, player.discard, { sourceCard: this });
      }
    }

    return state;
  }
}
